CONTRIBUTING.md

Delete the duplicated 'a'

---

src/js/player.js

document the error event

---

Gruntfile.js
package.json

If I don't get a watchify task to work I'll start punching people in the face. Seriously, we need it to stay sane or we have to wait 30 secs everytime we want to just console.log something.

Added watchify task

---

Gruntfile.js
package.json
src/js/core.js
test/api/api.js
test/index.html
test/karma.conf.js

Get test/index.html working when loaded directly into a browser. Remove extra browserifying via karma. Add timing info to to grunt output.

Grunt improvements

---

src/css/video-js.less

Same changes as pull request against master as per request. https://github.com/videojs/video.js/pull/1868#issuecomment-101025010

Added background-color to vjs-poster to remove transparent borders around scaled poster image

---

CHANGELOG.md
src/js/control-bar/text-track-controls/chapters-button.js
src/js/menu/menu-button.js

Fixed instances of tabIndex that did not have a capital I [#2176]

---

src/css/components/_layout.scss

Reverted .video-js inline-block style to fix Flash fullscreen

---

package.json

Pick up a fix for video dimensions being ignored after the first metadata tag.

Bump the SWF up to 4.7.1

---

test/index.html
test/unit/player.test.js
test/unit/tech/tech.test.js

- Removed incompatible module
- Added ie8 shim to qunit index.html
- Fixed extends() usage

Fix IE8 tests

---

src/js/utils/browser.js
src/js/utils/buffer.js
src/js/utils/dom.js
src/js/utils/events.js
src/js/utils/fn.js
src/js/utils/format-time.js
src/js/utils/guid.js
src/js/utils/log.js
src/js/utils/merge-options.js
src/js/utils/stylesheet.js
src/js/utils/time-ranges.js
src/js/utils/to-title-case.js
src/js/utils/url.js

Makes `src/js/utils/` pass videojs-standard.
Previous discussion in #3460

videojs-standard Utils

---

src/js/tracks/audio-track-list.js
src/js/tracks/audio-track.js
src/js/tracks/html-track-element-list.js
src/js/tracks/html-track-element.js
src/js/tracks/text-track-cue-list.js
src/js/tracks/text-track-display.js
src/js/tracks/text-track-list-converter.js
src/js/tracks/text-track-settings.js
src/js/tracks/text-track.js
src/js/tracks/track-enums.js
src/js/tracks/track-list.js
src/js/tracks/track.js
src/js/tracks/video-track.js

Makes `src/js/tracks/` pass videojs-standard.
Previous discussion in #3461

videojs-standard Tracks

---

src/js/tech/flash-rtmp.js
src/js/tech/flash.js
src/js/tech/html5.js
src/js/tech/loader.js
src/js/tech/tech.js

Makes `src/js/tech/` pass videojs-standard.
Previous discussion in #3462

videojs-standard Tech

---

src/js/menu/menu-button.js
src/js/menu/menu-item.js
src/js/menu/menu.js
src/js/popup/popup-button.js
src/js/popup/popup.js
src/js/slider/slider.js

Makes `src/js/menu/`, `src/js/popup/`, and `src/js/slider/` pass videojs-standard.

videojs-standard Menu, Popup, Slider

---

test/api/api.js
test/globals-shim.js
test/unit/tracks/text-track.test.js
test/unit/tracks/text-tracks.test.js
test/unit/tracks/track-baseline.js
test/unit/tracks/track-list.test.js
test/unit/tracks/track.test.js
test/unit/tracks/video-track-list.test.js
test/unit/tracks/video-track.test.js
test/unit/tracks/video-tracks.test.js

linted the other half of the `test/unit/tracks` folder and some other misc files

vjsstandard - Tests - Other 1/2 of Tracks folder + Misc

---

test/unit/tracks/audio-track-list.test.js
test/unit/tracks/audio-track.test.js
test/unit/tracks/audio-tracks.test.js
test/unit/tracks/html-track-element-list.test.js
test/unit/tracks/html-track-element.test.js
test/unit/tracks/text-track-controls.test.js
test/unit/tracks/text-track-cue-list.test.js
test/unit/tracks/text-track-list-converter.test.js
test/unit/tracks/text-track-list.test.js
test/unit/tracks/text-track-settings.test.js

linted half of the unit tests in the test/unit/tracks folder

vjsstandard - Tests - 1/2 of Tracks folder

---

test/unit/tech/flash-rtmp.test.js
test/unit/tech/flash.test.js
test/unit/tech/html5.test.js
test/unit/tech/tech-faker.js
test/unit/tech/tech.test.js

run `vjsstandard` on all of the tests in the tech folder of test/unit

vjsstandard - Tests - Tech folder 

---

docs/translations-needed.md
lang/fr.json

I added the missing line.
PS: I installed grunt but several errors interrupt the update of the `translations-needed.md` file... Could you update this file?

French translation - add a missing line

---

src/js/player.js

* refactor all event handling logic around tech
* remove unused code
* Save another 454 bytes on top of the previous PR (0.7%)
* This PR depends upon #3593 
Find a way to generate documentation for all the methods that are now dynamic, without compromising on the size of video.js

refactor redundant/verbose code in player.js

---

docs/translations-needed.md
lang/zh-TW.json

update docs, complete zh-TW.json
update:
docs/translations-needed.md
lang/zh-TW.json

 Complete work translated into traditional Chinese

---

src/js/tracks/text-track-settings.js
src/js/utils/dom.js
src/js/utils/obj.js
test/unit/tracks/text-track-settings.test.js
test/unit/utils/dom.test.js
test/unit/utils/obj.test.js

Refactor TextTrackSettings: Complete

---

COLLABORATOR_GUIDE.md

This adds a collaborator guide that describes how to reply to issues and
PRs and how to accept changes to the project.

docs(collaborator_guide): add collaborator guide

---

.github/PULL_REQUEST_TEMPLATE.md

Add a question to the PR template to ask about changes being verified in the browser.

Add a checkbox to the PR template: Was this verified in a browser?

---

docs/guides/components.md

fix typo, extends -> extend

---

src/js/player.js
src/js/setup.js
src/js/slider/slider.js

- player.js
- setup.js
- slider.js

Update the jsdoc comments to modern syntax - Part 3

---

src/js/poster-image.js
src/js/tech/flash-rtmp.js
src/js/tech/flash.js
src/js/tech/html5.js
src/js/tech/loader.js
src/js/tech/tech.js

`src/js/tech/*`
`src/js/poster-image`

Update the jsdoc comments to modern syntax - Part 4 

---

src/js/tracks/audio-track-list.js
src/js/tracks/audio-track.js
src/js/tracks/html-track-element-list.js
src/js/tracks/html-track-element.js
src/js/tracks/text-track-cue-list.js
src/js/tracks/text-track-display.js
src/js/tracks/text-track-list-converter.js
src/js/tracks/text-track-list.js
src/js/tracks/text-track-settings.js
src/js/tracks/text-track.js
src/js/tracks/track-enums.js
src/js/tracks/track-list.js
src/js/tracks/track.js
src/js/tracks/video-track-list.js
src/js/tracks/video-track.js
src/js/utils/browser.js
src/js/utils/buffer.js
src/js/utils/computed-style.js
src/js/utils/fn.js
src/js/utils/format-time.js
src/js/utils/guid.js
src/js/utils/obj.js
src/js/utils/stylesheet.js
src/js/utils/time-ranges.js
src/js/utils/to-title-case.js

Updated all of tracks and some of utils!

Update the jsdoc comments to modern syntax - Part 5

---

src/js/utils/time-ranges.js
test/unit/utils/time-ranges.test.js

Remove TimeRanges without an index deprecation warning.

Remove TimeRanges without an index deprecation warning

---

docs/translations-needed.md
lang/en.json
src/css/components/_play-pause.scss
src/js/control-bar/play-toggle.js

Replay button appears when content has finished playing

Replay at ended

---

src/js/control-bar/audio-track-controls/audio-track-button.js
src/js/control-bar/audio-track-controls/audio-track-menu-item.js
src/js/control-bar/text-track-controls/descriptions-button.js
src/js/control-bar/text-track-controls/text-track-button.js
src/js/control-bar/text-track-controls/text-track-menu-item.js
src/js/player.js
src/js/tech/html5.js
src/js/tech/tech.js
src/js/tracks/audio-track-list.js
src/js/tracks/text-track-display.js
src/js/tracks/text-track-list.js
src/js/tracks/text-track.js
src/js/tracks/track-list.js
src/js/tracks/track-types.js
src/js/tracks/video-track-list.js
test/unit/tech/tech.test.js
test/unit/tracks/audio-track-list.test.js
test/unit/tracks/html-track-element.test.js
test/unit/tracks/text-track-list-converter.test.js
test/unit/tracks/text-track.test.js
test/unit/tracks/text-tracks.test.js
test/unit/tracks/track-list.test.js
test/unit/tracks/track.test.js
test/unit/tracks/video-track-list.test.js

This PR was already reviewed and approved [here](https://github.com/videojs/video.js/pull/3744). This one will allow us to use browserstack to make sure that IE8-11 is not broken.

Unify all Track and TrackList APIs

---

docs/faq.md

Fix Broken FAQ links

---

docs/guides/components.md
docs/guides/event-target.md
docs/guides/plugins.md
docs/guides/videojs.md

Update docs using the package.json `docs:fix` script

Run docs:fix to update TOC on manual docs

---

docs/translations-needed.md
lang/de.json
lang/fr.json

Added German and French translations of "replay" and updated doc.

DE and FR translations of replay

---

src/css/components/_audio.scss
src/css/components/_big-play.scss
src/css/components/_captions.scss
src/css/components/_chapters.scss
src/css/components/_close-button.scss
src/css/components/_control.scss
src/css/components/_descriptions.scss
src/css/components/_fullscreen.scss
src/css/components/_play-pause.scss
src/css/components/_subtitles.scss
src/css/components/_volume.scss
src/js/button.js
src/js/clickable-component.js

Wrap font-icons in a span with aria-hidden=true on it.
Fixes #3982.

fix: hide font-icons from assitive technology

---

package.json
sandbox/flash.html.example
sandbox/index.html.example

Also add an example of using flash in the sandbox

Add flash as a dev dependency

---

src/js/control-bar/play-toggle.js
src/js/extend.js
src/js/player.js
src/js/tech/tech.js
src/js/tracks/audio-track.js
src/js/tracks/html-track-element-list.js
src/js/tracks/html-track-element.js
src/js/tracks/text-track-cue-list.js
src/js/tracks/text-track-display.js
src/js/tracks/text-track.js
src/js/tracks/track-list.js
src/js/tracks/track-types.js
src/js/tracks/track.js
src/js/tracks/video-track.js
src/js/utils/computed-style.js

There are still two globals that I can't figure out how to fix properly:
* TextTrackCue typedef in the TextTrackCueList
* mergeOptions
Though, I don't think those two should hold this PR up.

docs: fixup global members

---

test/unit/utils/obj.test.js

A question was brought up about `Obj.assign`s behavior, I wrote some unit tests to clear things up.

test: add tests for obj.assign util

---

src/js/menu/menu-item.js

feat: wrap menu item text in a span

---

src/css/video-js.scss

See https://github.com/videojs/video.js/pull/4061

[5.x] fix(sass): import path has cwd once again

---

build/grunt.js
docs/translations-needed.md
lang/en.json
src/js/component.js
src/js/control-bar/progress-control/seek-bar.js

feat: allow tokens in localize, localize progress bar time

---

docs/translations-needed.md
lang/fr.json

French translation update
Update + remove a duplicate translation + a typo

French translation update

---

build/grunt.js

Port of #4008 over to the master branch.

Change accessibility test in grunt.js to remove unnecessary warning message

---

build/grunt.js

This brings changes we currently have in master to the 5.x branch.

chore(build): lint errors only and silence webpack

---

src/js/control-bar/playback-rate-menu/playback-rate-menu-item.js

fix(playback rate menu): playback rate menu items should be selectable

---

package.json

update video-js-swf to 5.3.0

---

src/js/control-bar/text-track-controls/subs-caps-button.js

This is a followup from https://github.com/videojs/video.js/pull/4157 but for the subs-caps button.

fix(subs-caps-button): add hide threshold to subs-caps button

---

CODE_OF_CONDUCT.md
README.md
package.json

~~@videojs/core-committers please take a look. I used [weallbehave](https://github.com/WeAllJS/weallbehave) to generate the CoC.~~
It is now using [Contributor Covenant](http://contributor-covenant.org). See [this comment](https://github.com/videojs/video.js/pull/4160#issuecomment-286178821)

docs(coc): introduce CODE_OF_CONDUCT.md

---

package.json
src/js/tech/tech.js

update videojs-vtt.js to 0.12.3

---

src/js/component.js

fix a comment typo

---

.travis.yml

Add slack notifications for the 5.x branch like we have in master.

chore: add slack travis notifications (#4282)

---

src/js/player.js

typo soruce -> source

---

package.json
src/js/player.js
src/js/tech/html5.js
src/js/tech/tech.js
test/api/api.js
test/unit/tech/html5.test.js
test/unit/tech/tech.test.js

Video.js 6 version of https://github.com/videojs/video.js/pull/4286

Get video playback quality

---

src/js/player.js
src/js/tech/html5.js
src/js/tech/tech.js
test/unit/player.test.js
test/unit/setup.test.js
test/unit/tech/html5.test.js

This is a sister for [this 5.x PR](https://github.com/videojs/video.js/pull/4325)

Allow 'playsinline' player option (sister)

---

src/js/control-bar/text-track-controls/text-track-menu-item.js

This is the 5.x version of https://github.com/videojs/video.js/pull/4298

fix: Only update text track mode if changed

---

sandbox/combined-tracks.html.example
sandbox/descriptions.html.example
sandbox/flash.html.example
sandbox/index.html.example
sandbox/language.html.example
sandbox/plugin.html.example

I noticed these do not appear to be up to date with the latest Rollup-based build changes.

Fix paths in sandbox files.

---

build/version.js

Removed an unused var in build/version.js
Removed a single line of code

Removed unused var in version.js

---

test/unit/player.test.js

Unit tests for [this fix](https://github.com/videojs/video.js/pull/4443).

added unit tests for player.duration()

---

build/bin/release-next.sh

I've been using this to release the 5.x branch for a while. I've also just ran it through http://www.shellcheck.net/

chore: add a release script to makes things easier

---

src/js/tech/html5.js

Thanks for catching this @imbcmdth.

fix: use typeof for checking preload option

---

package.json

More info available in #4580.
Fixes #4580.

fix(package): remove pkg.module

---

docs/guides/plugins.md

document how to add a version number to a plugin

---

docs/translations-needed.md
lang/pl.json

Fixes a typo in pl.json. Also updated the translations needed doc, although it will need updating again once the other pending lang PRs are merged.

chore(lang): Update Polish

---

src/css/_private-variables.scss

Add comment for avoiding helvetica font

---

test/unit/modal-dialog.test.js

Also, add a test that verifies the behavior for the PR (#4690).
Fixes #4706.

test: fix modal dialog test for showing controls

---

src/js/player.js

refactor player.techGet_()

---

lang/zh-CN.json

Add translation for "caption settings"
Added a single line.

Add translation for "caption settings"

---

src/css/components/_layout.scss

Add word-break to fix progress bar bug
fixes: #2964

fix progress bar bug by adding word-break

---

package-lock.json
src/js/control-bar/progress-control/seek-bar.js

Fix for issue #4853.
Tests are passing.

Fix for #4853: Unhandled promise rejection in Safari

---

package.json

chore(package): update shelljs to version 0.8.1

---

build/netlify-docs.js
package-lock.json
package.json

Using `git tag --contains` to see if the commit ref that netlify gives us is a tagged commit, unfortunately, wasn't working in the master branch. Instead, use the git commit message and use semver to verify that it is a valid commit message.

chore: use git commit message for netlify

---

test/karma.conf.js

videojs/http-streaming is starting to run tests in browserstack so we should name our runs better.

test: add project and build names to browserstack

---

docs/guides/react.md

Update docs for react tutorial (#4935)

---

docs/guides/plugins.md

fix: changed paused to pause where appropriate
- [x ] Docs/guides updated

fix: changed paused to pause where appropriate

---

.github/first-timers-issue-template.md

We work slightly differently than the default first-timers-bot instructions, otherwise, it's mostly the same as the defaults in here https://github.com/hoodiehq/first-timers-bot

chore: add first-timers-issue-template.md

---

src/js/utils/dom.js

Fix misspellings

---

src/js/utils/time-ranges.js

function getRange has wrong comment.

fix wrong comment

---

build/grunt.js
test/karma.conf.js

test: no longer test on IE8, IE9, or IE10

---

src/js/tech/html5.js
src/js/tech/setup-sourceset.js

6.x refactor: move sourceset code out of tech

---

test/karma.conf.js

This PR updates the karma tests to use more modern and popular versions of Windows/Mac OS

test: update karma browser OS versions

---

package-lock.json
package.json
test/index.html

Since we no longer support IE8, we can actually update our qunit version.

chore(test): upgrade qunit and karma-qunit to latest

---

src/js/player.js
test/unit/sourceset.test.js

6.x fix/let tech preload

---

src/js/clickable-component.js
src/js/poster-image.js
src/js/slider/slider.js
src/js/tech/loader.js
src/js/tech/middleware.js
src/js/tracks/text-track-display.js

fix some misspellings

---

docs/index.md

add link to debugging guide

---

test/unit/player.test.js

Tested in the official win7 IE8 VM this time, so it should be good to go.

test: fix queue playing events test for ie8 (for real this time)

---

src/js/player.js
src/js/utils/filter-source.js
src/js/utils/mimetypes.js
test/unit/sourceset.test.js

feat(6.x): update the players source cache on sourceset (#5040)

---

src/js/player.js
test/unit/sourceset.test.js

feat: copy properties from <video-js> to the media el (#5039)

---

src/js/player.js
src/js/tech/html5.js
src/js/tech/setup-sourceset.js
src/js/utils/filter-source.js
test/unit/sourceset.test.js

fix: `sourceset` and browser behavior inconsistencies (#5054)

---

src/js/resize-manager.js
test/unit/player.test.js

tests: do not throw on tech/player dispose

---

package-lock.json
package.json

Upgrade to 1.0.2 which contains babel build fixes.
Fixes #5186

chore(package): Upgrade @videojs/http-streaming

---

COLLABORATOR_GUIDE.md

Clarify how to enter the header and body text when Landing a PR using the GitHub UI.

Clarify how to Land a PR using the GitHub UI

---

package-lock.json
package.json

 chore(package): update rollup to version 0.59.3

---

package-lock.json
package.json

Greenkeeper/conventional changelog cli 2.0.1

---

package-lock.json
package.json

chore(package): update rollup to version 0.61.1

---

package-lock.json
package.json

 chore(package): update grunt-zip to version 0.18.1 🚀

---

package-lock.json
package.json

Upgrade to VHS 1.1.0 to pick up the easier overrideNative option.

chore(package): upgrade to VHS 1.1.0

---

lang/sk.json

Adding `"{1} is loading."` translation for SK lang.

Just one missing line on sk.json lang file

---

package-lock.json
package.json

chore(package): update rollup to version 0.63.4

---

package-lock.json
package.json

chore(package): update autoprefixer to version 9.0.1

---

src/js/tracks/text-track.js

Fixes https://github.com/videojs/video.js/issues/5131

Fix subtitles/captions freeze when using uglify

---

package-lock.json
package.json

chore(package): update rollup to version 0.64.1

---

package-lock.json
package.json

fix(package): update @videojs/http-streaming to version 1.2.3

---

package-lock.json
package.json

chore(package): update grunt-cli to version 1.3.1

---

src/js/player.js

fix: make sure all attrs are updated before applying to tag

---

package-lock.json
src/js/resize-manager.js
src/js/utils/fn.js

6.x version of videojs/video.js#5390

test: fix travis ci issues with resize-manager tests

---

docs/guides/layout.md

~~Depends on https://github.com/videojs/video.js/pull/5478~~

docs(layout): document fluid and fill mode

---

src/js/player.js
test/unit/sourceset.test.js
test/unit/tech/tech-faker.js

fix: blob sources being updated in the source cache

---

build/netlify-docs.js
rollup.config.js

Refactor of the clean task added docs/api, which didn't happen
previously. Re-order when things are generated to work around it.
Also, don't show rollup progress on netlify either.

chore(netlify): make docs build properly

---

docs/guides/options.md
src/js/live-tracker.js
test/unit/live-tracker.test.js

* Less strict live edge detection
* documentation for `liveui` option

Docs for livui and less strict live edge

---

docs/guides/live.md

Adds a guide for the new live API and information on switching between the new and old live ui.

docs(live): Add a guide for the live ui and live api

---

package-lock.json
package.json

chore(package): update babel to version 7.2.2

---

package-lock.json
package.json

chore(package): update rollup to version 1.0.1

---

docs/guides/options.md
package-lock.json
package.json
rollup.config.js
sandbox/hotkeys.html.example
src/js/big-play-button.js
src/js/button.js
src/js/clickable-component.js
src/js/close-button.js
src/js/component.js
src/js/control-bar/progress-control/seek-bar.js
src/js/menu/menu-button.js
src/js/menu/menu-item.js
src/js/menu/menu-keys.js
src/js/menu/menu.js
src/js/modal-dialog.js
src/js/player.js
src/js/poster-image.js
src/js/slider/slider.js
src/js/utils/events.js

This PR does two things; it extends the keyboard handling for the seek bar to support a lot more keys (similar to YouTube), and then it passes all unused key presses from UI components to the player, <del>so that a subsequent PR (or plugin) can perform</del> to support player-wide keyboard shortcuts "m" (mute toggle), "f" (full-screen toggle), and "k" (play/pause toggle).

Extend SeekBar keyboard handling, and support hotkeys "m", "f", "k" and Space

---

src/css/_private-variables.scss
src/css/components/_big-play.scss

fix: big-play-button icon position

---

package-lock.json
package.json

chore(package): update patch-package to version 6.0.2

---

docs/guides/audio-tracks.md

Correct typo

---

lang/oc.json

Translation of new strings + 1 correction.
Thanks @gkatsev for the help with the 2 lines about the live!

[i18n]Update Occitan language

---

src/js/menu/menu.js
src/js/player.js
src/js/tech/tech.js
src/js/tracks/html-track-element-list.js
src/js/tracks/text-track.js

More memory leaks in DomData.elData uncovered by looking at our unit tests. I separated the code changes here from the test changes which I will open in another pull request.

fix: more memory leaks

---

index.html
sandbox/hls.html.example

chore: Add a sandbox for HLS

---

docs/guides/live.md

Was looking up the new live stuff, found some minor corrections.

docs(live): minor spelling/grammar corrections

---

package-lock.json
package.json

 fix(package): update @videojs/http-streaming to version 1.10.1

---

package-lock.json
package.json
test/unit/player.test.js

chore(test): upgrade to latest sinon

---

index.html
sandbox/autoplay-tests.html.example
src/js/player.js

Currently our `manualAutoplay` functionality fails quite often in IE 11, I added a test page to prove it and a fix.

chore: Add a sandbox page for testing autoplay values.

---

package-lock.json
package.json

chore(package): update rollup to version 1.15.1

---

docs/translations-needed.md
lang/de.json

Adds missing German translations, and updates translations-needed.

fix(lang): Update German translations

---

package-lock.json
package.json
src/js/player.js
src/js/tech/html5.js
src/js/utils/dom.js

fix: remote deprecated tsml dependency

---

package-lock.json
package.json
rollup.config.js
src/js/error-display.js
src/js/tech/html5.js
src/js/tracks/track-types.js
src/js/utils/define-lazy-property.js
src/js/utils/dom.js
src/js/utils/events.js
src/js/video.js

perf: Another 5ms of startup time improvements 

---

package-lock.json
package.json

fix(package): update videojs-vtt.js to version 0.15.2

---

src/js/tech/html5.js

This reverts commit c791cd8c4ea7675688882d39d745096f817e1395.
Fixes #6330

revert: Revert "fix(iOS): pause player on suspend or stalled if extra buffer is available (#6199)"

---

package-lock.json
package.json

fix(package): update @videojs/http-streaming to version 1.12.1

---

docs/guides/angular.md

Instructions for Angular integration.
add guides/angular.md

docs: add an example Angular integration.md

---

docs/guides/faq.md

docs(faq): update FAQ about HLS and DASH with VHS

---

src/js/player.js
src/js/tech/html5.js
test/unit/player.test.js
test/unit/tech/html5.test.js
test/unit/tech/tech-faker.js

This can be tested on Safari with a HLS playlist containing iframes, for example https://devstreaming-cdn.apple.com/videos/streaming/examples/bipbop_adv_example_hevc/master.m3u8

feat: support fastSeek during scrubbing if available

---

src/css/components/_layout.scss
src/js/player.js
src/js/tech/html5.js

Backport #6673 against 7.8.x release line.
Fixes #6640

fix(fs): don't set player element css props on native fullscreen

---

test/unit/player.test.js

test: skip requestPictureInPicture test if API isn't available

---

src/js/tech/html5.js
test/unit/tech/html5.test.js

fix: limit fastSeek to Safari based browsers only

---

docs/translations-needed.md
lang/de.json

Adds PIP strings for German and updates translations needed.

fix(lang): Add PIP strings to German translations

---

src/js/tech/html5.js
src/js/tech/tech.js

I'll be working on getting a test for this and Html5/Tech sync in a separate PR.

fix(tech): add abstract setScrubbing in tech.js

---

package-lock.json
package.json

Fixes https://github.com/videojs/video.js/issues/6812

chore(package): Update @videojs/http-streaming to 1.13.4

---

package-lock.json
package.json

This fixes an issue where subtitles were getting disabled when where
in-manifest.
Also, fixes vhs-util versions.
Fixes #6909

fix(package): update to VHS 2.2.4

---

docs/guides/faq.md
package-lock.json
package.json

docs(faq): fixup autoplay blogpost url

---

src/js/mixins/evented.js
test/unit/mixins/evented.test.js

Our current error messages and validation are not enough as some errors can still seek through. I improved our error handling and reporting in many places and will make code comments to show why a change was made below. Originally this was a part of #6967

fix: better evented validation and error messages

---

src/css/components/_control.scss

Fully solves issue https://github.com/videojs/video.js/issues/6989 - also in the case described in the comment by @gkatsev: https://github.com/videojs/video.js/pull/7088#pullrequestreview-590718642
Fixes #6989

fix: add display block to all buttons icon placeholder

---

docs/guides/player-workflows.md

docs: update note about accessing tech

---

package-lock.json
package.json

fix(package): remove remove

---

package-lock.json
package.json

See https://github.com/videojs/vtt.js/pull/56

fix(package): update vtt.js to allow server-side-rendering

---

src/js/control-bar/play-toggle.js

fix: silence play promise in the play toggle.

---

package-lock.json
package.json

fix: update to VHS 2.8.2

---

src/js/component.js

Noticed the comments for the this.ready call was not consistent with other commenting pattern.
Also sentance was incomplete, so added the word "go" so that it would make sense.
Also this is my first ever PR!! Hope I did it correctly :)
- [x ] Docs/guides updated

updated comment to be more thourough and consistent

---

package-lock.json
package.json

fix(package): update to VHS 2.9.1

---

lang/es.json

Completing progress line in Spanish
Completing progress line in Spanish

update text of progress bar timing

---

.github/workflows/ci.yml

Remove our custom cache and use the new one from `setup-node`

chore: use setup-node cache and remove individual cache step

---

docs/guides/react.md

The current React example for Video JS only describes a class component.
I added a working example of a React functional component with a fix for the dispose() method removing the elements from the DOM. 
Added an example and implementation example for a React functional component (React v16.8+).
Added to the top: 
```jsx
import React from "react";
import videojs from "video.js";
import "video.js/dist/video-js.css";
export const VideoJS = ( props ) => {
const videoRef = React.useRef(null);
const { options } = props;
// This seperate functional component fixes the removal of the videoelement 
// from the DOM when calling the dispose() method on a player
const VideoHtml = ( props ) => (
<div data-vjs-player>
<video ref={videoRef} className="video-js vjs-big-play-centered" />
</div>
); …
```

Added a functional React component example in react.md docs

---

package-lock.json
package.json

fix: update VHS to fix xmldom warning

---

package-lock.json
package.json

Update VHS to fix seeking into a gap.

fix(package): update to VHS 2.10.3

---

package-lock.json
package.json
rollup.config.js

built off of the work in https://github.com/videojs/videojs-generate-rollup-config/pull/40

fix: mark global/window/document as external globals

---

docs/guides/components.md

- fix spell error for guides doc

fix spell error

---

src/js/tracks/html-track-element.js

refactor: fix typo in html-track-element.js

---

docs/guides/react.md

Improve documentation on functional components to clean up reference if the component is unmounted.
#7361 

Fix clear up reference if component is unmounted

---

src/js/player.js

- fix a comment of the player's event

fix a comment of the player's event

---

test/unit/player.test.js

Quick fix for failing tests on #main.

fix: async audio only tests

---

package-lock.json
package.json

Update to the latest version of @videojs/http-streaming, 2.14.0.

chore(package): update to @videojs/http-streaming@2.14.0

---

docs/legacy-docs/guides/components.html

docs: fix typo in components.html

---

README.md

Updating docs with  number of websites using video.js player

docs(readme): updating the number of websites

---

src/js/player.js

refactor: fix typo in player.js

---

src/js/player.js
test/unit/sourceset.test.js

Can still be disabled with `enableSourceset: false`

feat: Enable sourceset by default

---

docs/_redirects

chore: update FAQ redirect

---

docs/guides/faq.md

Update FAQ.md to match the change in #7892

chore: update FAQ.md to match the change in #7892

---

package-lock.json
package.json

Updates Video.js to the newly released VHS 3.0.

chore(package): update to @videojs/http-streaming 3.0.0

---

package-lock.json
package.json

update @videojs/http-streaming 2.16.0

chore(package): update to @videojs/http-streaming 2.16.0

---

.github/workflows/ci.yml

Updates the codecov uploader action from sunset v1 to v3. SInce we're using only basic options there are no breaking changes.
https://github.com/codecov/codecov-action

chore: Update codecov action

---

package-lock.json
package.json

update @videojs/http-streaming from 3.0.0 to 3.0.2

chore(package): update to @videojs/http-streaming 3.0.2

---

package-lock.json
package.json

update @videojs/http-streaming from 2.16.0 to 2.16.2

chore(package): update to @videojs/http-streaming 2.16.2

---

.github/workflows/release.yml

change publish tag to next-7 for 7x

fix: use next-7 instead of next for 7x during npm publish

---

package-lock.json

package-lock.json was in a bad state, so this should address that.
- Ran `npm install` and `npm audit fix`

chore(package): fix out of sync package-lock.json

---

src/css/_utilities.scss
src/css/components/_button.scss
src/css/components/_loading.scss
src/css/utilities/_linear-gradient.scss
src/js/fullscreen-api.js
src/js/player.js

Removes prefexes that aren't needed for supported versions

chore: remove legacy prefixes

---

package-lock.json
package.json

Update http-streaming.
Update the @videojs/http-streaming dependency to v3.3.1.
https://github.com/videojs/http-streaming/releases/tag/v3.3.1

chore(package): update to @videojs/http-streaming v3.3.1

---

lang/fr.json

Adds French translation for skip buttons.

fix(lang): add skip button text for French

---

lang/es.json

Adds Spanish translation for skip buttons

fix(lang): Add skip button text for Spanish

---

package-lock.json
package.json
src/js/tracks/text-track.js
test/unit/tracks/text-track.test.js

Cherry picked changes from https://github.com/videojs/video.js/pull/8370
Plus updates to package-lock (sha1 -> sha512)

fix: Check for VTTCue (#8370)

---

package-lock.json
package.json

Bump VHS version from 3.3.1 to 3.5.3

chore: bump VHS version from 3.3.1 to 3.5.3

---

.babelrc
.browserslistrc
package-lock.json
package.json
rollup.config.js

Bump VHS version 3.5.3 -> 3.6.0

chore(package): Update VHS version

---

docs/index.md

Documentation update
* Fixed broken links in `docs/index.md`

fix(docs): broken documentation links

---

package-lock.json
package.json

feat: bump VHS 3.8.0

---

package-lock.json
package.json

chore: update vhs to 3.9.1

---

src/js/player.js

Update `playbackRates` function so TS code does not throw error when we do not pass anything into this function.

chore: update playbackRates documentation

---

package-lock.json
package.json

chore(package): update quality-levels version

---

package-lock.json
package.json

fix: update vhs version

---

postcss.config.js

- s/last 3 major version/last 3 major versions/
- sync with current browserslistrc, babelrc, rollup_config

chore(css): fix typo in postcss-config browserslist and update list

---

package-lock.json
package.json

Updates karma dependencies. This includes an update to karma-firebox-launcher via videojs-generate-karma-config, however tests won't run on Firefox without manual intervention as karma-detect-browsers would also need to be updated (with the correct fief executable name) and that doesn't seem likely.

chore: Update karma dependencies

---

docs/translations-needed.md

Added missing Arabic translation, but forgot to remove that from this file, sorry about that :)

chore(docs): Update translations needed

---

package-lock.json
package.json

feat: update xhr

---

package-lock.json
package.json

chore: update VHS version

---

package-lock.json
package.json

feat(package): Update to @videojs/http-streaming v3.17.0
