src/js/player.js

The playbackRate() function does not take a boolean, it takes a (double-precision) number.

playbackRate takes a number

---

lang/pt-BR.json

Legend in pt-BR is wrong.
Progress is not "Progressão" in portugues, the correct word is "Progresso".

Legend in pt-Br is wrong.

---

src/js/lib.js
src/js/media/flash.js
src/js/media/html5.js
test/unit/flash.js
test/unit/lib.js

Added getFileExtension to libs. And used it on Html5 and Flash canHandleSource method to guess the mime type if necessary.

Extended canHandleSource in media files to consistently guess mime types. Fixes #1833

---

CHANGELOG.md
src/css/components/_layout.scss

This doesn't immediately break anything (I know of) because the controls
were originally designed to work in both border-box and content-box
environments. Extra elements were added to create internally padding.
This does open the door for some simplification of the HTML, though the extra
elements could still be useful for extra skin design options.
See #1444

Switched to box-sizing:border-box for all player elements

---

docs/examples/simple-embed/index.html
docs/guides/setup.md

Change the docs to point to the new minified name for video.js. For #1013.

Update minified video.js name

---

src/js/component.js

When we changed to concise methods, we ended up creating a new function
that shadowed the global setInterval, setTimeout, clearInterval, and
clearTimeout methods. A recent change in babel exposed this bug.

We want to call global setInterval not our own

---

bower.json

Per https://github.com/bower/bower.json-spec/pull/43 :
> font files [...] are not `main` files as they are not entry-points.
(See also the new example in the spec)

bower.json: Remove font files from `main`

---

src/js/big-play-button.js
src/js/control-bar/fullscreen-toggle.js
src/js/control-bar/play-toggle.js
src/js/control-bar/playback-rate-menu/playback-rate-menu-item.js
src/js/control-bar/progress-control/seek-bar.js
src/js/control-bar/progress-control/seek-handle.js
src/js/control-bar/spacer-controls/custom-control-spacer.js
src/js/control-bar/text-track-controls/caption-settings-menu-item.js
src/js/control-bar/text-track-controls/captions-button.js
src/js/control-bar/text-track-controls/chapters-button.js
src/js/control-bar/text-track-controls/chapters-track-menu-item.js
src/js/control-bar/text-track-controls/off-text-track-menu-item.js
src/js/control-bar/text-track-controls/subtitles-button.js
src/js/control-bar/text-track-controls/text-track-button.js
src/js/control-bar/text-track-controls/text-track-menu-item.js
src/js/control-bar/volume-control/volume-bar.js
src/js/control-bar/volume-control/volume-handle.js
src/js/control-bar/volume-menu-button.js
src/js/menu/menu-button.js
src/js/menu/menu-item.js
src/js/poster-image.js
src/js/tech/flash.js
test/unit/tech/tech-faker.js

Didn't make the connection that the reason class method inheritance worked was the `__proto__` usage in babel... It breaks in IE8. Reverted those uses.

Fixed all uses of registerComponent that relied on __proto__ inheritance

---

CHANGELOG.md
src/js/component.js
test/globals-shim.js
test/unit/component.test.js
test/unit/tracks/text-track-controls.test.js

Addresses #1667 
I've changed ready() and triggerReady() to always be async. However now a bunch of track tests are falling. 
@gkatsev, can you provide any insight here? I would guess it has to do with the text track display.
https://github.com/videojs/video.js/blob/1ff361a825400a2be803d6d4f0b72e0ecfbc8e6f/src/js/tracks/text-track-display.js#L41
```
Text Track Controls should be displayed when text tracks list is not empty FAILED
control is displayed
textTracks contains one item. Expected: 1 Actual: 0
```
If I move the addRemoteTextTrack part out of the ready listener the tests actually pass, but then other tracks tests fail.
```
Tracks TextTrackDisplay initializes tracks on player ready FAILED
TypeError: Cannot read property 'tracks' of undefined
```

Updated player.ready to always be async

---

CHANGELOG.md
grunt.js
package.json
sandbox/index.html.example
src/js/player.js
src/js/tech/flash.js
src/js/utils/merge-options.js

- Fixed an issue using lodash.isPlainObject on elements in IE8 (reverted to old isPlain)
- Turned on loose mode for Babel and added ES5 shim and sham to the examples
- Fixed the Flash tech's events by creating the object in component.createEl (otherwise a default 'div' was created) 
Fixes #2184
*Might fix* #2185 - I don't know why but I'm not seeing it at the moment
@eXon mind checking out the Flash tech bit?

Fix IE8 issues from 5.0 changes

---

src/css/components/_control-spacer.scss
src/css/video-js.scss

The spacer, as a table-cell, seemed to be defaulting to width: auto

added display: none; to fix the custom spacer in ie8

---

src/js/player.js

IE10 only implements the 2012 version of the Flex spec, which doesn't support `flex-basis`. Because of this, we were left in a weird middle ground where IE10 was getting the `no-flex` class but overriding the no-flex table styles with flex things. Closes #2212.

added IE10 flex support check

---

.travis.yml

libsass may be running into issues with bindings and iojs so use a version-pegged node.js for now.
(Testing to see if this fixed Travis)

Use node.js 0.12 for travis

---

CHANGELOG.md
src/js/button.js
src/js/utils/events.js

fixes #2414 
Our fixEvent script makes a copy of the original event, but it was failing to also set `cancelBubble = true` and `returnValue = false` on the original event, which is needed to make IE8 work like modern browsers.

Fixed event bubbling in IE8

---

CHANGELOG.md
src/js/player.js

Now that we've cleaned up the relationship between the player and the tech we can clean up how duration works. It was a little complicated.
Fixes #863

Cleaned up durationchange process in the player

---

CHANGELOG.md
src/css/components/_live.scss
src/css/components/_progress.scss
src/css/components/_time.scss
src/js/control-bar/live-display.js
src/js/control-bar/spacer-controls/custom-control-spacer.js

...and also the layout in IE8 when live. Both are currently broken in the new skin.
Related to #2507

Fixed displaying the LIVE control bar item

---

CHANGELOG.md
src/js/player.js

Want to get this out before 5.0. Reasoning from #1676. 
> I think we need to deprecate the loadedalldata event for 5.0. It's a made up event (not from the video element) that has less use these days for a few reasons:
- For most cases, you should use the canplaythrough event instead of loadedalldata.
- Browsers manage their buffer more carefully now, they don't just load the whole video at once
- It doesn't apply to live events

Removed the loadedalldata event

---

CHANGELOG.md
src/js/player.js
src/js/tech/html5.js
src/js/tech/tech.js
test/unit/tech/html5.test.js

fixes #2588 @pat can you confirm?
Took me a day and half to fully wrap my brain around this. The code comments give some insight into the complexity.
With these changes you can now init a player on a video element of any loading state and the player will emit all the loading events, from loadstart to canplaythrough, to catch up to the current state.

Fix the double loadstart event and fix it good

---

src/css/video-js.less

Just found a minor issue that is when you have a cover art image that doesn't fit the player and it is scaled down, the player element is visible outside the scaled image.
This tweak sets the background-color property which means the player will always be completely covered if the poster does not fit exactly, or if the poster image cannot be loaded for some reason/whilst it's loading.
Here is what happens currently:
And here is what it looks like with the background-color property applied:

Added background-color to vjs-poster to remove transparent borders around scaled poster image

---

test/unit/player.test.js

Fix the tests on ie8. We need a new tag for IE8 and not reuse it when we create a new player.

use a brand new tag el for ie8

---

.travis.yml
test/karma.conf.js

This is because travis is failing to install the correct version of dependencies. We can re-add chrome back in at a later date.

revert 75116d4 adding chrome to travis

---

test/unit/plugins.test.js
test/unit/poster.test.js
test/unit/setup.test.js
test/unit/test-helpers.js
test/unit/video.test.js

lint the bottom half of the files in the test/unit directory with `videojs-standard`

vjsstandard - Tests - Bottom half of test/unit

---

test/unit/utils/dom.test.js
test/unit/utils/fn.test.js
test/unit/utils/format-time.test.js
test/unit/utils/log.test.js
test/unit/utils/merge-options.test.js
test/unit/utils/time-ranges.test.js
test/unit/utils/to-title-case.test.js
test/unit/utils/url.test.js

lint all of the tests in the test/unit/utils folder

vjsstandard - Tests - Utils folder

---

test/unit/button.test.js
test/unit/clickable-component.test.js
test/unit/close-button.test.js
test/unit/component.test.js
test/unit/controls.test.js
test/unit/events.test.js
test/unit/extend.test.js
test/unit/menu.test.js
test/unit/modal-dialog.test.js
test/unit/player.test.js

Files updated for videojs-standard v5:
button.test.js
clickable-component.test.js
close-button.test.js
component.test.js
controls.test.js
events.test.js
extend.test.js
menu.test.js
modal-dialog.test.js
player.test.js

Unit test linting

---

test/unit/tracks/text-track-list-converter.test.js

lint text-track-list-converter.test.js which was missed in the first linting pass

vjsstandard - Tests - one missed file

---

CHANGELOG.md
src/js/utils/events.js
test/unit/events.test.js

In the event dispatch function, we do not guard against event handlers raising exceptions. If that happens, any further processing of event handlers and *any code after the trigger* stops as the exception continues to unwind the stack.
This is particularly problematic if the event was triggered by a source handler during the initialization stages of the handler. The SourceHandler can end up in a state from which it can not recover through no fault of our own. 
See this example of a player broken by a simple exception thrown from an event handler:
http://jsbin.com/fipikerore/edit?html,output
Simply add a try/catch around each invocation of an event handler function called from the the `dispatch` function.

Exceptions in event handlers breaks further processing of event handlers

---

package.json

Updates `object.assign` to the latest, and uses a semver range so that consumers can `npm dedupe`.
All deps should always use semver ranges - if a dep isn't using semver, *nobody should be using the dep* - and I'm the maintainer of `object.assign`, so I can guarantee you there will never be a breaking change without a semver-major bump.

[Deps] update `object.assign`

---

build/grunt.js
package.json

Add bundle-collapser to browserify plugins to save us a lot of bytes!

add the bundle-collapser browserify plugin to save 16kb minified (5.5%)

---

src/js/control-bar/progress-control/load-progress-bar.js

The load progress bar never highlights the **first** buffered time range.
This page demonstrates the problem using a fake tech which always has `buffered` set to `[[0,2],[4,8]]`: http://jsbin.com/cakece/edit?html,output
The load progress bar should show 2 highlighted parts.
The load progress bar only shows 1 highlighted part, namely the `[4,8]` range.
Additionally, when inspecting the DOM, you can see that the `<span class="vjs-control-text">` inside the `<div class="vjs-load-progress">` gets resized.
The issue appears to be in [`LoadProgressBar.update`](https://github.com/videojs/video.js/blob/3a859f97d0647fc3d1ef6b2f4b755c71da8bef63/src/js/control-bar/progress-control/load-progress-bar.js#L40). This method keeps `this.el_.children` in sync with `this.player_.buffered()` by …

Fix load progress bar never highlighting first buffered time range

---

.babelrc
package.json

Followup from #3609. es2015-loose is deprecated because it's available as an option on the es2015 preset.

remove es2015-loose since it's an option for es2015

---

src/js/tech/html5.js

* Refactor any redundant code in the html5 tech to save bytes
* saved 254 bytes in the gzipped bundle, or 0.4% savings
* List native properties wrappers at the top and loop through and add them in the constructor
* Better video/audio track code

refactor redundant code in html5 tech

---

src/js/tech/html5.js

Previously, the ios webkit events (webkitbeginfullscreen and
webkitendfullscreen) were only proxied into the fullscreenchange event
when requestFullscreen was called directly. So, on iPhones, we would
never be able to get this event. This makes it so these events are
always proxied.

Proxy ios webkit events into fullscreenchange

---

src/js/tech/html5.js

Due to `timeupdate` events being fired before `canplay` is triggered, the spinner is hidden before the video is actually loaded. See https://github.com/videojs/video.js/issues/3653
Disabling manual `timeupdate` events for the Html5 tech prevents this from happening and only fires `timeupdate` events after `canplay`.
Add `Html5.prototype.featuresTimeupdateEvents = true` to the Html5 tech to disable manual `timeupdate` events.

Set timeupdate feature of html5 tech to disable manual timeupdate events

---

CHANGELOG.md
src/js/control-bar/time-controls/duration-display.js

This addresses a possible source of breakage introduced in #3349 where dependent applications could be using the removed events to manually force a duration display update.

Restore timeupdate/loadedmetadata listeners for duration display

---

src/js/utils/log.js

This fixes the potential for a completely broken player under the following conditions:
- IE < 10
- `console` is closed, so undefined
- Call `videojs.log` or one of its methods
No longer attempts to `apply(console, args)` because `console` is no longer defined as a local variable after e85c1c039153f4d031b602fa8dc6d4aa2130427f so the browser looks up the scope until it reaches the global scope and, in IE9, because there is no console unless it's open... throws a "console is undefined" error.

Apply window.console instead of console, which is no longer defined

---

docs/guides/options.md

A possessive belonging to an "it" doesn't need an apostrophe. Don't believe me? Ask [the Oatmeal](http://theoatmeal.com/comics/apostrophe) (look for the velociraptor)!
Replace incorrect "it's" with correct "its"

Remove Bad Apostrophe

---

src/js/tech/html5.js

`Tech.withSourceHandlers(Html5);` expects the prototype getter/setters to exist. Moving these functions after the getters/setters allows them to function properly

Move SourceHandler pattern functions after prototype getter/setters

---

CHANGELOG.md
build/grunt.js

Source Maps, while nice, aren't perfect and the ones we were outputting
weren't right.
Fixes #3701, #3106.

fix: remove sourcemaps from the output

---

src/js/video.js

If you try and require videojs in an environment that doesn't implement `document.createElement` properly -- like in Node.js -- you could potentially get an error. This checks that `window.document && window.document.createElement` is available before calling `createElement`.
We specifically check `window.document` so that `global` module won't cause issues with it's shimming of `document.createElement` in `global/document.
Fixes #3665

fix: make sure that document.createElement exists before using

---

CHANGELOG.md

5.12.6's changelog accidentally included all the 5.12.x changes and the
link to the comparison was from 5.10.7 to 5.12.6.
The comparison link in 5.12.3 was also updated to properly refer to
5.12.2 as the previous change.

chore(changelog.md): update 5.12.6 and 5.12.3

---

src/js/player.js
test/unit/player.test.js

If a player is fluid and does not have a width set, and preload is set to none, the height of the player is zero. This includes where preload is forced to none by mobile Chrome as in #3606.
- If the player has the `.vjs-fluid` class when initialised, `fluid` is set to `true`, so adding the class behaves the same as `{fluid: true}` in the setup options.
- The `fluid(bool)` setter calls `player.updateStyleEl_()`. Otherwise it won't be triggered in `createEl()` if an aspect ratio is not also set.
- Corrects the test for a set `videoWidth()` in `updateStyleEl_()` - `videoWidth()` returns `0` if the width is unknown. This allows the default `16:9` to kick in rather than using `0:0`.

Use default aspect ratio for fluid players if width unknown

---

src/js/tech/html5.js
test/unit/player.test.js
test/unit/tech/html5.test.js

Re issue #3079 and the discussion in #3083. Android Chrome returns `Infinity` for VOD HLS until after playback has started. This causes issues such as an unwanted flash of the live display control.
HTML5 tech will return `NaN` instead of `Infinity` if playback has not started. Fires a `durationupdate` event once the reported duration can be believed if the duration is still `Infinity`, so controls can update.

Suppress Infinity duration on Android Chrome before playback

---

src/js/button.js
src/js/clickable-component.js
test/unit/clickable-component.test.js

`enable()` and `disable()` on clickable components is only cosmetic. "Disabled" implies the control should not be functional.
- Remove event listeners on `disable()` and add back on `enable()`.
- Move adding listeners from constructor to `enable`
- Remove `tabindex` from disabled components and add `disabled` attribute to disabled buttons to prevent keyboard access.

Disable interaction with disabled clickable components

---

src/js/control-bar/progress-control/mouse-time-display.js
src/js/control-bar/progress-control/seek-bar.js
src/js/utils/computed-style.js
src/js/utils/get-computed-style.js
src/js/video.js

This is used internally in the seek bar and mouse time display.
In firefox, in an iframe that is hidden with "display: none",
getComputedStyle() returns "null" which can break things.
See https://bugzilla.mozilla.org/show_bug.cgi?id=548397 for more
details.
- add a `getComputedStyle` util
- expose `videojs.getComputedStyle`
- use the util in mouse time display and seek bar

feat: add a safe getComputedStyle to videojs.

---

test/unit/player.test.js

IE8 returns a rounded value for the fluid height / width test, 0.563 rather than 0.5625.
Test for a value between 0.562 and 0.563 instead of exactly 0.5625

fix: allow rounded value for fluid player ratio test

---

src/js/component.js

This is because IE returns 0 for both getComputedStyle and currentStyle.
However, offsetHeight and offsetWidth do contain the correct values we
want. So, if before returning in currentDimension the return value is
still zero, check the offset values.

fix: currentDimension can return 0 for fluid player on IE

---

src/js/tech/tech.js

Param doc update
Update the param doc for registerSourceHandler

Change registerSourceHandler param doc from first to index

---

src/js/big-play-button.js
src/js/button.js
src/js/clickable-component.js

- Removes un-needed constructor overrides from `button` and `big-play-button`
- Removes un-needed `addChild` override from `clickable-component`
- Created an [issue](https://github.com/videojs/video.js/issues/3720) for the TODO comment that was removed

remove un-needed contructor and function overrides

---

src/js/utils/merge-options.js

The current implementation causes the `mergeOptions` function to be de-optimized. This change improves readability by switching to ES6 syntax _and_ it results in a roughly 75% improvement in the performance of this function by transpiling to a `for` loop instead of `slice.call`.

Use ES6 and allow V8 to optimize mergeOptions

---

docs/guides/hooks.md
src/js/video.js
test/unit/video.test.js

There is no current way to hook into the setup that video.js does, and this functionality would be useful for many plugins to use. (they can even initialize themselves with it)
- Add several "hook" functions to the videojs object
- Add pre/post setup lifecycle event triggers

implement lifecycle hooks and trigger pre/post setup hooks

---

src/js/video.js
test/unit/video.test.js

Fix a unit test in ie8 that is currently broken

fix hooks unit test in ie8

---

src/js/tech/flash-cache.js
src/js/tech/flash.js
test/unit/tech/flash-cache.test.js
test/unit/tech/flash.test.js

Calling into the SWF too often is expensive. Current time and buffered don't actually change that often but it's very common to call them a couple times in the handling of a single event. Cache their return values for 100ms so the performance penalty of going through ExternalInterface is limited.
Cache return values from `currentTime` and `buffered` for 100ms in the Flash tech.

Cache currentTime and buffered from Flash

---

package.json

Until https://github.com/litixsoft/karma-detect-browsers/issues/17 is fixed, we need to pin it so our builds pass and tests can work locally.

chore: pin karma-detect-browsers to 2.1.0

---

test/unit/utils/dom.test.js

Safari 10 automatically dedupes duplicate class names in an element. So,
our test was failing because we had an extra "foo" in the check. This is
an unlikely scenario that has browser variations, so, better to just
remove it.

test(dom): fix removeElClass test in Safari 10.

---

src/js/player.js
src/js/tech/html5.js
src/js/tech/tech.js
test/unit/tech/tech.test.js
test/unit/tracks/text-tracks.test.js

Right now "remoteTextTracks" persist between source changes and must be removed manually by the user. This is problematic in many cases. It means plugins that change sources, such as the playlist API or videojs-contrib-ads, have to be extremely careful about changes the source and take care to cleanup remoteTextTracks. 
We do this because the Video.js API aligns very closely with the media element's native API. I propose that we could be doing more to iron-out the rough patches in the native API. In my opinion, the fact that previous changes to the media-element (adding text track elements) may change the behavior of a source is one of those rough patches.
`Tech#addRemoteTextTrack` now accepts a second parameter - a boolean named `manualCleanup` which defaults to true preserving backwards …

Add option to have remoteTextTracks automatically 'garbage-collected' when sources change

---

src/js/tech/html5.js

addRemoteTextTrack and removeRemoteTextTrack in Html5 tech assumed that
they are always called for native text tracks. However, Html5 tech can
have emulated text tracks. For those, we just exit early after the super
methods are called.

fix(html5): exit early on emulated tracks in html5

---

src/js/tracks/html-track-element-list.js

When accessing a HtmlTrackElementList, you cannot access them using indices like with [TrackList](https://github.com/videojs/video.js/blob/master/src/js/tracks/track-list.js).
Previously trying to access a remoteTextTrack by `player.remoteTextTrackEls()[0]`, resulted in an error `this.player.remoteTextTrackEls(...)[0] is undefined`.
I have added code similar to that in TrackList to allow accessing html track elements.

Include method to get html track elements from the list

---

src/js/component.js
src/js/video.js
test/unit/player.test.js

Allow to use custom player class
This change will allow to use custom player class. In version 4 new player instance was created from `vjs.Player` https://github.com/videojs/video.js/blob/release/4.2.0/src/js/core.js#L52 so it was possible to override Player witch custom class. Right now it's not possible since player is created directly from `Player` import. Using `Component.getComponent('Player')` will alllow to use custom player class that can be registered via `Component.registerComponent` same as current player is registered right now https://github.com/videojs/video.js/blob/master/src/js/player.js#L2979

Allow to use custom Player class

---

src/js/tech/html5.js

This has no functional change. This simply makes the code easier to understand.
Don't reference `player_` inside of a tech since it isn't actually a reference to the Player.
These references to player_ are actually not the player due to techs not having a reference to the player.

Remove confusing references to player in HTML5 tech.

---

src/js/tech/tech.js
test/unit/tech/html5.test.js

This PR provides a tech level option to disable native audio and video tracks.
This adds `nativeAudioTracks` and `nativeVideoTracks` tech options, this will disable hooking into the native track APIs. This would be useful when using videojs-contrib-hls on Edge.
Usage:
```js
videojs(video, {
html5: {
nativeAudioTracks: false
}
});
```

Added option to disable native tracks

---

.jsdoc.json
package.json
src/js/big-play-button.js
src/js/button.js
src/js/clickable-component.js
src/js/close-button.js
src/js/component.js
src/js/error-display.js
src/js/event-target.js

- Add `@return` and description where missing from functions
- Add `@param` and description where missing
- Remove un-necessary doc comments such as `@class` and `@method`
- Update examples to match current code standards
- Update descriptions to make more sense across the board
- Keep all doc comments in a standard format
- Verify that documentation looked good after running jsdoc
- document `@events` and `@fires`
- Depends upon #3721

Update the jsdoc comments to modern syntax - Part 1

---

src/js/fullscreen-api.js
src/js/loading-spinner.js
src/js/media-error.js
src/js/menu/menu-button.js
src/js/menu/menu-item.js
src/js/menu/menu.js
src/js/modal-dialog.js
src/js/plugins.js
src/js/popup/popup-button.js
src/js/popup/popup.js

- Add `@return` and description where missing from functions
- Add `@param` and description where missing
- Remove un-necessary doc comments such as `@class` and `@method`
- Update examples to match current code standards
- Update descriptions to make more sense across the board
- Keep all doc comments in a standard format
- Verify that documentation looked good after running jsdoc
- document `@events` and `@fires`
- src/js/extend.js
- src/js/fullscreen-api.js
- src/js/loading-spinner.js
- src/js/media-error.js
- src/js/menu/menu-button.js
- src/js/menu/menu-item.js
- src/js/menu/menu.js
- src/js/modal-dialog.js
- src/js/plugins.js
- src/js/popup/popup-button.js
- src/js/popup/popup.js

Update the jsdoc comments to modern syntax - Part 2

---

docs/guides/faq.md

added an faq

---

docs/guides/troubleshooting.md

Added a troubleshooting guide

---

package.json
src/js/button.js
src/js/clickable-component.js
src/js/extend.js
src/js/media-error.js
src/js/menu/menu-item.js
src/js/player.js
src/js/slider/slider.js
src/js/tech/flash.js
src/js/tech/html5.js
src/js/utils/dom.js
src/js/utils/log.js
src/js/utils/merge-options.js
src/js/utils/obj.js
src/js/video.js
test/unit/utils/obj.test.js

This pulls in a few updates I made to `utils/obj` from #3690 so they can be more isolated and make it into 5.x. 
Perhaps more impactful, this removes `object.assign` as a dependency and re-implements the functionality we were depending on. _This change reduces the minified size of Video.js by over 2KB off the gzipped size._
- Introduce the `isObject` method: essentially, `typeof x === 'object'` with a null check.
- Introduce the `isPlain` method: taken from `mergeOptions`, this does a reasonable job at identifying plain objects.
- Remove `object.assign`.

Object Type-Detection and Replacing object.assign

---

build/grunt.js
build/options-customizer.js
package.json
src/js/control-bar/progress-control/mouse-time-display.js
src/js/utils/fn.js
src/js/utils/merge-options.js
src/js/video.js

This removes lodash-compat as a dependency (though, lodash is preserved as a dev dep). _This reduces the minified+gzipped size of Video.js by 4KB._
- Remove lodash-compat as a dependency.
- Add lodash as a dev dependency.
- Reimplement a pared down throttle function in our `fn` utility.
- Reimplement `_.merge` behavior in `mergeOptions`.

Remove lodash

---

src/js/component.js
src/js/utils/events.js

When using the `Component#on` function, events added to the `window` object (like a `resize` event) the event handler is silently ignored.
This is caused because the current code uses the presence of a `nodeName` property to determine if the target is a DOM node. For the most part this is a good test, but it doesn't work for the `window` object.
This updates the logic for adding event listeners to check if the target is the window object, in addition to the current `nodeName` property check.
This change also adds a final `else` to this if statement that logs a warning so that developers are aware that their event is not being added.

fix(events): support adding events to the window object

---

src/js/tech/html5.js
src/js/utils/browser.js
test/unit/tracks/text-tracks.test.js

Chrome has a bug where if you add a remote text track and try to use it programmatically, you won't get any cues displayed. So, just switch to always emulated mode.
Also, add `IS_SAFARI` and `IS_ANY_SAFARI` to the browsers.

feat(texttracks): always use emulated text tracks

---

src/js/utils/fn.js
test/unit/utils/fn.test.js

This fixes a breakage in 5.14.0 of the MouseTimeDisplay UI that was caused by my work in 761b877626e9f056464f3ef12923d0bb768c276b
- Make the `Fn.throttle` function actually work.
- Add a test to verify and verify manually (which I did).

Fix error in Fn.throttle that broke MouseTimeDisplay

---

build/grunt.js
test/karma.conf.js

Add Edge as a browser to run tests on in browserstack.

tests: add Edge to browserstack tests

---

test/unit/events.test.js

The error that is logged in this test makes it hard to see what is an actual error in some cases.

tests(events): silence error logging in tests

---

src/js/player.js

If you're in a seeking state and the source changed, we should no longer
be in a seeking state.
Fixes #3765.

fix: remove vjs-seeking on src change

---

test/unit/plugins.test.js

We were accidentally stubbing console.log forever in our tests.
Move the storing of the default `window.console` to before we stub it out.

test: stub/restore window.console properly

---

src/js/tech/html5.js

`unpatchCanPlayType` and `patchCanPlayType` were causing issues, particularly in tests because they could end up setting the `canPlayType` method to `null` if called in the right order. This fixes it so that unpatching will always restore the native `canPlayType` method.

fix(html5): (un)patchCanPlayType could set native canPlayType to null

---

src/js/video.js
test/unit/videojs-hooks.test.js

Depends on https://github.com/videojs/video.js/pull/3861 and https://github.com/videojs/video.js/pull/3862

test(hooks): remove errors logged in tests

---

src/js/tracks/text-track-display.js
test/unit/tech/tech.test.js
test/unit/tracks/text-track-controls.test.js
test/unit/tracks/text-tracks.test.js

Tests were printing out a lot of deprecation warnings when using remote text tracks. Also, our own text track display was printing them out itself. This silences them and adds a test for the warning.
The first commit of this PR will be rebased out https://github.com/videojs/video.js/pull/3861 is merged.

fix: remote text track deprecation warnings

---

src/js/player.js
src/js/tech/html5.js
test/unit/player.test.js
test/unit/video.test.js

If the videojs embed code (a video element) is wrapped in a div with the
'data-vjs-player' attribute on it, that element will be used for the
player div and a new one will not be created. In addition, on browsers
like iOS that don't support moving the media element inside the DOM, we
will not need to clone the element and we could continue to re-use the
same video element give to us in the embed code.
This could also be extended in the future to change our embed code to a
div-only approach if we so choose.

feat(player): ingest a player div for videojs

---

src/js/player.js

Deprecate the use of `starttime` in player.js. It seems like the `startTime` option is actually used in flash so for the time being that will have to stay. Fixes #3781

Deprecate the use of `starttime` in player.js

---

src/js/control-bar/progress-control/seek-bar.js

In chrome 55, something changed which introduced a bug in videojs where
if you seeked back, it wouldn't work. This is because we always paused
the video in the mousedown handler.
Instead, we should create a timer for pausing that is cleared in the
mouseup handler or in the mouse move handler. This is so that if someone
is seeking by clicking and waiting the video pauses. As soon as we start
moving and we get a mousemove event, we can know that it's safe to pause
as well.
Fixes #3839.

fix(seeking): don't always pause in mouse down

---

src/js/tech/tech.js

Skipping browser bugfix for changing cursor as that stops tap events
from propagating to native controls. Also enabled option that disables
converting events to 'tap'. The 'tap' event does not cause native
controls to appear on devices like android.
When using nativeControlsForTouch - taps appear to be stalled and don't go through to the native video element, therefore the controls never appear again when tapping as would be expected.  On Android you have to tap and hold to bring up the controls, which is not as users would typically expect.
Additionally, added option for disableEmitTapEvents which when enabled, doesn't attempt to convert / check taps and allows the browser to natively interpret taps as clicks instead.
Added option disableEmitTapEvents to stop converting taps to manually. …

Correcting NativeControls + Taps.

---

src/js/video.js
test/unit/video.test.js

Extra warnings were being logged when getting a reference to a player via videojs('player_id').

Fix extra warn logs on already initialized player references

---

src/js/setup.js
src/js/tech/html5.js
src/js/utils/browser.js
src/js/utils/dom.js
src/js/video.js

This makes a number of small fixes to support pulling in video.js via `require()` in Node.
I have verified it in the following ways (using Node 4.6):
```sh
node -e "require('./dist/video.js')"
```
```sh
node -e "require('./es5/video.js')"
```
```
node
> require('./dist/video.js')
```
```
node
> require('./es5/video.js')
```
All these were tested because we had noticed some odd behavior when using the inline `-e` command vs. the REPL. Success was considered "didn't throw an error".
> **Note**: It is not expected that _calling_ `videojs()` the function in Node will work. That will throw an error, but loading it as a module should not throw.
Fixes #3869.
- Introduce the `Dom.isReal()` function, which makes an educated assumption about the "realness" of the `document` object.
- Wrap code here …

fix: support require()-ing video.js

---

src/js/tech/html5.js
src/js/utils/dom.js

This prevents test failures (and fixes some issues introduced by the Node support PR) in IE8.

ignore: Prevent test failures in IE8

---

docs/faq.md

@mister-ben would love your input on this as well.

docs(faq): add FAQ question about RTMP url

---

docs/faq.md

A comment question, particularly around mobile devices.

docs(faq): add a question about autoplay

---

build/grunt.js
package.json

npm start now runs `grunt dev` which in turn runs the connect server,
sets up babel watching, browserify watching (for both src and test
files), and css and alternate builds watching.
Additionally, it will copy over the dev build files into the dist folder
so that if you're linking videojs and you have a project that gets
video.js from the dist, you can link and develop with more easy without
rerunning all of `grunt dist` each time.
Additionally, this specifically does not run more time consumming
operations like minification.

chore: better dev experience

---

src/css/components/_big-play.scss

Show big play button if video is paused and
.vjs-show-big-play-button-on-pause is set on video element
If you pause a video-js video, the play button isn't shown like most users expect from UIs like youbtube or iPhone video behavior.
This patch implements a play button after pause if needed via an additional CSS class on the video-js video elemetn.

Show big play button on pause if specified

---

build/docs-only.js
build/grunt.js
package.json

Check to see if we're on travis and if the changes that we're running against only include files in the `docs/` folder or are `.md` files and if so, don't run any tests. Locally, or, if non-doc changes, tests will still run.

chore: don't run tests on travis if only docs were changed

---

docs/troubleshooting.md

- Fixed (and simplified) the codecs header; and while I'm at it:
- Elaborated slightly on codecs and flash in v6
- Changed case of 'Video.js' throughout and some other capilatisation to be consistent with the doc

docs(troubleshooting): Fix a title

---

build/grunt.js

Fix `npm start` file watching
Pass the babel cli a valid command for watch rather than --w.

Fix `npm start` file watching

---

build/grunt.js
package.json
src/js/tech/tech.js

Use require on `videojs-vtt.js` rather than adding on to the end of the bundle after building.
This PR replaces #3794 
* cleanup `build/grunt.js` for browserify
* use `aliasify` to exclude `videojs-vtt.js` for novtt builds
* allow fallback to old script vtt include
* fix a bug where `shell:babel` was passing `--w` to babel rather than `-w` or `--watch`

Require `videojs-vtt.js` via require rather than concat

---

src/js/player.js

For elements which parent doesn't have `hasAttribute` it needs do another check to prevent erroring out.
Added a check to ensure the tag's parentNode has the `hasAttribute` function

Add check to ensure `hasAttribute` is a function

---

src/js/control-bar/progress-control/seek-bar.js

I ran into the backwards seeking problem with Chrome 55, as previously reported in #3839. After some investigation, I found it was also reported in the Chromium bug tracker as [bug 675556](https://bugs.chromium.org/p/chromium/issues/detail?id=675556), and it should be fixed in Chrome 57.
I noticed that video.js 5.15.0 fixes this in #3886 by delaying the pause until the first `mousemove` or after 100ms (whichever happens first). However, the comments from the Chromium bug indicate that there is a simpler solution. The problem occurs when you call when you call `video.pause()` immediately after setting `video.currentTime`, however it does not occur when you pause **before** seeking.
This change reverts #3886. Instead, it ensures that `SeekBar.handleMouseDown` first pauses the player before …

Pause player before seeking in seek bar mousedown

---

src/js/tech/tech.js

This helps with debugging to know what a component's name is.
We try to look up the tech's name via the constructor's name property,
otherwise, we set it to 'Unknown Tech'. Can be overridden by setting
`this.name_` after calling `super()` in the constructor.
Fixes #1786.

fix: give techs a name

---

src/css/components/_poster.scss
src/js/poster-image.js

We previously hid the poster image when controls were disabled because
the poster image had a click handler on it. However, this meant that in
the case of Flash, which doesn't have a native poster image ability, we
lost the poster.
Fixes #1625.

fix: showing custom poster with controls disabled

---

src/js/player.js

This is an extremely minor fix to a mistake/type comment on the `currentTime()` method. But I think it's important that it be fixed - I found it confusing.
It's basically a one character change to a comment.
- **N/A** Feature implemented / Bug fixed
- **N/A** If necessary, more likely in a feature request than a bug fix
- **N/A** Change has been verified in an actual browser (Chome, Firefox, IE)
- **N/A** Unit Tests updated or fixed
- **N/A** Example created ([starter template on JSBin](http://jsbin.com/axedog/edit?html,output))

Minor fix to currentTime() comment: "setting" not "getting"

---

src/js/component.js
src/js/extend.js

This removes the `Component.extend()` method entirely, which has been deprecated since 5.0. Additionally, it removes the deprecated support for an `init` method in `videojs.extend()`.

Remove deprecated Component.extend() and init method in videojs.extend()

---

src/js/player.js

There is a default value for a `defaultVolume` option in the `Player`. It's never used; so, might as well remove it.

Remove unused defaultVolume option default

---

src/js/video.js

This is a change for 6.0 - Browserify provides a UMD wrapper for us.

Remove custom UMD

---

src/js/button.js

Remove deprecation for a Button created with a non-button element - throw instead.

Remove deprecation for a Button created with a non-button element

---

src/js/component.js

do not allow adding children with options passed in as a boolean

do not allow adding children with options passed in as a boolean

---

docs/faq.md
docs/guides/debugging.md
src/js/utils/log.js
test/unit/utils/log.test.js

This adds support for log levels to video.js' logger. Log levels act as a whitelist of logger method(s) that are allowed. The following levels are defined here:
* `off`: Matches none. Any value that can be cast to `false` will have this effect. The most restrictive.
* `all` (default): Matches all Video.js-provided functions (`log`, `log.warn`, and `log.error`).
* `warn`: Matches `log.warn` and `log.error` calls.
* `error`: Matches only `log.error` calls.
Also, this improves the `log.history` handling with the ability to `clear()` it as well as toggle it off and on using `disable()` and `enable()`.
- Adds the `log.level()` method which is a getter/setter for log levels.
- Adds the `log.levels` object as a container for the various logging levels.
- **BREAKING CHANGE:** `log.history` is now …

Log Levels

---

src/js/tech/tech.js
test/unit/tech/tech.test.js

Remove all special `loadstart` handling for source handlers.

remove special loadstart handling

---

src/js/component.js
src/js/tech/flash.js
src/js/tech/html5.js
src/js/tech/tech.js
test/unit/component.test.js
test/unit/tracks/text-tracks.test.js

This addresses one of the pre-existing cards from the 6.0 project. It prevents techs (and others) from being registered via `registerComponent`.
There is an open question as to whether or not we want to implement similar protections to `registerTech` and adopt `deregisterComponent` and `deregisterTech` methods similar to the way the plugins PR does for plugins.
- `registerComponent` now throws if given an object that is not a subclass of `Component` (or `Component` itself).
- `registerComponent` now throws if given a non-empty string as its `name` argument.

Make registerComponent only work with Components

---

src/css/_utilities.scss
src/css/components/_big-play.scss
src/css/components/_control.scss
src/css/components/_slider.scss
src/css/components/menu/_menu.scss

This restores outlines for everything for accessibility purposes.
The progress bar looks awkward, but I will be working on that in another PR.

Restore all outlines

---

src/js/player.js
src/js/tech/html5.js
test/unit/player.test.js

Return a Promise from `play()` originally this was a PR off of #3860 (https://github.com/BrandonOCasey/video.js/pull/4). This has been changed to be standalone.

Return the native Promise from play()

---

src/js/player.js
src/js/tech/flash.js
src/js/tech/html5.js
test/unit/tech/html5.test.js

* Implement missing methods on Player, HTML, and Flash
* Remove methods from Flash that are not needed
* Added unit tests for all API only methods

implement missing video methods, *Must* be merged before flash removal

---

docs/guides/modal-dialog.md

This adds a modal dialog guide based on the Brightcove document, provided by @mboles

docs: Add a Modal Dialog guide.

---

docs/guides/faq.md
docs/guides/player-workflows.md
docs/guides/react.md

Just some doc for a clean ReactJS integration
add `guides/react.md `

docs(guides): add basic ReactJS integration example

---

src/js/player.js
src/js/tech/tech.js

Make `registerTech` add that tech to the default `techOrder`

Make `registerTech` add that tech to the default `techOrder`

---

src/js/component.js
src/js/player.js
src/js/slider/slider.js
test/unit/controls.test.js

The PR for advanced plugins introduced the concept of mixins and added two: evented and stateful.
This PR refactors `Component` to use the evented mixin, granting it event broadcast/handling capabilities.
I will open a second PR for implementing stateful components.
- ~~Docs/guides updated~~
- ~~Example created ([starter template on JSBin](http://jsbin.com/axedog/edit?html,output))~~

refactor: Evented Components

---

src/js/component.js
test/unit/component.test.js
test/unit/mixins/stateful.test.js

The PR for advanced plugins introduced the concept of mixins and added two: evented and stateful.
This PR follows #3959 by providing `Component`s with the benefits of the stateful mixin.
- ~~Docs/guides updated~~
- ~~Example created ([starter template on JSBin](http://jsbin.com/axedog/edit?html,output))~~

feat: Stateful Components

---

src/js/player.js

[`techCall_` used to be synchronous](https://github.com/videojs/video.js/blob/stable/src/js/player.js#L1264) and is now async. This causes weird behavior for scenarios like this:
1. player.muted(true);
2. player.muted() === true // this will fail sometimes as setting muted is async
Make `techCall_` async again

make techCall_ sync again

---

src/js/tech/tech.js

#3975 as applied to Video.js 6.

fix: Patch a memory leak caused by un-removed track listener(s).

---

src/css/_utilities.scss
src/css/components/_control.scss
src/css/components/_volume.scss
src/js/control-bar/time-controls/remaining-time-display.js
src/js/control-bar/volume-control/volume-control.js
src/js/control-bar/volume-panel.js

Built from https://github.com/videojs/video.js/pull/3958
Moves as much transition and "logic" into CSS as possible.
Use some javascript to make sure that things are sized properly when tabbing with the keyboard.

move most volume panel functionality into css state

---

src/js/player.js
src/js/tech/middleware.js
src/js/tech/tech.js
test/unit/player.test.js
test/unit/tech/middleware.test.js

As I was playing around with middleware, in the first RC, I realized that the current way of `videojs.use` with an object was lacking. Specifically, if you have multiple players on the page, the middleware would need to be able to handle tech management itself, which doesn't seem right. Also, the mw didn't know about what player it was attached to.
Now, `videojs.use` takes in a function that given a player, returns a middleware object. The middleware object looks the same as the current object we use for registration. This allows us to have per-player instances of middleware and because it's a factory, a user can use a class or Component or Plugin object for managing their middleware if they want, as long as the methods are available.
For example:
```js
videojs.use('video/foo', (player) …
```

Update MW to require a factory, add *-mw

---

src/js/mixins/evented.js

If you try to delegate an to an EventTarget from an evented component, you'll end up failing because it didn't think that an EventTarget object worked. But it should and does. This adds a check for it in the `isEvented` function.

fix: EventTarget is also evented

---

src/js/control-bar/progress-control/time-tooltip.js

If the time tooltips try to update when the player isn't in the DOM,
they error out because the bounding rects for the player will not be available.
This does a null check and exists early.

fix: updating time tooltips when player not in DOM

---

src/css/video-js.scss

node-sass updated to remove the cwd from import paths.
Fix #3998

fix(sass): import path no longer has cwd

---

src/css/components/_volume.scss
src/js/control-bar/volume-control/volume-control.js

This makes it so you don't have to be precise in changing the volume.
One thing I'm not sure is whether I should change the cursor for the entirety of the volume control. I guess I probably should.
I'll be making another PR soon to allow similar functionality on the progress control.

fix: allow changing volume in full height of volume control

---

package.json

Karma 1.4.0 indavertantely broke IE8 when updating socket.io.
This pins karma to 1.3.0 a version that is known to work on IE8.
See https://github.com/karma-runner/karma/issues/2556
See https://github.com/socketio/socket.io-client/issues/1063

chore(package): pin karma to 1.3.0

---

src/js/control-bar/mute-toggle.js
src/js/control-bar/volume-control/volume-bar.js
src/js/player.js
test/unit/controls.test.js

Clicking `MuteToggle` when `volume` is 0 now has more user-friendly behavior. Previously, clicking MuteToggle when `volume` was 0 had no user-visible effect (as discussed in https://github.com/videojs/video.js/issues/3909, which this PR addresses).
There are three possible scenarios I'm aware of for setting the volume to 0 and then dealing with a click on `MuteToggle` that need to be taken into account:
1. **User drags `VolumeBar` to 0 with mouse or finger.** In this case, `volume` should be restored to the level it was at when the user started dragging `VolumeBar`.
1. **User steps `volume` to 0 with keyboard.** In this case, clicking `MuteToggle` should restore the volume to its last value before it reached 0.
1. **`volume` is set directly to 0 with external JS, by a plugin, etc.** In …

Improve mute button usability

---

test/unit/controls.test.js
test/unit/tech/tech-faker.js

IE8 can't run the html5 tech and the mute toggle tests rely on a working
volume and mute functionality which tech faker does not have. Instead of
implementing it in tech faker, skip it on non-html5 environments.

test(ie8): only run mute toggle tests in html5 env

---

CONTRIBUTING.md

Add a few lines to `CONTRIBUTING.md` explaining how to run tests from the browser.

Expand testing info in `CONTRIBUTING.md`

---

src/js/player.js
src/js/tech/tech.js
test/unit/player.test.js
test/unit/tech/tech.test.js

`getTech` now works with `TitleCase` and `camelCase` tech names
Fixes #3986
* update techOptions to look for `TitleCase`/`camelCase` options
* remove all possible `toTitleCase` calls from player.js
* remove deprecated usage of Tech as Component
* add a unit test to verify that registerTech works
* change defaultTech_ to defaultTechOrder_

feat: getTech now accepts `TitleCase` or `camelCase`

---

src/js/clickable-component.js
src/js/menu/menu-item.js

Prevents a title attribute from being applied to `MenuItem`s. Fixes #3699 
MenuItem indicates to ClickableComponent that the control is not just an icon, so it shouldn't have a title attribute.

Disable title attribute on menu items, fixes #3699 (same as #4009, but on master branch)

---

src/js/control-bar/volume-control/volume-bar.js

* Fixes #4021: `aria-valuenow` and `aria-valuetext` not set initially
* Fixes #4022: drop the decimal places on `aria-valuenow` and `aria-valuetext`

fix: accessibility bugs with the VolumeBar

---

src/js/control-bar/progress-control/mouse-time-display.js
src/js/control-bar/progress-control/play-progress-bar.js
src/js/control-bar/progress-control/progress-control.js
src/js/control-bar/progress-control/seek-bar.js

Pretty self-explanatory. These are more trouble than they're worth for a browser we only semi-support.
There are also a few tiny code cleanup pieces in here. Nothing significant.

Disable time tooltips entirely in IE8

---

src/js/big-play-button.js
src/js/component.js
src/js/player.js

If the control bar and playtoggle exist, focus the playtoggle after
triggering play via the keyboard from the Big Play Button.
If `play()` returns a promise, wait until it resolves to focus,
otherwise, use a setTimeout.
Fixes #2729

fix: focus play toggle from Big Play Btn on play

---

src/js/component.js
src/js/player.js
src/js/tech/html5.js
test/unit/player.test.js

The HTML5 tech has a [resize](https://html.spec.whatwg.org/multipage/embedded-content.html#event-media-resize) which fires when the video's intrinsic dimensions change. ~`Player` has a `resize` event when the player dimensions change.~ This can be confusing, and the tech's `resize` is useful.
`Player` had a `resize` event, but currently does not. 
~Trigger a `videoresize` event on `Player` when `Tech` emits `resize`. The existing `Player#resize` does not change.~
Retrigger tech `resize` on `Player`.

Expose Tech#resize as Player#resize

---

src/css/components/_progress.scss
src/js/control-bar/progress-control/mouse-time-display.js
src/js/control-bar/progress-control/play-progress-bar.js
src/js/control-bar/progress-control/progress-control.js
src/js/control-bar/progress-control/seek-bar.js

This fixes #3645.
Also rebased on #4029 so includes those commits.

fix: Progress holder gaps cause tooltips misalignment.

---

src/js/player.js
src/js/utils/filter-source.js
test/unit/utils/filter-source.test.js

* Add a util that filters all possible `Tech~SourceObjects` into a valid `Tech~SourceObject` (see tests) 
* Remove `Player#sourceList_` as it is no longer in use

Filter the source given to `Player#src` before use

---

build/grunt.js

Minor change in the grunt file to remove unnecessary warning messages from the accessibility test
(See above)

Change accessibility test in grunt.js to remove unnecessary warning message

---

src/css/video-js.scss
src/js/clickable-component.js
src/js/menu/menu-item.js

Prevents a title attribute from being applied to `MenuItem`s. Fixes #3699 
MenuItem indicates to ClickableComponent that the control is not just an icon, so it shouldn't have a title attribute.

Remove title attribute on menu items, fixes #3699

---

build/grunt.js

If `lint`ing fails during the `grunt` build process, the console messages only show any warnings that were reported, not the error that caused the failure. That's *really* unhelpful for people who don't know this feature!
Change the lint parameters in build/grunt.js so that only errors are reported. (In the future we can bring back warnings, or provide a different way to build and display warnings.

Only report errors during linting in the build process, not warnings

---

src/js/clickable-component.js
src/js/control-bar/audio-track-controls/audio-track-button.js
src/js/control-bar/control-bar.js
src/js/control-bar/text-track-controls/captions-button.js
src/js/control-bar/text-track-controls/chapters-button.js
src/js/control-bar/text-track-controls/descriptions-button.js
src/js/control-bar/text-track-controls/subtitles-button.js
src/js/menu/menu-button.js
src/js/menu/menu.js
test/unit/menu.test.js

The previous (v5.x) menu structure violated an ARIA requirement, that actionable elements (e.g. the menu button) not have child elements which are also actionable (e.g. the menu items). This PR changes that structure to make "MenuButton" actually a `<div>` containing a `<button>` and a menu. The v5.x structure, and the use of `role="group"` on the Control Bar, were a workaround which made the menus work with most screen readers, but the structure might fail in future screen readers.
This change is very similar to the change to the combined volume from v5 -> v6.
Restructure the HTML elements in a MenuButton & Menu; change the Javascript to handle this. Also, remove unnecessary `aria-label` attribute on the MenuButton, since the actual button used to open the menu is now correctly labeled …

Fix the structure of elements in menus to comply with ARIA requirements

---

src/js/component.js
src/js/modal-dialog.js
test/unit/modal-dialog.test.js

If the modal dialog was opened and the focus was preset inside the
player, move the focus to the modal dialog.
When the modal dialog is closed, move the focus back to the previously
active element.
When focus is inside the dialog, trap tab focus. This was inspired by https://github.com/gdkraus/accessible-modal-dialog and ally.js
Still needs:

feat: modal dialog accessibility updates

---

docs/guides/faq.md

Found a minor spelling mistake in the FAQ guide - 
`offical` > `official`

docs(guides): fix typos in faq guide

---

docs/guides/react.md

I just replace an obsolete typo.
Issue: https://github.com/videojs/video.js/issues/3995
I change in _docs/guides/react.md_, ```autoPlay``` by ```autoplay```
Nothing

Replace 'autoPlay' by 'autoplay'.

---

src/js/player.js
test/unit/player.test.js

If the player language had been set via player options to something other than the document language, the css `:lang()` pseudo-class would match a different language code than `player.language()`. This would be matter for #4028.
Set the `lang` attribute on the player element during initialisation.

Add lang attribute to player el

---

package.json

Fix [#3930](https://github.com/videojs/video.js/issues/3930)
`husky` will automatically migrate hooks installed by `ghooks` so there's no additional action.
* Removes `ghooks` devDependency and configuration.
* Adds `husky` devDependency and adds `prepush` script.

chore: switch from ghooks to husky

---

src/js/control-bar/mute-toggle.js

Because `MuteToggle.controlText` is coordinated only with `muted` and not with `volume`, it doesn't change when `volume` is set to zero:
This fixes by adding a check for `this.player_.volume() === 0` to the predicate of the conditional that sets `toMute`.

Fix `MuteToggle.controlText` when volume set to 0

---

lang/de.json
lang/en.json
lang/tr.json

Solve a typo in translation files
Change "subititles" with "subtitles"
This modification is not included in the PR #4062

Solve a typo in translation files

---

docs/guides/components.md

Updated list.
As an aside, should the loader's `div` have a class so it's obvious what it is when looking at the DOM?

docs: Add MediaLoader to components list

---

src/css/video-js.scss

As described in https://github.com/videojs/video.js/issues/4055, node-sass v4.5.0 has reverted back to allowing `@import "node_modules/videojs-font/scss/icons";`
Reverting back to this format allows for referencing video.js as a dependency in other projects without build failures when importing the sass files from this package. It would be ideal to bring this back into v5.x as well as v6.x of video.js

fix(sass): import path has cwd once again

---

src/js/utils/obj.js
test/unit/utils/merge-options.test.js

Object.keys() will error on IE11 instead of default to an empty array, this will make sure that videojs.mergeOptions() has the same behavior across browsers.
Made a keys() function that defaults to [] when given an non-object.

fix: make mergeOptions behave the same across browsers (5.x)

---

src/js/utils/obj.js
test/unit/utils/merge-options.test.js

`Object.keys()` will error on IE11 instead of default to an empty array, this will make sure that `videojs.mergeOptions()` has the same behavior across browsers.
Made a `keys()` function that defaults to `[]` when given an non-object.

fix: make mergeOptions behave the same across browsers

---

src/js/tech/tech.js

6.x: fix: synchronously shim vtt.js when possible

---

src/js/tech/tech.js

Fix a bug where `vtt.js` would shim `window.WebVTT` way to late in the pipeline.

5.x fix: synchronously shim vtt.js when possible

---

src/js/tech/html5.js
test/unit/tech/html5.test.js

`play()` is defined twice in `Html5`, [here](https://github.com/videojs/video.js/blob/e176b56843b2084c8b0c985d9ea491b5de1da113/src/js/tech/html5.js#L347) and then [here](https://github.com/videojs/video.js/blob/e176b56843b2084c8b0c985d9ea491b5de1da113/src/js/tech/html5.js#L1557).
The promise handling in the earlier one was moved into `Player#play()`
Deleted redundant play() and associated test.

fix: remove redundant Html5#play()

---

src/js/plugin.js
test/unit/plugin-basic.test.js

Copy basic plugin properties to prevent breaking older basic plugins

fix: copy basic plugin properties onto the wrapper

---

docs/guides/components.md
src/js/component.js
src/js/tech/loader.js

`MediaLoader` has a div that's unnecessary. See #4070
- Do not create an element for `MediaLoader`
- Update `Component#dispose()` to check if it has an el before trying to remove it

fix: Do not create element for MediaLoader

---

src/js/control-bar/volume-control/volume-bar.js
test/unit/controls.test.js

Currently, the ARIA value of `VolumeBar` tracks the value of `volume`. It should instead track the position of the slider on `VolumeBar`, which tracks `volume` except when the player is muted, in which case it's 0.
Addresses https://github.com/videojs/video.js/issues/4064.
Clicking `MuteToggle` fires the `volumechange` event on the player, which in turn runs `VolumeBar#updateARIAAttributes`.
However, in the testing environment—at least as I have the tests set up!—clicking `MuteToggle` doesn't fire `volumechange` on the player, so I've had to manually call `VolumeBar#updateARIAAttributes` where it should have been run automatically in order to get the tests to pass. Of course, this needs to be fixed before merging.
Do any problems with my test configuration stick out, or is this likely a …

Muting with `MuteToggle` sets ARIA value of `VolumeBar` to 0

---

src/js/modal-dialog.js

Pretend that the modal dialog is equivalent to the first
focusable/tabbable element when hitting shift-tab.
Fix #4049

fix: trap tab focus in modal when hitting s-tab

---

src/js/menu/menu-button.js

In 5.x this function existed. I think that it was an oversight to remove it so, I have brought it back.

feat: add back MenuButton#controlText

---

src/js/big-play-button.js
src/js/component.js
src/js/player.js

This is a port of https://github.com/videojs/video.js/pull/4018 onto 5.x.
The reason it's a `feat` rather than `fix` is because it adds the `focus()` and `blur()` methods on components.

feat: focus play toggle from Big Play Btn on play

---

sandbox/descriptions.html.example

The sandbox/descriptions.html.example was pulling its video files directly from archive.org; this fixes that to use the same CDN source as the `combined tracks` example (and the Advanced example on the videojs.com site).
Change the URL for the video files (mp4 and ogg).

Use Elephants Dream video files from CDN for the sandbox/descriptions.html.example.

---

src/js/player.js

fix: early play should wait for player ready, even if source is available

---

src/js/plugin.js
test/unit/plugin-static.test.js

Currently, if a plugin is re-registered, it will throw an error. On the face, this makes sense, but it comes with two issues:
1. It will totally break in an unrecoverable way in a case where it might not actually be a break.
2. Nothing else has this behavior - components and techs do not throw.

Don't throw when re-registering a plugin

---

src/js/tracks/text-track.js
test/unit/tech/tech-faker.js
test/unit/tracks/html-track-element.test.js
test/unit/tracks/text-track-list.test.js
test/unit/tracks/text-track.test.js

Wait for tech to be ready before worrying about timeupdate events

5.x fix cue-points with a startTime of 0

---

src/js/tracks/text-track.js
test/unit/tech/tech-faker.js
test/unit/tracks/html-track-element.test.js
test/unit/tracks/text-track-list.test.js
test/unit/tracks/text-track.test.js

Previously `timeupdate` would fire before the video was playing, and the tech was not ready. This caused issues when `preload` was set to `auto`, because `cuechange` would fire before the video was even started for cues with a `startTime` of 0.
* Wait for tech to be ready before watching for `timeupdate`
* update unit tests to use TechFaker
* Add a unit test to verify that we wait for Tech to be ready.

fix: cues at startTime 0 do not fire

---

src/js/utils/dom.js

Verify that `el` is defined so that we don't throw if we get to this function with an undefined `el`

fix: dom.getBoundingClientRect check that el is defined

---

src/js/control-bar/playback-rate-menu/playback-rate-menu-button.js
src/js/control-bar/text-track-controls/captions-button.js
src/js/control-bar/text-track-controls/chapters-button.js
src/js/control-bar/text-track-controls/descriptions-button.js
src/js/control-bar/text-track-controls/subtitles-button.js

In #4034, we changed the way that menu buttons work slightly by introduction a wrapper element with a separate wrapper css builder. However, this broke, at least the playback-rate menu.
This PR adds a `buildWrapperCSSClass` to each of our menu buttons.

fix: add buildWrapperCSSClass methods to all menu buttons

---

src/js/control-bar/text-track-controls/captions-button.js
src/js/control-bar/text-track-controls/text-track-button.js
src/js/menu/menu-button.js

When remote subtitle text tracks are removed and there are none left, the subtitle button button persists in the menu bar. This also applies to the descriptions button as seen in #3994.
Reduced test case created by @mctep: http://jsbin.com/navoruk/1/edit?html,js,output
Addresses #3890, #3994
- Implement a `getHideThreshold` function in `menu-button` and override it in `captions-button`.
- Remove `menu-button` descendants' update methods

fix(MenuButton) Implement unified method of showing/hiding MenuButton

---

src/js/control-bar/audio-track-controls/audio-track-button.js

Similar to #4146, this update fixes the CSS on the audio tracks menu button wrapper after the changes in #4034.

fix(audio-tracks-button): add wrapper CSS builder to audio tracks menu button

---

sandbox/combined-tracks.html.example

Remove poster image which doesn't match the video from the 'combined-tracks.html' example in sandbox, and also fixed a typo.

Fix poster image to match the video in the 'combined-tracks.html' example in sandbox

---

src/css/components/_control.scss
src/css/components/_subs-caps.scss
src/js/control-bar/text-track-controls/subs-caps-button.js
src/js/control-bar/text-track-controls/subs-caps-menu-item.js
src/js/control-bar/text-track-controls/text-track-button.js

We want to visually show that captions items in the subs-caps menu are captions vs subtitles using the captions icon. However, we want to hide this from screen readers. Moreover, we can't display things visually that isn't also conveyed to screen readers.
To do so, I created a Subs Caps Menu Item which adds an icon placeholder for the icon and a localized text of `captions` for screen readers.
@OwenEdwards can you review this please? Thanks!

fix(subs-caps-button): captions items should hide icon from SR

---

src/js/control-bar/text-track-controls/captions-button.js
src/js/control-bar/text-track-controls/text-track-button.js
src/js/menu/menu-button.js

Same as https://github.com/videojs/video.js/pull/3993 but targeting `master`.

fix(MenuButton) Unify behavior of showing/hiding

---

src/js/control-bar/track-button.js
src/js/tech/html5.js
src/js/tech/tech.js

In addition, the track buttons need to update on the ready event because when the tech loads, it could run with support native captions, so, it needs to know whether to include the captions settings menu.
And all tracks should always be included in `player.textTracks()` and not just `player.remoteTextTracks()`.

fix(tracks): allow forcing native text tracks on or off

---

test/unit/plugin-static.test.js

This silences a deprecation warning for the plugin re-registration test.

Silence deprecation warning from test

---

src/css/components/_control.scss
src/js/control-bar/text-track-controls/subs-caps-button.js
src/js/menu/menu-button.js

Make sure that the button inside the menu button element isn't a
vjs-control but make sure that the icon-placeholder is sized properly.

fix(icon-placeholder): align icons on ie8 properly

---

src/css/components/_captions-settings.scss
src/js/control-bar/progress-control/play-progress-bar.js
src/js/control-bar/text-track-controls/caption-settings-menu-item.js
src/js/menu/menu.js

This fixes a logging in the console regarding timetooltips which don't exist. Also, makes sure not to focus the menu button when the captions settings menu item is clicked since the caption settings is getting focused instead. In addition, it makes sure the legend text in the track settings is the foreground color.

fix(ie8): various minor ie8 fixes

---

src/js/tech/tech.js

The issue is that in Flash, `Flash.embed` wraps the `object` element in a div but that `object` element is what is referenced by `this.el()`, so, `parentNode` isn't null but we aren't actually in the DOM. Instead, just check to see whether the tech element is in the DOM or not via `node.contains()`.

fix(vttjs): wait till tech el in DOM before loading vttjs

---

docs/examples/elephantsdream/index.html

Same as #4137, but for docs/example/elephantsdream/index.html.

chore(docs): Use Elephants Dream video files from CDN for docs/examples/elephantsdream/index.html

---

src/js/error-display.js
src/js/modal-dialog.js
test/unit/modal-dialog.test.js

* Added a feature to make it optional for `ModalDialog` to `pauseOnOpen`
* Use `pauseOnOpen: false` in `ErrorDisplay` so that errors that can recover during playback will recover

fix: dont pause when the ErrorDisplay is opened

---

docs/guides/faq.md
docs/guides/options.md

`techOrder` option was a bit out of date, I have updated it to reflect the current state of 6.0.0.

docs: tech order will only have html5 by default

---

build/fix-api-docs.js
docs/guides/audio-tracks.md
docs/guides/components.md
docs/guides/debugging.md
docs/guides/faq.md
docs/guides/languages.md
docs/guides/modal-dialog.md
docs/guides/options.md
docs/guides/player-workflows.md
docs/guides/plugins.md
docs/guides/react.md
docs/guides/setup.md
docs/guides/text-tracks.md
docs/guides/tracks.md
docs/guides/troubleshooting.md
docs/guides/video-tracks.md
docs/guides/videojs.md
docs/index.md
docs/translations-needed.md
package.json
src/js/player.js
src/js/setup.js
src/js/tech/tech.js
src/js/tracks/html-track-element-list.js
src/js/tracks/track-types.js
src/js/utils/dom.js
src/js/video.js

* Update the API doc build to fix links after generation
* Fix any currently broken API docs
* Used `linkdown` to make sure links are working
* The tech source handler mixin is currently not showing/broken in the docs
* videojs itself does not show most of its functions in the API docs
* Some things are using `Dom` when they should be using `module:dom`

fix links in docs

---

src/js/control-bar/text-track-controls/text-track-menu-item.js
src/js/tech/tech.js
src/js/tracks/text-track.js

There are currently two issues with `TextTrack`s that have `default` set to `true` when added. 
1. The TextTrackMenu has the `captions off` and the new `default` caption button both selected
2. The captions do not show up until after a re-selection
1. is addressed by listening for player `loadstart`, rather than just `texttrackchange` as in most cases text tracks will be added before we start to listen for `texttrackchange`
2. Treat `addtrack` and `removetrack` similar to how we treat `change` now (watch for `cuechange` on any showing tracks and update the display)

fix: default text tracks

---

src/js/control-bar/text-track-controls/text-track-menu-item.js
src/js/tech/tech.js

There are currently two issues with `TextTrack`s that have `default` set to `true` when added. 
1. The TextTrackMenu has the `captions off` and the new `default` caption button both selected
2. The captions do not show up until after a re-selection
1. is addressed by listening for player `loadstart`, rather than just `texttrackchange` as in most cases text tracks will be added before we start to listen for `texttrackchange`
2. Treat `addtrack` and `removetrack` similar to how we treat `change` now (watch for `cuechange` on any showing tracks and update the display)

5.x fix: default track selection

---

src/js/tracks/text-track.js
test/unit/tracks/text-track.test.js

This PR fixes two issues:
1. If you add two of the same cues to the cues list they will both be removed by one call to `removeCue`
2. If you create an add a native cue to the cues list. You cannot use the native cue to remove the cue that was added to the cue list.

fix: removeCue with native/same cues

---

src/js/tracks/text-track.js
test/unit/tracks/text-track.test.js

This PR fixes two issues:
1. If you add two of the same cues to the cues list they will both be removed by one call to `removeCue`
2. If you create an add a native cue to the cues list. You cannot use the native cue to remove the cue that was added to the cue list.

5.x-fix: removeCue with native/same cues 

---

src/js/control-bar/mute-toggle.js
test/unit/controls.test.js

When unmuting and `lastVolume` is less than 0.1, set volume to 0.1 instead of to `lastVolume`.
Fixes #4054.
Volume set to **0.024390243902439025**.
Volume set to **0.1**.

Minimum volume after unmuting

---

test/unit/controls.test.js

Fix [test failure](https://travis-ci.org/videojs/video.js/builds/214771473#L356) caused by IE9 rounding issue in #4227.

Fix IE9 rounding issue

---

src/css/components/_captions-settings.scss
src/css/components/_modal-dialog.scss
src/css/components/menu/_menu.scss
src/js/tracks/text-track-settings.js

Make the font column of the text track settings dialog also use fieldset and legends like the colors column. Also, don't set a width on the label and legend elements.
This makes it so that the two columns line themselves up similarly.

Tracks settings updates

---

src/js/player.js

This silences the play promise when `play` is called while source is changing.
There are a few other calls to `play` in video.js that we potentially should silence, like in the PosterImage. Those can be fixed later on if we see that they get rejected often.

fix: silence play promise error

---

package.json

We can't update qunitjs yet because of our IE8 support.
We don't want to upgrade sinon until we're ready.
So, we are [telling greenkeeper to ignore](https://github.com/greenkeeperio/greenkeeper#repository-options) those two dependencies.

chore: ignore qunit and sinon from greenkeeper

---

src/css/components/_layout.scss

The focus ring on the player itself isn't necessary and can be confusing and distracting to sighted users. This PR removes the focus ring from the player element itself but not from other elements.

fix: remove focus ring from player itself

---

docs/guides/components.md

Closes [#4266](https://github.com/videojs/video.js/issues/4266)
Video.js 6 replaces the `VolumeMenuButton` component with the `VolumePanel` component. This PR updates the default component tree in the video.js 6 docs (https://github.com/videojs/video.js/blob/master/docs/guides/components.md#default-component-tree) to reflect this.

docs: Replaced VolumeMenuButton with VolumePanel in component tree doc

---

.gitignore

Just adding * at the end of npm-debug.log gitignore rule so that files like npm-debug.log.2170340511 are also ignored.
Just adding * at the end of npm-debug.log gitignore rule so that files like npm-debug.log.2170340511 are also ignored.

npm-debug.log.* to gitignore

---

src/js/player.js
src/js/utils/to-title-case.js
test/unit/player.test.js
test/unit/utils/to-title-case.test.js

In the new middleware work, the way that new sources were loaded was refactored. We also recently made techs and components work either TitleCased or camelcased. There was one comparison that didn't do the proper check and cause the tech to be reloaded, even if the two techs were the same.

fix: techOrder names can be camelCased.

---

COLLABORATOR_GUIDE.md
docs/guides/faq.md
docs/guides/setup.md

Since video.js 6 no longer officially supports bower (https://github.com/videojs/video.js/issues/4012), remove some old mentions in the docs of bower.

docs: remove mentions of bower support

---

docs/guides/react.md
docs/guides/webpack.md

Note how to require the css file, as denoted in the FAQ sections and clarification on how to resolve the .eot files in the css file.

Add: Notes on Webpack Fixes in React Docs

---

src/js/utils/browser.js

`videojs.browser.IE_VERSION` is `null` in IE11 because IE11 uses a different user agent string than other IE versions
#4278

set IE_VERSION correctly for IE11

---

src/js/tech/html5.js
src/js/utils/browser.js
test/unit/tech/html5.test.js

#4321 for v5
Android Chrome now supports playbackRate properly, so removes the blacklist added in #3246 for newer Chrome versions.  
Adds `browser.CHROME_VERSION` as a necessary evil.
No longer blacklists for Chrome 58+ -- this could possibly be fixed since 52, but 58 is all I've been able to test on and most users should keep Chrome up to date.

Remove playbackRate blacklist for recent Android Chrome (v5)

---

src/js/player.js
test/unit/player.test.js

#4320 for v5.
Adds a version class to the player to simplify CSS for plugins supporting multiple versions. For example to add an icon to a button in v5 you'd target `.my-button:before`, in v6 `.my-button .vjs-icon-placeholder:before`.
Adds a class e.g. `vjs-v5` to the player element.

Add a version class to the player (v5)

---

package.json
src/js/player.js
src/js/tech/flash.js
src/js/tech/html5.js
src/js/tech/tech.js
test/api/api.js
test/unit/tech/flash.test.js
test/unit/tech/html5.test.js
test/unit/tech/tech.test.js

NOTE: This requires https://github.com/videojs/video-js-swf/pull/225
Provides a tech getter for getVideoPlaybackQuality as specified by the W3C's Media Playback Quality API: https://wicg.github.io/media-playback-quality/

Add getVideoPlaybackQuality API

---

src/js/player.js
src/js/tech/html5.js
src/js/tech/tech.js
test/unit/player.test.js
test/unit/setup.test.js
test/unit/tech/html5.test.js

Video.js players can accept a number of standard `<video>` element options (`autoplay`, `muted`, `loop`, etc), but not currently `playsinline`, which is now part of the [HTML spec](https://html.spec.whatwg.org/multipage/embedded-content.html#attr-video-playsinline). We should add it to the list of `<video>` attributes that can be provided to the player as options.
Update the `Html5` and `Player` classes with getter and setter methods for `playsinline` and make a few other additions to ensure that the `playsinline` option works the same way as the other `<video>` element options.

Allow 'playsinline' player option

---

test/unit/player.test.js

This test is more of an integration test and uses the html5 tech to make
sure the setter and getter work properly. This causes issues with IE8
which doesn't work well with the Html5 tech.
Instead, we wrap the test in an if that checks whether Html5 is
supported.

test: fix playsinline test for IE8

---

docs/guides/react.md

This section demonstrates how to register a VJS component, but allow it to be render within the React ecosystem.
Update docs.

Docs: Use a React component as a VJS component

---

src/js/tech/html5.js
src/js/utils/browser.js
test/unit/tech/html5.test.js

Android Chrome now supports playbackRate properly, so removes the blacklist added in #3246 for newer Chrome versions.  
Adds `browser.CHROME_VERSION` as a necessary evil.
No longer blacklists for Chrome 58+ -- this could possibly be fixed since 52, but 58 is all I've been able to test on and most users should keep Chrome up to date.

Remove playbackRate blacklist for recent Android Chrome

---

docs/guides/plugins.md
src/js/plugin.js
test/unit/plugin-advanced.test.js
test/unit/plugin-basic.test.js

This adds a `beforepluginsetup` event as well as `beforepluginsetup:$name` and `pluginsetup:$name` events.
The drive behind this is improving the ability for people to make cross-plugin dependencies in a more robust manner.

feat: Add 'beforepluginsetup' event and named plugin setup events (e.g. 'pluginsetup:foo')

---

src/js/player.js
test/unit/player.test.js

Add a version class to the player to simplify CSS for plugins supporting multiple versions. For example to add an icon to a button in v5 you'd target `.my-button:before`, in v6 `.my-button .vjs-icon-placeholder:before`.
Adds a class e.g. `vjs-v6` to the player element.

Add a version class to the player

---

src/js/clickable-component.js
test/unit/clickable-component.test.js

Prevent ClickableComponents re-adding event listeners each time `enabled()` is called
Fixes #4312
- Keeps track of enabled state (`this.enabled_`)
- `enable()` doesn't do anything if the component is enabled, so the event handlers are not re-added

Prevent dupe events on enabled ClickableComponents

---

src/js/control-bar/text-track-controls/text-track-button.js

On Safari and iOS, we use native text tracks, so, during text track
button creation, textTracks() is populated. However, `this.kinds_` isn't
necessarily set and ends up throwing.
Instead, we want to move the fallback for `this.kinds_` from the
constructor and right above the usage of `this.kinds_`.

fix: TextTrackButton on Safari and iOS

---

src/js/control-bar/text-track-controls/text-track-menu-item.js

Hi there,
Would you consider this fix for triggering less track.modechange and subsequently trackList.change events - at the moment too many of those are triggered even if nothing has actually changed.
cc https://github.com/videojs/video.js/issues/4294

Only update track mode if changed

---

src/js/clickable-component.js
test/unit/clickable-component.test.js

Like #4316 for v6, this prevents multiple click handlers being added if an already enabled component is enabled. In the PR for six, `ClickableComponent` was tracking `this.enabled_`  but this is incompatible with v5 on a `MenuButton` which also changes the state of `this.enabled_`. 
Removes event handlers in `enable()` before adding them. 
Do we want the same fix implemented in a different way in 5 and 6 though?

Prevent dupe events on enabled ClickableComponents (v5)

---

src/js/video.js

The order of imports in video.js is causing some issues with some bundlers from producing a working package. While we should try and produce a reduced test case for the bundlers to fix this issue, we should also just work around it since it is fairly easy to do so.

chore: move imports up so bundlers wont trip up

---

src/js/control-bar/text-track-controls/off-text-track-menu-item.js
src/js/control-bar/text-track-controls/text-track-button.js
src/js/control-bar/text-track-controls/text-track-menu-item.js
src/js/tracks/text-track-display.js
src/js/tracks/text-track-list.js
src/js/tracks/text-track.js
test/unit/tracks/text-track-display.test.js
test/unit/tracks/text-tracks.test.js

This should allow a user's choice of subtitle or description to be respected across an entire session(if available).
- Remember the user selection
- User selected choice is preferred over the first default track
- If necessary, more likely in a feature request than a bug fix

Persist caption/description choice over source changes

---

test/unit/tracks/text-track-display.test.js

The test for user-selected language was unnecessarily specifying html5 as the techOrder

Removing test techOrder

---

src/js/player.js

A link was incorrect on the docs site. I believe this will fix it?

Fixing player.remoteTextTracks jsdoc

---

docs/guides/options.md

Update to the documentation to fix a broken example: fullscreenToggle is referred to as fullscreenControl. See #4407.

Update name of FullscreenToggle in documentation

---

src/js/player.js

docs: Fix links in API docs for several Player events.

---

docs/translations-needed.md
lang/de.json
lang/en.json
lang/fr.json
lang/sk.json

The lang files were translating "all settings to the default values" instead of "[restore all settings to the default values](https://github.com/videojs/video.js/blob/master/src/js/tracks/text-track-settings.js#L461)".
- Updated the key in all lang files already using it
- Updated the French translation and added some further missing German translations
@h0lysl4y3r the Slovakian translation probably needs an update now.

fix: Update a translation key to match correct string

---

src/js/tracks/audio-track-list.js
src/js/tracks/video-track-list.js

in IE10, the variable list for disableOthers returns "permission denied"
this causes an uncaught exception which breaks the rest of the javascript execution
issue described in #4378 
directly invoking list[i].id triggers the permission denied error
however, if an object has all of its properties denied access to, Object.keys returns a length of 0
- [ x ] Feature implemented / Bug fixed

fix IE10 issue for disableOthers

---

src/js/clickable-component.js
src/js/control-bar/time-controls/current-time-display.js
src/js/control-bar/time-controls/duration-display.js
src/js/control-bar/time-controls/remaining-time-display.js
src/js/tech/html5.js
src/js/tracks/text-track-settings.js

These are a few performance improvements.
- Use `textContent` instead of `innerHTML` for text content.
- Construct `TextTrackSettings` content with HTML strings where possible because it's a bit faster than manual DOM construction.
- Do minimal DOM updates to time controls. This reduces our `timeupdate` footprint from ~2-2.5ms to ~1ms!

perf: Various small performance improvements.

---

src/js/tech/html5.js

When picture-in-picture mode is entered on Safari, `webkitbeginfullscreen` is triggered which results in a proxied `fullscreenchange` event and adding the fullscreen class to the player. That causes the tech element to collapse to zero height so that the "this video is playing in picture in picture" placeholder is not visible. 
On `webkitbeginfullscreen` check whether the presentation mode is `picture-in-picture` before proxying a `fullscreenchange` event.

fix: Safari picture-in-picture triggers fullscreenchange

---

src/js/utils/events.js

Not using passive event listeners now causes Chrome to log warnings to the console, and possibly has a performance impact
Fixes #4432
Where supported, use passive event listeners for `touchmove` and `touchstart`

Use passive event listeners for touchstart/touchmove

---

src/js/player.js

`player.duration()` currently returns 0 if the duration is not known, when it should return `NaN`. The problem is that if `NaN` is passed to `player.duration()` as an argument, [we set the duration to 0](https://github.com/videojs/video.js/blob/5.x/src/js/player.js#L1700). If `player.cache_.duration` was set to `NaN` by other means, `player.duration()` [would still return 0](https://github.com/videojs/video.js/blob/5.x/src/js/player.js#L1697). If approved, this will require a sister PR in the 5.x branch as well.
Modify the player `duration()` method so that it will 1.) set the cached duration to `NaN` if it is passed in as an argument, and 2.) return the proper value when called without an argument.

fix: player.duration() should return NaN if duration is not known

---

src/js/tech/tech.js
test/unit/tech/tech.test.js
test/unit/tracks/text-tracks.test.js

We added a feature so that remote text tracks can auto-removed when a source changes. However, in 6.x we changed the source behavior to be asynchronous meaning that some text tracks were accidentally being removed when they weren't supposed to be.
For example:
```js
var player = videojs('my-player');
player.src({src: 'video.mp4', type: 'video/mp4'});
// set second arg to false so that they get auto-removed on source change
player.addRemoteTextTrack({kind: 'captions', src: 'text.vtt', srclang: 'en'}, false);
```
Now when the player loads, this captions track is actually missing because it was removed.
Instead of adding auto-removal tracks immediately to the list, wait until we've selected a source before adding them in.
This probably needs a test.
Fixes #4403 and #4315.

fix: auto-removal remote text tracks being removed when not supposed to

---

src/js/tech/html5.js

When picture-in-picture mode is entered on Safari, `webkitbeginfullscreen` is triggered which results in a proxied `fullscreenchange` event and adding the fullscreen class to the player. That causes the tech element to collapse to zero height so that the "this video is playing in picture in picture" placeholder is not visible. 
As with #4437 for v6, on `webkitbeginfullscreen` check whether the presentation mode is `picture-in-picture' before proxying a `fullscreenchange` event.

fix: Safari picture-in-picture triggers fullscreenchange (5.x)

---

src/js/utils/events.js

#4440 for 5.x
Not using passive event listeners now causes Chrome to log warnings to the console, and possibly has a performance impact
Where supported, use passive event listeners for `touchmove` and `touchstart`

Use passive event listeners for touchstart/touchmove (5.x)

---

src/js/player.js
test/unit/player.test.js

This is a sister PR for [this](https://github.com/videojs/video.js/pull/4443), and also adds unit tests for the changes to the `player.duration()` method. Once approved, I'll make another PR against master to make sure these unit tests get added there as well.

fix: player.duration() should return NaN if duration is not known (sister)

---

src/css/components/_playback-rate.scss

In 6.0, we changed the way that Menu Buttons were being created by
wrapping an actual button with a menu sibling in a container. The
playback rate menu also had a rate value display. In 6.x, this rate
value display ended up coming on top of the button itself and capturing
it's clicks. So, we want to remove pointer-events from the rate-value
display and resize the actual button to be the size of the control.

fix(playback rate menu): cycling rates via click

---

src/js/player.js

The API docs for `Player#src` are inaccurate/incomplete.

docs: Fix Player#src API documentation.

---

build/gh-release.js

Add a `--prerelease` flag so we can run `gh-release.js` manually and mark releases as prerelease.
Also, find the correct zip file.

chore(gh-release): add prerelease flag and find right zip 

---

src/js/control-bar/mute-toggle.js

Potential fix for https://github.com/videojs/video.js/issues/4424
Change the volume levels used to select the videojs-icon-volume-* classes so muted(true) and volume(0) do not use the same icon.  Fixes an issue where sliding the volume slider to 0 has the appearance of setting muted(true) but toggling the mute-toggle/volumeMenuButton does not restore the volume.  Only setting the volume using the slider removes the muted icon appearance.
- [ x ] Feature implemented / Bug fixed

adjust volume ranges so muted(true) and vol=0 do not use the same icons

---

src/js/big-play-button.js
src/js/button.js

This is a simple change to not change the focus to the play toggle from the Big Play Button when clicking on it with the mouse.
There's still work to be done with regards to the focus ring and mouse vs key events but that's for another time and would probably be more involved.
We cancel out focus changing if the mouse was used to click the button, or, as far as we could tell via the `mousedown` handler. Unfortunately, using VoiceOver's functionality (via control-option space), we also get a `mousedown` event. However, those events do not add `clientX` and `clientY` to the `click` event like a true mouse event does.

fix: only change focus from BPB if not a mouse click

---

src/css/components/_button.scss

Fix the subs caps button size issue [(#4547)](https://github.com/videojs/video.js/issues/4547)

Fix: Subs caps button size issue

---

src/js/tech/html5.js

This PR addresses a behavior in the iOS Safari native player: if a captions text track has its mode set to `showing`, Safari will set the mode of any other present tracks to `disabled`, including metadata tracks. In iOS Safari, specifically, this also unfortunately means that the `cues` and `activeCues` arrays for those disabled tracks are set to `null`. This is a problem for developers who wish to have functional cue points in iOS fullscreen video playback.
Add a private `Html5` tech method that snapshots the state of all metadata tracks leading up to a `'fullscreenchange'` event, then retroactively restores the metadata tracks to their pre-fullscreen state after the first track `'change'` event that occurs during native playback. Although it isn't ideal, we are presuming that the first …

Fix: issue where tracks are disabled and cuepoints are cleared in iOS native player

---

build/rollup.js

When https://github.com/videojs/vtt.js/issues/15 is fixed, this should be reverted.

fix: remove 'use strict' from rollup because vttjs isn't strict

---

build/grunt.js
build/rollup.js
build/tasks/sandbox.js

Makes the output of dev rollup and babel watch more quiet.
Add a task to copy .example files over to non .example files if the non .example files are *not* present.

chore: improve dev and beginner experience

---

docs/guides/debugging.md
docs/guides/event-target.md
docs/guides/faq.md
docs/guides/hooks.md
docs/guides/languages.md
docs/guides/options.md
docs/guides/player-workflows.md
docs/guides/plugins.md
docs/guides/react.md
docs/guides/setup.md
docs/guides/tech.md
docs/guides/videojs.md
docs/guides/webpack.md
docs/index.md

Some miscellaneous doc updates, including:
* Updates for v6, e.g. `plugin` -> `registerPlugin`
* Tweaked and expanded some FAQ and language guide content. 
* Some fussing over writing Video.js consistently when a proper noun

docs: updates to faq, language guide and minor edits

---

src/js/control-bar/playback-rate-menu/playback-rate-menu-button.js

Bug: the playback rate default value was missing the "x".
Changed the default value from "1", to "1x", to behave the same as when it is after you chose a rate.

Fix playback rate default text

---

src/js/tech/html5.js
src/js/utils/dom.js

I don't think this is quite complete yet but this is the initial implementation for making boolean attributes like `muted` set the property `video.muted = {{boolean}}` and the attribute `video.setAttribute('muted', 'muted')` when changing the value.
Also, in html5's createEl, we were setting/updating attributes for various properties but we were only setting the attributes and not also the properties but also autoplay was happening first rather than last which caused autoplay to fail because `muted` and `playsinline` weren't necessary set by that time.

fix: make boolean attributes set and check both the associated property and the attribute

---

src/js/tech/html5.js

This is the sister PR for [#4496](https://github.com/videojs/video.js/pull/4496).
Closed the [previous sister](https://github.com/videojs/video.js/pull/4568) because the Travis build was against master instead of 5.x.

Fix cuepoints in iOS native player (sister)

---

src/js/player.js

When setting the source, we were calling `play` if `autoplay` was set. We shouldn't do that and instead we should rely on the browser or tech (like Flash) to handle it properly.
I'm unsure whether this should be a `fix` or a `feat`, thoughts?
There are two more places that we should consider removing but they are probably OK because they're specific/bug fixes rather than general "if autoplay, call play" kind of deals.
There's one in `enterFullscreen` on the html5 tech, which should only be called on iOS devices.
https://github.com/videojs/video.js/blob/fe63992bd1e0d6e4eb7783584bce17c2796c4a2c/src/js/tech/html5.js#L548-L557
In the player, in `handleTechReady_`, there's another call to `play`, which is a fix for older chrome and older safari. This one seems more of a candidate for removal …

fix: rely on browser or tech to handle autoplay

---

package.json

Most of our other projects have a watch command (rebuild on change, but no dev server). This PR simply adds an alias for a command that already exists so that their is a common command.

ignore: alias rollup-dev to watch for development

---

docs/guides/options.md

Add documentation for the already supported `playbackRates` option, based on my experience and [this StackOverflow post](https://stackoverflow.com/a/24767026).
Fix to https://github.com/videojs/videojs.com/issues/71 (sorry, I probably put that in the wrong repo of the same org).
* New section in `docs/guides/options.md` describing `playbackRates`

Document playbackRates

---

docs/guides/plugins.md

Based on the docs it should be `this` instead of `player`.
vjsstandard also found issue in my plugin:
```
/home/foo/projects/videojs-wavesurfer/src/videojs.wavesurfer.js:30:30: "player" is not defined.
```

fix typo in plugins guide

---

src/js/control-bar/play-toggle.js

When seeking backwards after the video has ended, the `vjs-ended` class will remain on the video until play is pushed. This means the the play button will still show as a replay button, which seems incorrect to me.
This PR removes `vjs-ended` on any `seeked` event on the player and resets the button into a play/pause state depending upon the player state.

fix: reset to a play/pause button when seeking after ended

---

src/js/control-bar/time-controls/current-time-display.js
src/js/control-bar/time-controls/duration-display.js
src/js/control-bar/time-controls/remaining-time-display.js
src/js/control-bar/time-controls/time-display.js

Refactor the Time displays so that they use the same base class, as they are nearly all the same.
Create a `TimeDisplay` class and use that class in `DurationDisplay`, `RemainingTimeDisplay`, or `CurrentTimeDisplay`

refactor: Create a base time display class, and use it

---

src/js/menu/menu-button.js
src/js/utils/dom.js

Changing focus to a sub-menu (ex. by tapping the captions menu button) when a player is embedded in an iframe is resulting in unwanted scrolling behavior on iOS. @gkatsev is planning to refactor all focus handling soon, but this will serve as a temporary fix in the meantime. 
Modify the MenuButton `pressButton()` method to only change focus to a sub-menu on platforms other than iOS

fix: issue where changing focus is causing unwanted scrolling behavior on iOS

---

src/js/control-bar/time-controls/remaining-time-display.js
src/js/player.js

Allow remainingTime to be given a rounding function during use. Add a function which should be used as the default when displaying remaining time.
Fixes #4608

feat: add remainingTimeDisplay method

---

src/js/control-bar/time-controls/remaining-time-display.js
src/js/control-bar/time-controls/time-display.js

The recent refactoring of time displays is great, but it seems there was a bug where it would always prepend times with `-` even when we want a positive number (i.e. everywhere except remaining time display)!

fix: Make sure time displays use correctly-formatted time.

---

src/js/control-bar/time-controls/current-time-display.js

Pretty self-explanatory. This can cause an error to be thrown.

fix: Fix a typo in current time display component.

---

src/js/control-bar/time-controls/remaining-time-display.js

Anyone that mocked the player would have to also mock this new method. This would cause them to break until they have it.

fix: a breaking change caused by the use of remainingTimeDisplay

---

build/gh-release.js

We've been printing the resulting value from a successful call to the ghrelease, this was useful for debugging but isn't necessary anymore.
Add the result to the error conditional with some headings.

chore(gh-release): no console log on success

---

src/js/control-bar/play-toggle.js

There are cases where we might not see a `seeked` event when replaying a video. This will make this code more reliable.

fix: Make sure we remove vjs-ended from the play toggle in all appropriate cases.

---

package-lock.json

Adds the package-lock.json file for npm 5.

chore: Add package-lock.json file.

---

test/unit/tracks/text-track-display.test.js

Currently you have to specify a second param in addRemoteTextTrack so that it does not log. This causes a few lines to log for every browser, which can make things a bit confusing.

ignore: get rid of redundant test logging

---

docs/guides/hooks.md
src/js/video.js
test/unit/videojs-hooks.test.js

This adds a `videojs.hookOnce()` method, which allows single-run hooks.
Also, cleaned up the guide for readability and grammar/spelling/typos.

feat: Add videojs.hookOnce method to allow single-run hooks.

---

src/css/_utilities.scss

add Konqueror and iOS Safari, by https://stackoverflow.com/questions/826782/how-to-disable-text-selection-highlighting-using-css

update user-select none

---

src/js/modal-dialog.js

Don't enable player controls if they where disabled when ModalDialog closes.
Save the result of "player.controls()" when the ModalDialgo opens and set it again on close.

fix: Don't enable player controls if they where disabled when ModalDialog closes.

---

src/js/utils/events.js
src/js/utils/url.js

I found a problem, where adding custom functions to Object.prototype made the event-off function crash upon iterating over all properties of an object.
I fixed it by checking for ```hasOwnProperty```. ~~As the tests failed for me on Win10 IE11 I also fixed issue #3100 that addressed this.~~
~~I added an if-clause to url.js‘s ```parseUrl``` to add the current window.location.protocol if the protocol of the given url is empty (or ```//```).~~
~~I also added 2 if statements to events.js‘s ```off``` in the "type is falsy" if to check that data and data.handler is present (occasionally was undefined with me) and within the loop check if data.handler has t as it‘s own property~~.
I added an if statement to events.js‘s off in the ```if (!type)``` to check that data.handler is still present and …

Fixing an issue where patching functions into Object.prototype makes the event removal crash.

---

src/js/control-bar/progress-control/seek-bar.js

As with the other prs that just went in, we want to make it seem like a video has ended from a user perspective, even if internally e know something is off. (currentTime !== duration, but the video has ended).
A small refactor of `seekBar` to allow this

feat: set the seek bar to 100% on ended

---

src/js/player.js

update doc on hasStarted()
I feel 'request' are more suitable than hasStarted (as a variable) because when I do "if (request === undefined)", it mean if you don't have any request, then we just return current status, it a bit more clear

refactor player.hasStarted()

---

src/js/component.js

refactor component.ready()

---

src/js/utils/url.js

url.js ```parseUrl``` drops the protocol from the return object on IE if the url starts with "//:". Chrome returns the current ```window.location.protocol``` value in that case. This causes the test mentioned in #3100 to fail on IE, but not on Chrome or FF.
I added an if-clause to url.js‘s ```parseUrl``` to add the current window.location.protocol if the protocol of the given url is empty (or ```//```).

Bugfix for issue #3100

---

src/css/components/_progress.scss
src/css/components/_slider.scss
src/js/control-bar/progress-control/progress-control.js
src/js/control-bar/progress-control/seek-bar.js
src/js/slider/slider.js

Sometimes you do not want the user to be able to use the progress controls, such as during an ad. It would be quite difficult to do this outside of video.js due to the complexity of it. I think that we should allow this within video.js.
Add functions to disable/enable progress controls

feat: allow progress controls to be disabled

---

src/js/tracks/text-track-settings.js

The `aria-labelledby` attribute on the `fontPercent`, `edgeStyle`, and
`fontFamily` select options includes an extra space since there is
no `ledgendId` variable being set on the `createElFont_()` method.
[Fixes #4688](https://github.com/videojs/video.js/issues/4688)
This fix adds a check to see if the `legendId` value is set or not inside
the `createElSelect_()` method. This should keep the extra space
from appearing on the select tags created by the `createElFont_()`
method.

fix: aria-labelledby attribute has an extra space

---

src/js/component.js
src/js/control-bar/time-controls/duration-display.js
src/js/control-bar/time-controls/time-display.js

Right now the `durationchange` event is throttled with the other two events, `timeupdate` and `loadedmetadata`. This means that only one of those events will trigger an update if they all occur within 25ms of each other. 
This functionality makes sense for `timeupdate` or `loadedmetadata` as those should not indicate a time update (even though they often do). 
For `durationchange` however it will always indicate a change in the duration, and we want to always update the display when it happens. Here is a scenario of how we could show duration incorrectly right now:
User is playing a video that has a postroll ad at the end. After the postroll ad their will be a `timeupdate`, and then a `durationchange` to signify that we are back in content. Then `ended` will fire, and no more events will …

fix: don't throttle duration change updates

---

src/js/player.js
test/unit/player.test.js

`player.src()` returns `undefined` for a new player.
Default to `''` if there is no source cached.

fix: default cached src to empty string

---

src/js/player.js

refactor player.dimension()

---

src/js/video.js

Issue #4697 
Add warning, if the element given to Video.js is not in the DOM

add warning, if the element given to Video.js is not in the DOM

---

src/js/control-bar/progress-control/seek-bar.js

Instead of tying the play progress update lifecycle to the timeupdate
event, the update happens every 15ms. This makes it so the play progress
transitions smoothly.
Fixes #4526
Here's a video!
https://www.useloom.com/share/d578023adf3545e8b97a065d22d2ea92
Instead of relying on the `timeupdate` event exclusively to update the play progress bar, we set an interval on `play` and clear this interval on `pause` and `ended`.

improvement: PlayProgressBar Smooth Transition

---

test/unit/video.test.js

Add test to #4698 
Test to make sure that warning is printed, when element given to Video.js is not in the DOM

test: warning, if the element is not in the DOM

---

src/js/plugin.js
test/unit/plugin-advanced.test.js

Having to use videojs.getPluginVersion(<pluginInstance>.constructor.name) is a bit weird when you already have an instance. I would even say we should get rid of the getPluginVersion function or deprecate it.

feat: add a version function to all advanced plugin instances

---

docs/guides/embeds.md
docs/guides/setup.md
sandbox/embeds.html.example
src/js/player.js
src/js/setup.js
src/js/video.js
test/unit/video.test.js

Add the ability to initialize Video.js with an element named `video-js`. This is because sometimes, seeing the native element is undesirable, plus, it's cool to have our own element.
Can be used just like the `video` embed. For IE9-only we have a `vjs-source` element that's copied to a `source` element because IE9 is strict about keeping `source` elements inside of `video` elements.

feat: allow embeds via <video-js> element

---

src/js/clickable-component.js
src/js/component.js
src/js/control-bar/live-display.js
src/js/control-bar/playback-rate-menu/playback-rate-menu-button.js
src/js/control-bar/progress-control/load-progress-bar.js
src/js/control-bar/text-track-controls/text-track-menu-item.js
src/js/control-bar/time-controls/time-display.js
src/js/menu/menu-button.js
src/js/menu/menu.js
src/js/mixins/evented.js
src/js/modal-dialog.js
src/js/player.js
src/js/popup/popup.js
src/js/tech/html5.js
src/js/tracks/text-track-settings.js
src/js/utils/events.js
test/unit/tracks/text-track-display.test.js
test/unit/video.test.js

We have a bunch of references to DOM elements we were retaining even after we had disposed the player. This cleans up a bunch of them.

perf: null out els on dispose to minimize detached els

---

src/js/player.js

Change setTimeout min to 4 as https://www.w3.org/TR/2011/WD-html5-20110525/timers.html#timers

refactor: player.listenForUserActivity_()

---

src/js/player.js

refactor player.controls()

---

src/js/clickable-component.js
src/js/menu/menu-item.js

@gkatsev @misteroneill cc @luarmr I'd like to make this change to avoid having weird titles for the menu items in the player. You can easily reproduce the bug by keeping your mouse over any submenu item (caption language, video quality) on your own homepage e.g.
Note: Firefox just hides an empty-space tooltip, but this issue does pop up in Chrome, IE, likely others
before:
after:

Avoid weird menu item tooltip title

---

src/js/player.js

refactor: player.usingNativeControls()

---

src/js/player.js

refactor player.userActive()

---

package-lock.json
src/js/big-play-button.js
src/js/player.js
src/js/utils/promise.js
test/unit/player-play.test.js
test/unit/utils/promise.test.js

The core goal here is to make sure the following works in light of some middleware process that makes setting the source more async than next tick:
```js
player.src('...');
player.ready(() => player.play());
```
In fact, given this change, we should even be able to do:
```js
player.src('...');
player.play();
```
Unlike #4665, which would have clarified/changed the meaning of "ready", it remains a reflection of the tech's state and we make better use of the ability to queue things on that state and on the middleware `setSource` process.

fix: Wait for loadstart when changing sources, instead of just ready.

---

src/js/video.js
test/unit/player.test.js

Currently we get logs in the tests due to a recent change. This PR fixes that. It also fixes a case were we would log that the dom element isn't in the dom, when it really is:
Here is an example (taken from the test that showed me it)
```js
const fixture = document.getElementById('qunit-fixture');
fixture.innerHTML += '<video id="test_vid_id"></video>';
const tag = document.getElementById('test_vid_id');
const player = videojs(tag)
// this would log a warning about tag not being in the dom. Technically its not because
// of the changes we made to it. I would even say that this is a bad way to get the player again.
// but I think that warning that the players tag is not in the dom on the first creation is enough, and // warning that it isn't in the dom because the tag has been changed is a …
```

test: cleanup test warnings

---

src/js/video.js
test/unit/video.test.js

Previously 'element is not in the dom' warnings would go off every time that we get a player from videojs. This change fixes that as well as a bug that would occur if the tag was passed in twice to video.js. This would cause the tag to technically not be in the dom as the element has changed, but the correct player is still returned.

fix: only print dom warning on player creation

---

package-lock.json
src/js/control-bar/progress-control/seek-bar.js

TimeUpdate ui does not fire on seek when paused. 
By manually triggering a timeupdate we force the ui to not use the cache.

Fixes TimeUI update on seek

---

src/js/player.js

We have a better engine to detect left click, fix middle click pause/playable + small refactor

refactor player.handleTechClick_() + small fix

---

src/js/player.js

If the HTML element doesn't have a lang attribute, Edge throws an exception when calling closest.getAttribute because tag.closest('[lang]') returns an empty object (which will be coerced to true) instead of null.
Just test for getAttribute on closest.
- [x ] Bug fixed

Edge 15 fix for closest.getAttribute

---

src/js/control-bar/text-track-controls/off-text-track-menu-item.js
src/js/control-bar/text-track-controls/text-track-menu-item.js

Prevents a race condition where `TextTrackList` triggers a change but it is ignored and the `OffTextTrackItem` is selected alongside the correct track.
* Use the `handleTracksChange` function in the parent class to set the default state of menu items.
* Do not set `OffTextTrackItem` to true by default.

fix: off text tracks should be set based on current state

---

build/grunt.js

Fix an issue were css was only being built if it changed on `grunt dev`

fix: an issue were css is not built initially on grunt dev

---

src/js/utils/dom.js

On handleTechClick_, before the checking was
```js
button.event !== 0 // it work on IE9
```
Now it become
```js
!dom.isSingleLeftClick // ignore IE9 check, so doesn't work anymore
```
Could make it to be something like
```js
!dom.isSingleLeftClick && browser.IE_VERSION !== 9
// should we do this or sacrifice IE9 right click pause video to make code cleaner
```

fix: can not drag on drag-bar IE9

---

src/js/utils/events.js

Once you have successfully tested that passive listeners are supported you should remove the test listeners :)

Remove listener used to test if passive listeners are supported

---

src/js/player.js

Fix for bug #4501 
Added if statement to player.currentTime() that sets argument 'seconds' to 0 if negative value is passed to the function

#4501 Seek to 0 if attempt is made to seek to negative value

---

src/js/tech/html5.js

Due to historical issues, we loops the settings attributes like muted
and autoplay in reverse order but we want to loop them in order.

fix(html5): loop video el attributes in order

---

src/js/player.js
test/unit/tech/tech-faker.js

Chrome has started pausing autoplaying video elements when they are
moved in the DOM. Here we need to make sure that if the video started
autoplaying, after we move the element in the DOM we call play again.
Fixes #4720.

fix: force autoplay in Chrome

---

lang/zh-TW.json

Add translation for "caption settings"
Added a single line, translating "caption settings" to "字幕設定"

Add translation for "caption settings"

---

src/js/menu/menu-button.js

This was resulting in the menu not being focused for all browsers/devices (if the player was in a frame), but it should target only IOS. This fixes #4821

Fix: use correct logic for menu focus

---

docs/guides/debugging.md
src/js/utils/log.js
test/unit/utils/log.test.js

Adds support for `debug` as an available logging method under `videojs.log`
Changes the default from `all` to `info`

feat: add support for debug logging

---

src/js/player.js
test/unit/player.test.js

Fixes #4629, and also handles multi-dimensional resizing correctly. I.e. `playerresize` event is only triggered once when width and height is changed at once (using `Component#dimensions`).
Trigger a `playerresize` event in `Player#dimension` if `Player.isReady_` and `skipListeners` is falsy.
`skipListeners`  is added as an optional parameter to the following methods: `Player#width`, `Player#height`, and `Player#dimension`. This parameter can be used to skip the `playerresize` event trigger.

feat: player resize event

---

src/css/components/_loading.scss
src/js/player.js

In some browsers (chrome on windows) when playing high fps video (.mp4 60 fps) there is blinking loader that keeps showing all the time while playing, despite buffer size.
I suggest add a delay (0.3s) before showing it.

feat(css): add a delay before showing loading spinner

---

test/unit/utils/log.test.js

fix: modify debug log tests to accomodate old IE stringification

---

src/js/control-bar/spacer-controls/custom-control-spacer.js

fixes #4309
replace `&nbsp;` with `\u00a0` in `src/js/control-bar/spacer-controls/custom-control-spacer.js`

replace &nbsp; with \u00a0 fixes #4309

---

src/js/video.js
test/unit/videojs-hooks.test.js

I noticed that the `hookOnce` function failed when used for the `beforesetup` hook because it didn't return the value of its inner function.

fix: Fix an issue where hookOnce failed for the 'beforesetup' hook.

---

src/js/control-bar/audio-track-controls/audio-track-menu-item.js

Audio track menu items are not updating properly. This change is related to https://github.com/videojs/video.js/pull/4745

fix: Don't bind and dispose audio track menu item prototype methods

---

docs/guides/text-tracks.md

Add docs to guide new user to use callback alternative of function ```player.addRemoteTextTrack```
issue: https://github.com/videojs/video.js/issues/4849

docs: callback alternative to addRemoteTextTrack

---

build/netlify-docs.js

The netlify script seemed like it should be working fine at the time and while it runs great for PRs it's failing against master. This allows us to debug the script better.

chore(netlify): add some debug info in the netlify command

---

src/css/components/_volume.scss
src/js/control-bar/volume-panel.js

Show horizontal volume panel only when the volume slider is active or volume button is hovered but not when focused. This addresses [#4431](https://github.com/videojs/video.js/issues/4431)

fix: Hide horizontal volume panel while the slider is not active and mute toggle button is on focus

---

docs/guides/setup.md
src/js/video.js
test/unit/video.test.js

There are cases where you want to get a player by an ID or an element, but not necessarily call `videojs()` to do it - because you don't want to create a player where one is absent.

feat: Add `getPlayer` method to Video.js.

---

src/js/tech/html5.js
test/unit/tech/html5.test.js

Patching `canPlayType` on Android shouldn't be necessary on Android Chrome since it reports its ability to player HLS correctly.
Skip patching if UA is Android Chrome.

fix: Do not patch canPlayType on Android Chrome

---

src/js/video.js
test/unit/video.test.js

When working on another PR, I noticed that there were tests somewhere not completely cleaning up after themselves. Then, I thought, wouldn't it be nice to be able to delegate method calls to _all_ players, so we could dispose them?
This new function makes that easier:
```js
videojs.getAllPlayers().forEach(p => p.dispose());
```
Previously, you'd have to do something like:
```js
Object.keys(videojs.players).map(k => videojs.players[k]).filter(Boolean).forEach(p => p.dispose());
```

feat: Add `videojs.getAllPlayers` to get an array of players.

---

docs/guides/plugins.md

Fix the typo in advance plugin, the event hook should be 'pause' instead of 'paused'

Fix the advance plugin example in documentation

---

src/js/control-bar/text-track-controls/caption-settings-menu-item.js
src/js/control-bar/text-track-controls/off-text-track-menu-item.js
src/js/control-bar/text-track-controls/text-track-menu-item.js
src/js/menu/menu-item.js

These changes address an issue where screen readers may repeatedly and redundantly read `TextTrackMenuItem`'s [control text](https://github.com/videojs/video.js/blob/master/src/js/menu/menu-item.js#L95) on every `texttrackchange` event in some browsers.
The source of the problem is in the `handleTracksChange()` method of [`TextTrackMenuItem`](https://github.com/videojs/video.js/blob/master/src/js/control-bar/text-track-controls/text-track-menu-item.js#L131-L133) and its subclass [`OffTextTrackMenuItem`](https://github.com/videojs/video.js/blob/master/src/js/control-bar/text-track-controls/off-text-track-menu-item.js#L56-L70), in which `this.selected(true/false)` gets called even if the selected state has not changed since its previous invocation.
1. Create private `isSelected_` property …

Only select TextTrackMenuItem if unselected

---

src/js/player.js
src/js/tech/middleware.js
test/unit/tech/middleware.test.js

This is the work to fix #4677. Currently, it caches middleware instances per player in an object whose keys are player ids and the value is an array of arrays. The inner array associates middleware factories and the middleware instances.
Tests need to be added and updated as well.

fix: cache middleware instances per player

---

src/js/control-bar/progress-control/progress-control.js
src/js/control-bar/progress-control/seek-bar.js

When user seek by dragging the area below the timeline, the video continue playing.
Video should stop when user is seeking
Reuse the mouse up and mouse down event handler of seekBar. So the video is paused during seek

Fix the video continue player when user drag in timeline

---

src/js/video.js
test/unit/video.test.js

As part of https://github.com/videojs/video.js/pull/4836, this piece of code was removed because it was thought it was not needed as everything else covers it. Turns out it's needed.
https://github.com/videojs/video.js/blob/f6eaa5e2ae417ffe27251133e1d1212cd9afa8e2/src/js/video.js#L103-L107

fix: regression for getting a player via the tech's id

---

docs/translations-needed.md
lang/en.json
src/js/loading-spinner.js

Partial fix for #4902 
Verified in VoiceOver.

fix: Add alternate text in an ARIA alert to the loading spinner.

---

src/js/control-bar/progress-control/seek-bar.js

I noticed a small issue when the progress control is disabled, this code throws an error because it gets called without an event object.

fix: Fix an issue where disabling the progress control would throw an error.

---

src/js/utils/events.js
test/unit/events.test.js

Currently, trigger an event with an object rather than a string will have `document` as a `target` on the event object rather than the element.

fix(events): triggering with an object had incorrect target property on event object

---

src/js/tracks/text-track-display.js

Bug fix for issue https://github.com/videojs/video.js/issues/4964
added one condition to early out to check if this.player_.textTrackSettings is false if so return as the later code isn't needed.

Small addition to an if check to fix an error

---

docs/guides/react.md

When a component is disposed of, without calling `ReactDOM.unmountComponentAtNode()` on the `data-reactroot` in the destroyed component, the `React.Component` and `videojs.Component` (here `EpisodeList` and `vjsEpisodeList`) remain in memory.
The `videojs.Component` should listen for its dispose event and unmount its React root in the corresponding `React.Component`.
I had some trouble creating a JSFiddle / CodePen to show an example, but I can produce an example project showing the memory leak if required.

guides: update react guide wrt components

---

docs/guides/options.md
docs/guides/tech.md
src/js/player.js
test/unit/player.test.js
test/unit/tech/tech-faker.js

The option for the player `techCanOverridePoster` is introduced in this commit. It allows techs to update the post whenever they like. `isPosterFromTech_` is introduced as a private player field in order to track when a poster was set by a tech. This allows us to clear the poster whenever the tech is disposed of by the player.
Additionally, attempting to set the same poster more than once will have no effect / no changes will be made, since the poster is the same. This was done in order to stop triggering multiple *posterchange* events when calling `player.poster(aPoster)` with `techCanOverridePoster` set to true.
Related to #4910 
- `techCanOverridePoster` option
- `isPosterFromTech_` player field
- `player.poster(aPoster)` triggers a single *posterchange* event
- `poster.poster(aPoster) …

Allow techs to change poster if player option `techCanOverridePoster` is set

---

src/js/utils/filter-source.js
src/js/utils/mimetypes.js
test/unit/utils/filter-source.test.js

File mimetype is filled when the file extension is known and type is not provided.
Feature to support some bad behaviours like #4469 and #4851.

feat: add mimetype type to source object when possible (#4469)

---

src/js/utils/format-time.js
src/js/video.js
test/unit/utils/format-time.test.js

Addresses #2931, approximately following the suggestions of @gkatsev in the discussion on #3433.  Adds named export `setFormatTime`  to **utils/format-time.js**. Allows overwriting the standard format-time implementation with a custom function, which will be called with seconds and guide as arguments. Also exposes setFormatTime on **videojs**.
Example:
```javascript
videojs.setFormatTime((seconds, guide) => `${seconds}, ${guide}`));
```

feat: Add an option to override format-time (#2931)

---

src/css/components/_captions-settings.scss

Currently the Caption settings menu has two issues:
1. extra characters added to the classname here: https://github.com/videojs/video.js/blob/master/src/js/tracks/text-track-settings.js#L437
2. When the player is smaller than ~450px the menu is squished together and some items are cut off. 
1. Removed the extra characters from the class name so the CSS will target correctly
2. Switch to CSS Grid with minmax column row size to make sure the menu is responsive and looks uniform at all sizes. 
**Before:**
Large Player:
Small Player: 
**After:**
Large Player:
Small Player:

Use CSS grid for caption Setting overlay to avoid cutoff

---

src/js/player.js

This reverts commit 6fe7a9a3dd4d3d4930a23cbb2b5ce23a86e97a42.
The PR #4804, which fixes #4720, causes a regression #5005. When testing for the regression, the original issue is no longer reproducible so the fix should be backed out. If someone is still using the old version of chrome and seeing the behavior of #4720, they can continue using the versions of Video.js that contain the fixed made in #4804: 6.5.2, 6.6x, 6.7.x.
Fixes #5005.

revert: Revert "fix: force autoplay in Chrome (#4804)"

---

src/js/player.js
src/js/tech/html5.js
test/karma.conf.js
test/unit/sourceset.test.js

If `.load()` is called, we don't know what the new source will be because of the asynchronous nature of the resource selection algorithm. However, we can know if the src attribute is set on the video element because that's what will be chosen. So, set the src property on the event object to be the src attribute or be the empty string. This matches how `currentSrc` works where it is an empty string when no source is set. So, when `sourceset` is triggered and `src` is `""` in the event object, it means that the source is changing.
In addition, we're going to be releasing `sourceset` as an *experimental* feature so we could improve the API and make changes in minor releases.
TODO:

fix(sourceset): set evt.src to empty string or src attr from load

---

src/js/player.js
src/js/tech/html5.js
src/js/tech/tech.js
test/unit/sourceset.test.js

While sourceset is experimental, require the option `enableSourceset`.
This can easily be reversed in a minor update.
Going forward with this because most of the core committers preferred a flag for this experimental feature and this gets it out the door sooner and can be flipped easily in the future.

feat: require enableSourceset option for event

---

src/js/tech/html5.js
src/js/tech/setup-sourceset.js

The `sourceset` code is growing a bit large, and some of the parts are going to be `re-usable` in the prs that follow this one. I think it makes sense to split it into another file.

refactor: move sourceset code out of tech

---

.gitignore
.npmignore
build/rollup.js
package-lock.json
package.json
src/js/index.js
test/require/webpack.js

This PR is to add HLS playback support built into video.js for 7.0 via videojs-http-streaming (shorthand VHS). VHS is the next major version of videojs-contrib-hls that removes HLS Flash playback and includes some experimental DASH support (hence the rename). The purpose is to improve the out-of-the-box experience for video.js and allow cross browser HLS compatibility.
The proposed changes are to have the standard video.js browser and module scripts contain VHS and provide an alternate video.js browser script that does not contain VHS.
Requires https://github.com/videojs/http-streaming/pull/69

feat: built-in HLS playback support

---

src/js/player.js
test/unit/sourceset.test.js

This was found due to the work done in #4660. Basically we reload the video element twice on every source with preload set to auto. This can potentially cause the same data to be downloaded twice.
* remove players call to load, as tech should handle preload on its own, and this is harmful for the html5 tech.

fix: let the tech preload auto on its own

---

README.md

docs: update readme to use the latest version of vjs.

Close #5066 docs: update readme

---

docs/guides/languages.md

It's currently printed red in the github markdown pages, aka syntax error:
https://github.com/videojs/video.js/blob/master/docs/guides/languages.md#json-format

Use valid json in translation example

---

src/js/player.js
src/js/tech/tech.js
test/unit/player.test.js
test/unit/tech/tech.test.js

SourceHandlers that use MSE have a problem: if they push a segment into a `SourceBuffer` and then seek close to the end, playback will stall and/or there will be a massive downswitch in quality. The general approach to fixing this that was discussed on slack was by setting the playback rate of the player to zero, buffering all that was required, and then restoring the previous playback rate. In my implementation, I've done this in the source handler (see: videojs/videojs-contrib-hls#1374).
From the video.js perspective, it should ensure that the UI reflects the buffering status and that the player API behaves like you'd expect -- that is to say, that it will fire `seeking` immediately after a call to `currentTime`, and it will fire `seeked`, `canplay`, `canplaythrough`, and `playing` when …

Queue playback events when the playback rate is zero

---

src/js/player.js
src/js/tech/tech.js
test/unit/player.test.js
test/unit/tech/tech.test.js

This is a clone of PR #5024 made against the 6.x branch.
Needed because the [related PR for contrib-hls](https://github.com/videojs/videojs-contrib-hls/pull/1374) will also link against vjs6.

Feature/queue playback events for zero playback rate (vjs6)

---

src/js/player.js
test/unit/player.test.js

fix: init inactivity checker not until first play event

---

src/js/control-bar/progress-control/seek-bar.js

Move all eventHandler bindings into a function.
This allows for easier customisation of the the seekbar component.
If you extend the seekbar component you can choose to override `setEventHandlers_` or keep it default.
If you do override `setEventHandlers_`  and call `super()` in the constructor, you get your own event handlers + the functionality provided by `Slider`
Currently extending slider and wanting different bindings, means either copy pasting from the  existing slider or writing a function to undo the bindings (which is not possible in this case since they are anonymous functions).

Moving seekbar event handler bindings into a function

---

src/js/tech/html5.js
src/js/tech/tech.js
test/unit/tech/html5.test.js

Adding an option to override native audio/video tracks.  This is being added to ease enabling and disabling it within https://github.com/videojs/http-streaming.  This is partly to make enabling/disabling native playback easier when integrating videojs/http-streaming into this project.
I'm in the process of adding tests.  I'd like eyes on this while I'm doing that to ensure that the implementation makes sense/if I'm missing anything that might break playback that I'm unaware of.
Adds 2 flags on the Html5 tech, `overrideNativeAudioTracks` and `overrideNativeVideoTracks` that can be set at any time.  The change will take effect any time the source is set.
One question I'm unclear on... what should the version compatibility be with video.js with this change?  I can modify things to be …

Add option to override native audio and video to html5 tech

---

src/js/player.js
src/js/tech/html5.js
src/js/tech/setup-sourceset.js
src/js/utils/filter-source.js
test/unit/sourceset.test.js

* `load` should always fire sourceset
* because `mediaEl.src` -> `mediaEl.removeAttribute('src')` -> `load()` should fire a sourceset
* initial sourceset should fire the correct source
* handle empty string sources
* sourceset should always fire an absolute source
* player cache should be absolute urls
* reset souceset before dispose and init sourceset after initial `sourceset`
* probably one more pr as some browsers support what I am calling "error recovery", which means that they will start watching for a source append after an error if there is currently no source.

fix: several source setting inconsistencies and slight refactor

---

src/js/player.js
test/unit/sourceset.test.js

Currently properties from `video-js` elements are not copied over to the `video` element when we do that. This means doing things like `videojsEl.src = ...;` will not carry over if they are done before player init. This also add `video-js` testing to our `sourceset` tests.

Fix: `video-js` el sourceset

---

src/js/tracks/text-track-settings.js

Remove spaces in the element IDs and ARIA attributes in the Captions Settings Dialog.
Fixes #4688 and #4884; supercedes 855adf3.
Remove spaces in the construction of IDs and aria-labelledby attributes in the Captions Settings Dialog constructor.

Fix IDs and ARIA attributes in Captions Settings Dialog

---

src/js/control-bar/control-bar.js

Remove unnecessary ARIA role on the Control Bar. Fixes #5134

Remove unnecessary ARIA role on the Control Bar. Fixes #5134

---

src/js/button.js
src/js/clickable-component.js
test/unit/button.test.js

Reduce the multiple-announcement by screen readers of the new name of a button when its text label changes. Partial fix to #5023
Move the `aria-live` attribute to the control text element within buttons, rather than on the whole button, so it is not affected by the change of the `title` attribute, only by the change of the control text.

Reduce the multiple-announcement by screen readers of the new name of a button when its text label changes. Partial fix to #5023

---

src/js/control-bar/progress-control/seek-bar.js

Under certain situations the value of `getPercent()` was returning `NaN` which lead to the error described in this ticket: https://github.com/videojs/video.js/issues/4960
Updated the `getPercent` function to return 0 instead of NaN. This is in accordance with the return value in the function's jsdocs.

fix: ensure aria-valuenow attribute in seek-bar is not NaN (#4960)

---

src/js/resize-manager.js
test/unit/player.test.js

Currently we don't have any way to check for/prevent issues like #5175. This adds a test to player/tech dispose to make sure nothing throws if the element is removed before dispose.

tests: do not throw on tech/player dispose

---

src/js/player.js
test/unit/video.test.js

When having a video-js embed with a class attribute, as part of the
changes to remove old IE support (#5041), we overwrote our addition of
the video-js class when it was missing. Instead, we want to make sure
that we don't override the class names again since they are already set
up correctly.
Fixes videojs/http-streaming#100

fix(player): video-js embed missing video-js class

---

README.md
docs/examples/elephantsdream/index.html
docs/examples/simple-embed/index.html

Since video.js V7 no longer supports IE9, remove the </track> tags from the doc/example HTML files, and while we're about it update those examples to use video.js v7.0 (from the CDN). Fixes #5165.
And then, while we're about that, update the README.md to also describe using v7.0.

Remove IE9 text track HTML markup in the doc/examples, and update to use video.js v7.0

---

src/js/player.js

Workaround for #4583 (JAWS+IE doesn't announce BPB or play button)
Add ARIA `role="application"` to the `<video>` element if the browser is IE, as recommended by @stevefaulkner in https://github.com/FreedomScientific/VFO-standards-support/issues/78#issuecomment-388327926.

Workaround for #4583 (JAWS+IE doesn't announce BPB or play button)

---

src/js/control-bar/audio-track-controls/audio-track-button.js
src/js/control-bar/playback-rate-menu/playback-rate-menu-item.js
src/js/control-bar/text-track-controls/chapters-track-menu-item.js
src/js/control-bar/text-track-controls/off-text-track-menu-item.js
src/js/control-bar/text-track-controls/text-track-button.js
src/js/menu/menu-item.js

Change menu items to ARIA role of "menuitemradio" when only one item can be selected can be selected (i.e. in the Captions, Subtitles, Descriptions, Chapters, Audio Tracks, and Rate menus). Fixes #5136.
Add an option of `multiSelectable` on `MenuItem` component; if `true`, the item is marked as a checkbox (`role="menuitemcheckbox"`), otherwise the item is marked as a radio button (`role="menuitemradio"`). All existing menu items, except the Captions Settings Menu, will be marked as radio buttons (the Settings Menu item has `role="menuitem"`), as will any components which extend the existing components and don't set 'multiSelectable'.

Change menu items to ARIA role of "menuitemradio" when only one item can be selected

---

src/js/control-bar/audio-track-controls/audio-track-button.js
src/js/control-bar/playback-rate-menu/playback-rate-menu-item.js
src/js/control-bar/text-track-controls/chapters-track-menu-item.js
src/js/control-bar/text-track-controls/off-text-track-menu-item.js
src/js/control-bar/text-track-controls/text-track-button.js
src/js/menu/menu-item.js

Change menu items to ARIA role of "menuitemradio" when only one item can be selected (i.e. in the Captions, Subtitles, Descriptions, Chapters, Audio Tracks and Rate menus).
Fixes #5136.

fix(menus): change ARIA role of menu items for better screen reader support

---

src/js/player.js

Freedom Scientific's recommended workaround for JAWS + IE not announcing the first button after a video element which doesn't have its own native controls (See FreedomScientific/VFO-standards-support#78).

fix(player): ensure that JAWS+IE announces the BPB and play button

---

rollup.config.js

This fix moves the main `umd` bundle that we use for dev work to the front. Currently the `cjs`/`es`  bundles fail to build on the second watch. This fixes just makes it so that the main `umd` bundle will still work during watch. It's not great but outside of fixing the bug in rollup on our own I think its a good temporary fix for now.

ignore: a terrible rollup watch fix for development

---

src/css/components/_progress.scss
src/js/slider/slider.js

A proposed solution for #4650  
Instead of calling `preventDefault()` on `touchstart` in Chrome, set `touch-action: none` style on progress control to prevent unintended scrolling.

fix: suppress console warnings in Chrome on mobile when scrubbing progress slider

---

src/css/components/_subs-caps.scss

Proposed solution for #4758 
Currently, if longer captions labels are used the SubsCaps menu gets all messed up in IE11/Edge. This occurs due to the menu size is not adjusted correctly not taking into consideration the CC icon. This, as a result, causes the captions items not to fit in the menu and because they end up too wide and the menu has `overflow: auto` style,  the horizontal scrollbars show up and cause the menu not to render correctly.
Do not position the CC icon absolutely.

fix: menu sizing when using longer caption labels

---

src/js/player.js
test/unit/player.test.js

The changes to source caching in #5156 introduced a regression where the source options were no longer available to plugins. This PR makes sure the cached source object retains any source options passed along.
Merge the entire source object into the cached source
-----
Please let me know if you think I should check something other than `player.currentSource()` for the unit test.

fix: make sure source options are passed through

---

.npmignore

Excludes zip file with souces from being published to npm.
This closes videojs/video.js#5248
Adds dist/video-js-*.zip pattern to .npmignore file

Add zip file to npmignore

---

src/js/mixins/evented.js
test/unit/mixins/evented.test.js

I don't think there's an issue for this (I looked), but the bug is that objects using the new-ish `evented` mixin cannot listen to the `window` object, preventing things like:
```js
component.on(window, 'scroll', throttledListener);
```
This fixes that so anything that's a native `EventTarget` works.
Allow any native `EventTarget` to be a listening target.

fix: Allow evented objects, such as components and plugins, to listen to the window object in addition to DOM objects.

---

src/js/tracks/text-track-display.js
test/unit/tracks/text-track-display.test.js

When providing the TextTrackDisplay component with track settings overrides, currently colour codes with only three digits are supported. I would like to make this more flexible by also allowing six digit hex codes.
CC @arski 
Updates the TextTrackDisplay component's `constructColor` function to accept and process both three and six digit colour codes.

Extend the constructColor function to handle 6 digit hex codes

---

build/grunt.js
package-lock.json
package.json
postcss.config.js

`autoprefixer` cuts out any vendor prefixes that we don't need. It would probably be better to run this on the source files, but we cannot since we are working with sass. So for now we can run it as a "minification" step. 
* New size: `9514` bytes gziped
* Old size: `9829` bytes gziped

feat: run autoprefixer on css

---

src/js/player.js

Found some code that looks like it was added for safari 5 and Chrome 15 support. We should probably test to make sure we don't need it, but it would seem like we don'

refactor: removed old bug work-around code

---

src/js/tech/html5.js
src/js/utils/browser.js

`IS_CHROME` in browser module currently returns `false` for iOS Chrome. 
Include iOS Chrome UA string pattern when detecting Chrome.

feat: include iOS Chrome UA pattern when detecting Chrome in browser module

---

.github/move.yml
.github/stale.yml

Enable [stale](https://probot.github.io/apps/stale/) and [move](https://probot.github.io/apps/move/) [probots](https://probot.github.io/).

chore: enable move and stale probots

---

src/js/utils/browser.js

Fixed the Issue with the code proposed
Changed the TOUCH_ENABLE constant initalization
Now evaluate true with Windows 10 with touch screen and Browser: Chrome 50 and IE11, Edge and also with Windows Phone 10 and Edge.
With a Windows 10 computer without touch screen it evaluate false as it should.

Fix Issue #3306

---

src/js/player.js

Handling possible exception when calling `player.autoplay()` so that the video-playing fallback implementation should work.
If the source is not loaded, `player.play()` returns `undefined` on
Firefox and Edge.
This causes an exception when `player.autoplay()` called.
With this fix, player will not make an exception and the fallback
(Retrying video-play after loading video) will be enabled.
Reproduced on Firefox(Mac) and Edge.
Not reproduced on Chrome(Mac) and Safari
- Reproducing code
```html
<!DOCTYPE html>
<html>
<head> 
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<link href="http://vjs.zencdn.net/7.0/video-js.min.css" rel="stylesheet">
<script src="./video.js"></script>
</head>
<body>
<video id="test-video" class="video-js vjs-default-skin" controls>
<source …
```

fix: autoplay throws 'undefined promise' error on some browsers.

---

src/js/control-bar/fullscreen-toggle.js

In the event that fullscreen is unavailable, such as when the player is in an iframe that does not have the allowfullscreen attribute, the fullscreen button will be disabled. This fixes #5290
fullscreen-toggle.js will check if fullscreen is enabled, and if not, set the button to "disabled"

Fullscreen button will be disabled if fullscreen is unavailable

---

src/js/component.js
test/unit/component.test.js

Our setTimeout and requestAnimationFrame methods added dispose handlers so that they get cancelled if the component is disposed before they get a chance to run. However, we were only clearing out these dispose handlers if we cleared the timeout or the rAF manually. Instead make sure that we remove the dispose handler when it is no longer needed.
Fixes #5199.

perf: setTimeout and requestAnimationFrame memory leak

---

src/js/mixins/evented.js
test/unit/mixins/evented.test.js

This reverts commit 7fd29b4f18320ee6c7daee6a9110c7afb72695c5.
With this change, playing back HLS content via VHS caused an infinite
event loop to be printed out. See issue #5281

revert: fix: Allow evented objects, such as components and plugins, o listen to the window object in addition to DOM objects. (#5255)

---

docs/guides/middleware.md
src/js/tech/middleware.js
test/unit/tech/middleware.test.js

Adding tests first and implementation will be available after tests fail.
setSource is useful if you care to be fiddling with the source or doing some work depending on what source is set. However, sometimes, you don't need a setSource and want the middleware to always be selected.
Now, if setSource is missing, it will implicitly be included in the middleware chain.

feat(middleware): make setSource be optional

---

src/js/player.js

Add a isResetting flag to loadTech, and unloadTech, so not to copy text tracks.
When reset is called, text tracks are being kept. By adding the appropriate flag, we keep text tracks, but not when we are resetting the player.
https://github.com/videojs/video.js/issues/5140
Added a isResetting flag to the loadTech_  and unloadTech_ methods which controls text tracks copy.

Player reset text track unwanted copy

---

src/js/event-target.js
src/js/tracks/text-track-list.js
test/unit/event-target.test.js
test/unit/tracks/text-track-list.test.js
test/unit/tracks/text-tracks.test.js

Trigger the `change` event on the next tick. This means that multiple changes to a track's mode will only result in a single `change` event on its associated TextTrackList rather than 3 events as it may be currently.
Fixes videojs/video.js#5159.

feat: async `change` events in TextTrackList with EventTarget#queueTrigger

---

src/css/components/_progress.scss

Changed tooltips position from relative to absolute 
Issue videojs/video.js#5354

Changed position to absolute

---

src/js/player.js

It's possible for us to get a blob url for sourceset, but when we do, we
shouldn't update the source caches with that information.

fix(sourceset): ignore blob urls when updating source cache

---

src/js/player.js
test/unit/player.test.js

Always return a Promise from play when we have a Promise object.
Fixes videojs/video.js#3927

feat: always return a promise from play, if supported

---

src/js/resize-manager.js
src/js/utils/fn.js

It's possible that ResizeManager will trigger its debounce handler but
then get disposed before the handler runs. This can cause tests to fail,
so, instead, we should cancel the debounce when ResizeManager is
disposed.

fix: add debounced.cancel and use it in ResizeManager

---

src/js/player.js

Change the constant used in the techId prop to the camelCased version, this will result on consistent id when loadTech_() is executed.
this closes videojs/video.js#5411 
change line 948 to use camelTechName

fix: use consistent id after loadTech_()

---

src/js/resize-manager.js

Noticed this when working on the `v6` version of the test fixes. I think this code may be broken right now.

fix: typo in resize manager

---

src/js/tracks/text-track.js
test/unit/tracks/text-track.test.js

We were only triggering cuechange events if a metadata track started out as not disabled or only when setting the mode to 'showing'
Fixes #5308

fix(text-tracks): cuechange handler not triggering correctly

---

src/js/tracks/text-track-display.js

On mobile devices, when changing orientation, or if the player gets resized, the captions won't update to reflect the new orientation or player size. However, they do get updated the next time they are redrawn. Instead, we should redraw the captions whenever `orientationchange` and `playerresize` get triggered.

fix(text track display): update on playerresize and orientationchange

---

src/js/extend.js
src/js/player.js
src/js/plugin.js
src/js/tech/middleware.js
src/js/utils/browser.js
src/js/utils/computed-style.js
src/js/utils/dom.js
src/js/utils/events.js
src/js/utils/fn.js
src/js/utils/format-time.js
src/js/utils/log.js
src/js/utils/merge-options.js
src/js/utils/time-ranges.js
src/js/utils/url.js
src/js/video.js
test/unit/extend.test.js
test/unit/tech/tech.test.js

**Reviewers:** `?w=1` is recommended. 😄 
In helping someone with an issue, I realized our API docs, especially for properties of the `videojs` function, were really bad. And this is extra-bad because that's the API surface that people actually use in 99% of cases.
There is some limitation here due to the fact that we're using `videojs` (and other things) both as a function and a namespace; so, while the docs are not perfect after these changes, we actually have the majority of the public API documented. While functions-as-namespaces [is supported in JSDoc 3.5](https://github.com/jsdoc3/jsdoc/issues/955#issuecomment-313829149), our template does not seem to be able to handle it.

docs: Update JSDoc comments, so core API docs for the videojs function are accurate.

---

src/js/player.js

Prevent video.js from throwing errors when reloading the tech a after using reset().
This was already fixed for version 7 here: https://github.com/videojs/video.js/pull/5415
Fixes #5411 for 6.x
Use `camelTechName` instead of `titleTechName`

fix: Set correct techName after call to reset() (6.x)

---

src/js/player.js
test/unit/player.test.js

Like fluid mode, you can enable it with the class or by calling the fill
method. Calling fill() will turn off fluid mode and calling fluid() will
turn off fill mode.
Fluid mode takes precedence over fill mode currently.

feat(fill): make vjs-fill a player mode

---

docs/examples/elephantsdream/index.html
docs/examples/simple-embed/index.html
docs/guides/options.md
sandbox/combined-tracks.html.example
sandbox/descriptions.html.example
sandbox/flash.html.example
sandbox/index.html.example
sandbox/language.html.example
sandbox/plugin.html.example
sandbox/responsive.html.example
src/css/components/_adaptive.scss
src/css/components/_control-bar.scss
src/js/component.js
src/js/player.js
test/api/api.js
test/unit/player-breakpoints.test.js
test/unit/test-helpers.js

Closes videojs/video.js#4371 
This adds a `breakpoints` option. By default, this option is `false` meaning this is an opt-in feature.
When passing `true`, it will use a default set of breakpoints. Or custom breakpoints can be passed if users do not like our breakpoints (or previously-existing style decisions).
* Add `breakpoints` option.
* Adds some new (currently unused) classes: `vjs-layout-medium`, `vjs-layout-large`, `vjs-layout-x-large`, and `vjs-layout-huge`.
* Add `updateCurrentBreakpoint` and `currentBreakpoint` methods to the player.
* Update `css/components/_adaptive.scss`
* In cleaning up sandbox a bit, I noticed several appearances of `vjs-default-skin` which was no longer used anywhere. Removed it everywhere.
* Add `sandbox/responsive.html.example`

feat: Add breakpoints option to support toggling classes based on player width.

---

README.md

Refer to minified versions of the JS and CSS files from `unpkg` and `cdnjs`, and add notes about versions. Remove unnecessary quoting in the README, and clarify the comment about v7 (and later) not having the Google Tracking pixel.
Edits to the README.md file

Update README.md to refer to minified versions of JS and CSS, and improve general layout and minor nits

---

docs/guides/layout.md
docs/guides/options.md
sandbox/responsive.html.example
src/js/player.js
test/unit/player-breakpoints.test.js

Follow-up for #5471 
This makes the `breakpoints` option and `setBreakpoints()` method clearer and introduces the `responsive` option and `setResponsive()` method, which will turn on the breakpoints.
The return value of `currentBreakpoint()` was simplified to only ever return a string (empty if none).
Also, added convenience methods: `isResponsive()`, `getBreakpointClass()`, and `currentBreakpointClass()`.

feat: Add responsive option, which enables breakpoints support.

---

src/js/tracks/text-track-settings.js

The default button type is "submit" which triggers a form submit. Thus
if videojs is embedded in a form element the button triggers a form
submit.
This is the same problem with same solution as discussed in https://github.com/videojs/video.js/issues/2470

fix: Do not use default button type.

---

src/js/player.js

Docs were not clear that it removed the text track when resetting a video.
Updating docs around `reset()` method in player.js

docs(player.js): make reset() method more clear

---

package-lock.json
package.json
rollup.config.js

So `rollup-plugin-filesize` is minifying all of our code in video.js, then throwing it out to report a minified file size. I think we should just get rid of this plugin because there isn't a great way to turn it off
initial builds for each build target go from ~12s -> 6s and rebuilds go from 6s -> 1s
Closes #5506

chore: remove rollup filesize plugin to double build speed

---

rollup.config.js

Currently rollup watch is broken for most "module" (cjs/es) builds. All it took was some externals/globals to get it to work correctly.

chore: fix rollup watch bulid with globals/externals

---

src/js/player.js
test/unit/player.test.js

Sometimes the `vjs-waiting` class is removed prematurely after the player gets into a waiting state. This removes the graphic waiting spinner while the player is still waiting. To see this behavior on Chrome:
1) Go to https://videojs.github.io/http-streaming/
2) Open the console
3) Enter:
```
player.on('waiting', () => console.log('waiting'));
player.on('timeupdate', () => console.log('timeupdate: ' + player.currentTime()));
player.play();
```
4) Click "Offline" in the network tab
The console logs `timeupdate` events of the same time sandwiching a `waiting` event, e.g.:
```
...
timeupdate: 49.675262
timeupdate: 49.812381
waiting
timeupdate: 49.812381
```
This PR waits to remove the `vjs-waiting` class until the time changes on `timeupdate` events.

Don't remove vjs-waiting until time changes

---

build/grunt.js

A temporary solution to enable es6 import of the language files.
Related issue: #5092
```es6
import es from 'video.js/dist/lang/es.json';
videojs(element, {
language: 'es',
languages: {
es
}
});
```
If you use typescript, you need to add the following compilerOptions to the tsconfig:
```json
"resolveJsonModule": true,
"esModuleInterop": true,
"allowSyntheticDefaultImports": true
```
Add a grunt task to copy all json files to dist/lang directory.

feat(lang): es6 import of a language file

---

src/js/tracks/text-track-display.js
test/unit/tracks/text-track-display.test.js

fix(tracks): don't select tracks based on user pref if no langauge is set

---

src/js/media-error.js

Fixed as was specified in the issue.
Changes as specified. 
- [ X ] Feature implemented / Bug fixed

Correct error type number matches

---

index.html

Using a relative url will make this page work whether run via the server
of npm start or a third party server that serves other things as well.

chore: use relative urls in index.html

---

src/js/control-bar/time-controls/duration-display.js
src/js/player.js

This resets the duration display when a new media item is loaded with `preload` set to 'none', and allows the duration NaN or 0 to update the duration display.
Fixes [videojs/video.js#3927](https://github.com/videojs/video.js/issues/5347)

fix: duration reset, and allow duration NaN or 0 for duration display

---

src/css/components/_captions-settings.scss
src/js/tracks/text-track-settings.js

* Makes reset/done buttons take up two columns and centers them
* Makes the width of all selects the same 
* When the caption settings are open on a small player, move to a single column layout. Currently there is a horizontal scroll bar.

feat: responsive caption settings

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md
docs/guides/faq.md

Use a codepen template for the starter template that includes a 7.x
player, video-js element, and a JavaScript created player.
The template is https://codepen.io/gkatsev/pen/GwZegv?editors=1010#0
Fixes #5562

docs: update starter template

---

package-lock.json
package.json

Not having `lint-staged` or `npm-merge-driver-install` has been bugging me, they make the workflow a lot quicker when committing or merging package-lock changes. It also allows us to only lint the partially staged changes that we are working on during commit/push.

chore: Lint on pre-commit with lint-staged, use npm-merge-driver

---

package-lock.json
package.json

event-stream had unknown code added to it, npm-run-all 4.1.5 was updated
to fix that. https://github.com/dominictarr/event-stream/issues/116 for
more information

chore(package): update npm-run-all to 4.1.5 to remove event-stream
