videojs/video.js

src/js/tracks/text-track-display.js, test/unit/tracks/text-track-display.test.js
This is a follow-up to [this fix in VHS](https://github.com/videojs/http-streaming/pull/239), after which default in-manifest subtitles were still not being correctly enabled. The reason is because video.js's text track [preselection](https://github.com/videojs/video.js/blob/master/src/js/tracks/text-track-display.js#L105) logic was running before the media groups were set up in VHS.
Text track preselection should happen on `'loadedmetadata'` instead of `'loadstart'`. According to the HTML [spec](https://html.spec.whatwg.org/multipage/media.html#event-media-loadedmetadata), text track data is available on `'loadedmetadata'`, so we should be waiting until then to make preselection decisions.
Test content w/ default subtitles: https://bitdash-a.akamaihd.net/content/sintel/hls/playlist.m3u8
=> fix: default subtitles not enabled

COLLABORATOR_GUIDE.md, CONTRIBUTING.md, docs/guides/components.md, docs/guides/languages.md, docs/guides/layout.md, docs/guides/options.md, docs/guides/text-tracks.md, docs/translations-needed.md, index.html, package.json, sandbox/combined-tracks.html.example, sandbox/flash.html.example, sandbox/focus-visible.html.example, sandbox/index.html.example, sandbox/live.html.example, sandbox/liveui.html.example, sandbox/vertical-volume.html.example
Since grunt was removed in https://github.com/videojs/video.js/pull/5592, we should update our docs to stop referring to grunt and to refer to the new ways of doing things. This includes in things like the sandbox examples.
Also, update the top level index.html and the docs with `npm run docs:fix`.
=> docs: remove grunt and update usage of build scripts

src/js/control-bar/progress-control/seek-bar.js, src/js/live-tracker.js, test/unit/live-tracker.test.js
1. Make sure that we seek to live playback on the first timeupdate
1. Do not report that we are not live before playback has started (a timeupdate has been seen)
1. Prevent negative seekable increments
1. We can seek past the `seekable` value in the video element, so we use that to seek to live, rather than waiting for a seekable end change.
=> fix: liveui tweaks

src/js/control-bar/time-controls/time-display.js, src/js/control-bar/time-controls/time-divider.js
The desired behavior when navigating any of the TimeDisplay components (current time, duration, remaining time) with the arrow keys with a screen reader is for the singular parent div to receive focus, and the reader should announce the text of each child span in order, ex. "Current Time 0:17" and "Duration 1:10". This is how it works when using JAWS. However, with VoiceOver each individual child span element receives focus and the contents are announced separately:
[Screenshot of 1st span - control text](https://user-images.githubusercontent.com/20497452/49480053-3e5a0280-f7f3-11e8-9152-22956dc3953c.png)
[Screenshot of 2nd span - numerical time](https://user-images.githubusercontent.com/20497452/49480054-3e5a0280-f7f3-11e8-84f3-7307256833f7.png)
According to the ARIA spec (see …
=> fix: current time and duration display accessibility with VoiceOver

src/js/control-bar/progress-control/load-progress-bar.js, src/js/control-bar/progress-control/play-progress-bar.js, src/js/control-bar/progress-control/time-tooltip.js
Fix the hidden Control Text (intended for screen reader users) in the Progress Bar, which never gets updated by loading or playback. Fixes #5251.
* Update the Control Text in the load-progress-bar during loading
* Remove unnecessary Control Text from the play-progress-bar
* Hide the time-tooltip feature from Assistive Technology using ARIA.
=> Fix hidden Control Text in Progress bar (Fixes #5251)

package-lock.json, src/js/control-bar/progress-control/load-progress-bar.js, src/js/control-bar/progress-control/seek-bar.js, src/js/control-bar/progress-control/time-tooltip.js, src/js/control-bar/seek-to-live.js, src/js/player.js, test/unit/controls.test.js, test/unit/player.test.js
* Added a test that should catch assertions that happen when a child is turned off on the player.
* About to add a fix for the current assertion on liveTracker/seekToLive.
=> test: add a test to check various children set to false

src/js/player.js, test/unit/player.test.js
Solves videojs/video.js#5258 
Adds two event handlers for 'mouseenter' and 'mouseleave' events on the control-bar.
When the 'mouseenter' is triggered the inactivityTimeout is set to 0 and on 'mouseleave' is set to the default value (2s).
Expected behavior: 
* cursor stops inside control bar -> sets timeout 0s so nothing happens
* cursor leaves player bounds -> sets timeout 2s before going inactive
=> fix: Control-bar autohide when cursor placed over it #5258

src/css/components/_loading.scss
This PR fixes the animation shorthand order.
Animation shorthand order can be found here:
https://alligator.io/css/animation-shorthand/
https://css-tricks.com/almanac/properties/a/animation/
name | duration | ease-in-out | delay | iteration-count | backwards
BEFORE
```css
.vjs-seeking .vjs-loading-spinner,
.vjs-waiting .vjs-loading-spinner {
display: block;
animation: 0s linear 0.3s forwards vjs-spinner-show ;
}
```
AFTER
```css
.vjs-seeking .vjs-loading-spinner,
.vjs-waiting .vjs-loading-spinner {
display: block;
animation: vjs-spinner-show 0s linear 0.3s forwards;
}
```
This will fix css minimization issues when using https://github.com/webpack-contrib/mini-css-extract-plugin#minimizing-for-production.
**incorrect vs correct**  css syntax
Please list the specific changes involved in …
=> Fix css animation order

src/js/player.js, src/js/utils/mimetypes.js, test/unit/player-loadmedia.test.js, test/unit/player.test.js
This adds methods for loading media into a player.
- `loadMedia` will set source, poster, and text tracks. It will create an `artworks` array for uses with the `MediaSession` API.
- `getMedia` will return a clone of the media object.
Fixes #4342
=> feat: Add loadMedia and getMedia methods

src/js/player.js, test/unit/player.test.js, test/unit/tech/tech-faker.js
Fixes videojs/video.js#5675 
This PR will fully clear the `player.cache_` when calling `Player#reset`.
=> fix: make sure sources, volume, and playback rate are reset along with the player

src/js/control-bar/time-controls/remaining-time-display.js, src/js/control-bar/time-controls/time-display.js, src/js/utils/fn.js, src/js/utils/url.js
Fixes issue videojs/video.js#5168  @gkatsev 
Remaining time is now a positive value by it's own and the negative sign is added decoratively.
- Removed negative sign in when returning the remaining time
- Added the negative ('-') sign to the number's container and make it 'aria-hidden' so screen readers can't read it
=> Move the "-" in remaining-time-display.js so it is not announced by screen readers. Fixes #5168

src/js/fullscreen-api.js, src/js/player.js
Before the fullscreen API was un-prefixed, we listened to triggered a
`fullscreenchange` event on the player manually. This worked fine
because a prefixed `fullscreenchange` event was triggered on the player
element itself. But when it was unprefixed, we ended up with two events
now, the unprefixed event and the one we triggered.
Instead, we should listen the event the browser supports and re-trigger
it as the unprefixed event as necessary.
We also make sure that the handler gets calls when the document level
fullscreenchange handler gets called so that it is cancelled properly.
Fixes #5685.
=> fix(fs): make sure there's only one fullscreenchange event

src/js/control-bar/progress-control/seek-bar.js
The seekbar is disabled if the seekable end is Infinity and re-enabled
when it isn't. Instead, we should only disable if seekable end is
Infinity and re-enable only if we disabled for the seekable end.
This auto disabling and re-enabling, without this fix, caused issues
with disabling the progress control since the seekbar got re-enabled.
=> fix(seekbar): don't disable if live tracker's seekable is infinity

src/js/component.js, test/unit/component.test.js, test/unit/menu.test.js
A child component may have been assigned to another
parent before assigning that child component to the
new parent via "addChild" method. In this case, the
original parent should remove the child then it can
be safely added back to the new parent. This commit
will keep the parent's "children_" and its DOM
element's child nodes in the consistent state.
Remove the specific child component from the old parent component before adding the child component to the new parent
=> fix: remove child from old parent when moving to new parent via addChild

src/js/control-bar/text-track-controls/text-track-menu-item.js, test/unit/control-bar/text-track-controls/text-track-menu-item.test.js
While investigating a non-public issue, I happened to notice that metadata tracks were being disabled when switching captions languages. Upon investigation, I found [this code](https://github.com/videojs/video.js/blob/175f77325346af9ec5fa7f090eba8be2076a54e2/src/js/control-bar/text-track-controls/text-track-menu-item.js#L113-L119), which is the culprit. It will disable any track that's not the selected track.
Instead of disabling all tracks when switching, only disable tracks of the appropriate kind(s).
=> fix: TextTrackMenuItem components should not disable text tracks of different kind(s).

COLLABORATOR_GUIDE.md, CONTRIBUTING.md, README.md, docs/examples/elephantsdream/index.html, docs/examples/simple-embed/index.html
Some links were still using http (even though they redirect to https).
=> use https links in documentation

src/js/menu/menu-button.js
Currently menu titles are not components, but Dom elements instead.  This is an issue specifically for existing code such as in [src/js/menu/menu.js:114](https://github.com/videojs/video.js/blob/3d093ede98f2ad6204ff44c9631b0aa18bbf0cc5/src/js/menu/menu.js#L114,L115) where each child element is expected to be a videojs component (`element.el()`) though when a title is provided to `MenuButton`, it is created as a Dom element in `src/js/menu/menu-button.js:111`
Relevant issue already exists, though it has only popped up as an issue for me after VJS 7.x updates:
videojs/video.js#3612 
```
/**
* Called when a `MenuItem` loses focus.
*
* @param {EventTarget~Event} event
*        The `blur` event that caused this function to be called.
*
* @listens blur
*/
handleBlur(event) {
const relatedTarget …
```
=> fix(menu-button): make menu button title a component

src/js/resize-manager.js, test/unit/resize-manager.test.js
The ResizeManager's iframe element is able to be focused via tabbing, which results in a bad user experience for users that rely on a screen reader to navigate the video and its sibling elements. The fix is to set the tabIndex to "-1", and the aria-hidden property to `true` for good measure. Confirmed the fix by spinning up a local server and attempting to tab to the resizeManager's iframe element. This was possible prior to the fix, and not possible after the fix. In addition, I added to the existing resizeManager unit test.
=> [A11y Fix] - Ensure resizeManager is not focusable via tab

docs/guides/troubleshooting.md
Updated the formats information in the troubleshooting guide to account for http-streaming being included in Video.js 7, and added detail to some sections.
Added some caniuse.com links for reference.
=> docs: Update format information

src/js/player.js
We need to define the cache for `inactivityTImeouot` before the `mouseenter` event, because if you do play on the `controlBar` for example and go out, the actual `mouseenter` event of it never gets triggerd, and so the cache is gonna be always undefined. 
It's a really visible bug when you have a custom player with the control-bar all the way bottom (-40px) and you set a `inactivityTimeout: 0`, it gets overriden by the undefined and gets hidden always.
=> Set cache before 'mouseenter' event for inactivityTimeout

src/js/player.js, test/unit/tech/tech-faker.js
In Safari, if we call play early and we are going to be waiting till
loadstart, it's possible this will take too long for the user activition
flag to still be available. In this case, we should call load() on the
player to prime the video element so for when loadstart happens.
=> fix: if play is delayed till loadstart, call load

src/js/video.js
Videojs currently relies on the document object from the window that videojs script is instantiated in, in order to determine if the element it will use for initialization is attached to the dom. The method used to determine dom attachment is incorrect. This fixes that method.
document.contains(el) will only check if el is contained within that one document. This causes problems for elements in iframes.
Instead, use the element's ownerdocument instead of the global document. Additionally, check that the document in question has a default view. If the document is no longer attached to the …
=> fix warning - element supplied is not included in the DOM

package-lock.json, src/js/player.js, test/unit/reset-ui.test.js
The resetProgressBar_ method was calling 'updateContent' on the durationDisplay and remainingTimeDisplay controls without checking to make sure they exist
Bug report here: https://github.com/videojs/video.js/issues/5838
- Ensure that the `durationDisplay` and `remainingTimeDisplay` controls exist prior to calling `updateContent`
- Added a test to ensure that no error is thrown when the above controls don't exist in the controlBar
=> Fixes #5838. Ensure that controls exist prior to calling updateContent in resetProgressBar_

src/js/video.js
PR #5831 made the not-in-DOM warning work with elements from other
documents. This works in modern browsers but IE11 doesn't include a
contains method on the document. Instead, we should check to see if the
body contains the element.
=> fix: use ownerDocument.body.contains for IE11

src/js/control-bar/progress-control/seek-bar.js
SeekBar ends up adding two extra `timeupdate` handlers for the `update` function.
1. One is added in `Slider` via the `playerEvent` on `SeekBar`s prototype. This one may be worse because it will be added on the original update function before we throttle it.
2. The other is just added in `setEventHandlers_`.
=> fix: Remove `playerEvent` and extra `timeupdate` handler in SeekBar

src/js/resize-manager.js, src/js/utils/events.js
Right now we leak one event handler in DomData on every player dispose. Funnily enough we are leaking a dispose event handler from the evented mixin: https://github.com/videojs/video.js/blob/master/src/js/mixins/evented.js#L395
=> fix: trigger dispose on resize manager

test/unit/close-button.test.js, test/unit/component.test.js, test/unit/controls.test.js, test/unit/event-target.test.js, test/unit/events.test.js, test/unit/menu.test.js, test/unit/mixins/evented.test.js, test/unit/mixins/stateful.test.js, test/unit/modal-dialog.test.js, test/unit/player-breakpoints.test.js, test/unit/tech/html5.test.js, test/unit/tech/tech-faker.js, test/unit/tech/tech.test.js, test/unit/tracks/audio-track-list.test.js, test/unit/tracks/audio-track.test.js, test/unit/tracks/audio-tracks.test.js, test/unit/tracks/html-track-element.test.js, test/unit/tracks/text-track-controls.test.js, test/unit/tracks/text-track-display.test.js, test/unit/tracks/text-track-list-converter.test.js, test/unit/tracks/text-track-list.test.js, test/unit/tracks/text-track.test.js, test/unit/tracks/text-tracks.test.js, test/unit/tracks/track-baseline.js, test/unit/tracks/track.test.js, test/unit/tracks/video-track-list.test.js, test/unit/tracks/video-track.test.js, test/unit/tracks/video-tracks.test.js
Using `DomData.elData` contained a ton of improperly cleaned up objects in tests this pull request fixes that.
=> tests: memory leak fixes in tests

src/js/player.js
Call `off` on `TrackList`s when the player is disposed so that we don't leak memory via `DomData.elData`
=> fix: turn off all track list listeners on dispose

src/js/control-bar/progress-control/seek-bar.js
The seek bar updates on a 30ms interval to have a nice, smooth transition as time ticks forward. Unfortunately, IE11 has some performance issues with interval when the document is hidden. This doesn't appear to be an issue when using setTimeout but using a setTimeout was causing the play progress to appear very jerky in comparison.
Instead, we should just not update the play progress when the document is hidden. Besides solving the issue in IE11, it makes sense to do as no one could be seeing the progress bar. In addition, update() is now a no-op if the seek-bar element isn't visible.
Fixes #5575
=> perf(seek-bar): don't update play progress when document is hidden

src/js/resize-manager.js, src/js/tracks/audio-track-list.js, src/js/tracks/text-track-list.js, src/js/tracks/video-track-list.js, test/unit/tracks/text-track-list-converter.test.js, test/unit/tracks/text-tracks.test.js, test/unit/utils/dom-data.test.js
* These where caused because we were not always able to clean up `resize` on the `ResizeManager`s iframe contentWindow after
* Native tracks on safari do not have an `off` so we have to remove our event listeners manually.
Fixes #5878
=> perf: Fix memory leaks in safari, edge, and ie

src/js/tracks/audio-track-list.js, src/js/tracks/video-track-list.js, test/unit/tracks/audio-track-list.test.js, test/unit/tracks/video-track-list.test.js
Fixes #5887 
~~trying to find out why the unit tests didn't catch this, 🤔~~ Tests fixed
=> fix: audio and video track changes

src/js/modal-dialog.js
The ModalDialog's `pauseOnOpen` option is not documented.
Adds API docuemntation.
=> docs: document ModalDialog's pauseOnOpen option

src/js/player.js, test/unit/autoplay.test.js
Based on #5895 
1. Restores the old value of `muted` on a `play-terminated` event.
2. Adds more autoplay checks, especially around the new `play-terminated` behavior 
3. Simplifies `manualAutoplay_`, Basically we were trying to support, and not support promises at the same time, which did not make much sense because:
a. `manualAutoplay_` will only work as expected if we have access to promises.
b. `play()` always returns a promise, even if the tech doesn't so we can rely on a promise being returned.
c. we should only bother with `muted` autoplay if `muted` is not already `true`.
I also noticed that there is a small chance for `muted` to be set to `true` after `manualAutoplay_` runs and then be set back to `false` once it fails. Do we want to try to handle that?
=> fix: Restore muted on autoplay middleware terminate

src/css/components/_adaptive.scss
We received a report that muted autoplay players using the new responsive breakpoints could not be unmuted at small sizes. This was due to an oversight in the initial implementation of responsive mode.
=> fix: Always show the mute button by default in responsive mode.

src/css/components/_adaptive.scss
This follows on from #5914 by hiding the progress control and showing the subs-caps buttons in `x-small` players when the new `liveui` option is used.
No change is necessary for the default `live` treatment because it hides the progress bar already.
**NOTE:** This is currently based on `fix/always-show-mute-button` branch!
=> fix: Hide the progress control and show the subs-caps button when using Live UI at extra small size.

src/js/player.js
We have gotten a report (at Brightcove) of an issue where a disposed player could potentially leave behind the document keydown listener for the new-ish hotkeys feature.
This led me to realize there could be other cases where document-level listeners are left behind. For example, if the player is somehow disposed while in fullscreen, it could leave behind those listeners.
Even though we haven't had reports of any other listeners being left, it seems responsible to make sure they're cleaned up!
* Remove all document-level listeners on player dispose.
=> fix: Explicitly remove all document-level listeners on player dispose.

lang/de.json
Just a fix for a small typo in German (de) translation.
=> Fix typo in de translation

src/js/player.js
Bug fix that prevented the control bar from being hidden when progress bar was tapped on on mobile (not seeked on, and only after control bar was already showing).
This was due to a mouseenter event firing (on mobile) that would set the `inactivityTimeout = 0` right before the below bit of code was executed.
```
const timeout = this.options_.inactivityTimeout;
if (timeout <= 0) {
return;
}
// In <timeout> milliseconds, if no more activity has occurred the
// user will be considered inactive
inactivityTimeout = this.setTimeout(function() {
// Protect against the case where the inactivityTimeout can trigger just
// before the next user activity is picked up by the activity check loop
// causing a flicker
if (!this.userActivity_) {
this.userActive(false);
}
}, timeout);
```
Ensures the …
=> Fix bug preventing control bar from hiding on mobile

src/js/player.js, src/js/tech/middleware.js, test/unit/autoplay.test.js, test/unit/play.test.js, test/unit/player.test.js, test/unit/tech/middleware.test.js, test/unit/test-helpers.js
Currently when a middleware terminates a call to play, we resolve the promise right away, event though that promise is not resolved. We should instead resolve the promise on the next call to play that works.
Doing this turned out to be a bit tricker than first anticipated. I added detailed tests that make sure that the play `retval` is resolved in a slew different scenarios. I think that we will still need another pull request to handle `play-terminate` events in the `manualAutoplay_` function, but this pull request was getting to big already.
=> fix: Correctly resolve play on middleware terminate

src/js/player.js, src/js/utils/browser.js
Similar to #5173, this PR adds role='application' to the video element on Chrome on Windows, to work around a JAWS screen reader bug (see https://github.com/FreedomScientific/VFO-standards-support/issues/78). We only add the ARIA attribute on Chrome _on Windows_ to avoid having any impact on Chrome on other platforms (macOS, iOS, Android, etc.)
=> Fix BPB announcement and operation on Chrome with JAWS screen reader

rollup.config.js
Currently, when running `npm run watch`, editing a file will cause a failure in generating the CommonJS and ES outputs:
```
bundles src/js/index.js → dist/video.es.js, dist/video.cjs.js...
[!] Error: Could not load mux.js/lib/tools/mp4-inspector (imported by /tmp/video.js/node_modules/@videojs/http-streaming/dist/videojs-http-streaming.es.js): ENOENT: no such file or directory, open 'mux.js/lib/tools/mp4-inspector'
Error: Could not load mux.js/lib/tools/mp4-inspector (imported by /tmp/video.js/node_modules/@videojs/http-streaming/dist/videojs-http-streaming.es.js): ENOENT: no such file or directory, open 'mux.js/lib/tools/mp4-inspector'
at /tmp/video.js/node_modules/rollup/dist/rollup.js:17372:19
at <anonymous>
```
Add `mux.js/lib/tools/mp4-inspector` to the list of externals.
=> fix: change rollup config so that npm run watch works

docs/guides/player-workflows.md, docs/guides/setup.md
Favours using a source object as the argument to `src()` in the workflows doc, and adds `<video-js>` to the setup doc.
=> docs: emphasize src object and video-js element

src/js/player.js
The fullscreen API now returns a promise. If the player is inside an
iframe that doesn't allow fullscreen, the promise will reject and cause
an error to be logged. Instead, we should silence this promise.
Fixes #5918
=> fix(player): silence rejected fullscreen promise

src/js/player.js
Followup to https://github.com/videojs/video.js/pull/5912
=> fix(fs): feature detect el.matches() for IE11

src/js/control-bar/text-track-controls/off-text-track-menu-item.js, src/js/control-bar/text-track-controls/text-track-button.js, src/js/control-bar/text-track-controls/text-track-menu-item.js, test/unit/control-bar/text-track-controls/text-track-menu-item.test.js
This fixes a regression introduced in v7.4.3. The addition of [this code](https://github.com/videojs/video.js/pull/5741/files) made it so that, when turning on captions, other text tracks are only disabled if they are of the same `kind` as the one being selected. This resulted in broken behavior when switching between a `subtitles` track and a `captions` track or vice-versa.
"Subtitle" tracks should be disabled if another "caption" track is enabled, and vice-versa (in other words, they should be considered the same when enabling/disabling tracks). There is existing infrastructure that stores the appropriate text track `kinds_` or `kind_` for a given instance of `TextTrackButton`, each of which creates a list of `TextTrackMenuItem` instances. We can pass that information on to each …
=> fix: switching between 'subtitles' and 'captions' text tracks is broken

.github/stale.yml
Add "Affects: a11y" as an exempt label and switch to outdated label instead of wontfix as the stale label.
=> chore: add Affects: a11y and switch to outdated label

src/js/player.js, test/unit/controls.test.js
For non-prefixed APIs, check directly against the fullscreen element
rather than using the cached value.
Fixes #5814.
=> fix(fs): fix isFullscreen check for spec-api

src/js/big-play-button.js, src/js/button.js, src/js/clickable-component.js, src/js/close-button.js, src/js/component.js, src/js/control-bar/progress-control/seek-bar.js, src/js/menu/menu-button.js, src/js/menu/menu-item.js, src/js/menu/menu.js, src/js/modal-dialog.js, src/js/player.js, src/js/poster-image.js, src/js/slider/slider.js, src/js/tracks/text-track-settings.js, test/unit/menu.test.js, test/unit/modal-dialog.test.js, test/unit/player-user-actions.test.js
We saw some issues with the recently-added hotkeys feature.
1. The use of `document`-level `keydown` listeners caused players to respond to events they should not have when focus was not in the player.
1. Those `keydown` events which do reach the player are considered possible hotkey triggers. However, there are sometimes elements added to the player - such as in modals - that _should not_ trigger hotkeys.
- Rename any `handleKeyPress` method to `handleKeyDown` because that's more accurate. Define `handleKeyPress` as a `Component` method that delegates to `handleKeyDown` so that any existing uses of it should not break.
- Do not bind/unbind listeners on `focus`/`blur` and stop listening for `keydown` events on the `document`. It's better to just listen for `keydown` events on the …
=> fix: make sure hotkeys are not triggered outside the player or in form fields within the player

src/js/player.js
There was an issue with the merge of #6001 where these two methods got re-added accidentally.
=> chore: fixup merge issue with #6001

src/js/event-target.js, src/js/mixins/evented.js, src/js/utils/events.js, test/unit/events.test.js, test/unit/mixins/evented.test.js
There are a lot of times in Video.js code and plugin code where we want a function to trigger a single time for an array of events, then remove itself after the first event. I have implemented such a function via `any`.
Here are some examples:
Single event
```js
const player = videojs('some-player-id');
player.any('a', (e) => console.log(e.type + ' triggered');
player.trigger('a');
// logs 'a triggered'
player.trigger('a');
// logs nothing as the listener has been removed.
```
Multiple Events
```js
const player = videojs('some-player-id');
player.any(['a', 'b', 'c', 'd'], (e) => console.log(e.type + ' triggered');
player.trigger('d');
// logs 'd triggered'
player.trigger('a');
player.trigger('b');
player.trigger('c');
player.trigger('d');
// all triggers above log nothing as the listener …
```
=> feat: any event function

docs/guides/options.md, src/js/player.js, test/unit/player-fullscreen.test.js
This allows us to then extend the `fullscreen` option with `element` and `handler` as necessary.
=> refactor: switch to fullscreen.options

src/js/control-bar/play-toggle.js
The play button stops working when recent versions of Google's Polymer
is in use on the page because of the way Polymer synthesizes 'tap'
events on non-touch devices. The Polymer tap code thinks the click
event was ignored unless the DOM event's stopPropagation method is
called. 
Demo of issue: https://codepen.io/mscalora/pen/mQzQmp
Fixes: videojs/video.js#5624 In chrome 70 the small play/pause control doesn't work with Polymer 1.x Gestures tap is used on document
The play-pause button's click handler now calls event.stopPropagation() after the click event is handled.
=> Fix polymer issue by marking click event with stopPropagation

sandbox/double-sub-video.html.example, src/js/tracks/text-track-display.js
Allows users to set the `allowMultipleShowingTracks` option on the textTrackDisplay in order view multiple texttracks at once on the player. Once this setting is set to true, you can view multiple text tracks in the player by setting `textTrack.mode = "showing"` on the tracks you want to view.
* add below as an option on the video js player.
```
textTrackDisplay: {
allowMultipleShowingTracks:true
}
```
* Allow mutliple texttracks to be displayed at once.
=> Allow displaying of multiple text tracks at once

src/js/control-bar/progress-control/time-tooltip.js
I found myself needing to access the value that was being written to the time tooltip and the only way to do this was to overwrite the entire `update` method just to set the `time` content to the TimeTooltip state. This method would allow for overriding a single line of code if the DOM mutations aren't preferred.
=> Introduce write method to handle value output

src/js/component.js
=> fix: undeprecate options()

src/js/live-tracker.js, test/unit/live-tracker.test.js
This addresses an issue where autoplay players playing live streams would seek to the live edge after the first seek a user initiated (via UI or API).
Before listening for the `play`/`timeupdate` combination when starting the `LiveTracker`, check if the player has already started playback.
editors=1000#0))
=> fix: do not seek to live on first manual seek when autoplaying a live stream

docs/guides/options.md, src/js/big-play-button.js, src/js/player.js, src/js/poster-image.js, test/unit/player.test.js
Video.js checks whether sources are playable and both displays a message to the user and logs an error to the console. In Google's [mobile friendly test](https://search.google.com/test/mobile-friendly) and related tools, this message and error is triggered because their test browser's video element does not support any video formats. Some Video.js users are concerned about the æsthetics of the rendered preview within the tools and whether this might have an SEO impact.
Adds a `suppressNotSupportedError` option, defaulting to `false`. If set to `true`, if no sources are playable the error is deferred to the first human interaction (click or touchstart) but cleared if a loadstart occurs.
=> feat: Add option to suppress initial error for non-playable sources

src/js/control-bar/picture-in-picture-toggle.js, src/js/player.js, test/unit/controls.test.js
The WICG spec calls out only two events, enterpictureinpicture and
leavepictureinpicture. We should try and only use those.
If pictureinpicturechange is still necessary, it can be re-added at a
later date.
=> refactor(pip): rely only on WICG spec events

src/js/control-bar/control-bar.js
This came up in #5824. We do currently disable the button if PiP isn't available or isn't allowed, but we should just not show it if the APIs aren't available in the browser to keep the control bar cleaner.
When Safari support is added, this should be augmented to check for Safari PiP support.
=> fix(pip): hide PiP button in browsers not support the WICG spec

src/js/player.js, src/js/tracks/text-track.js, test/unit/tracks/text-track.test.js
Use the new `any` event function where it makes sense.
=> chore: use the new `any` event function

.gitignore, package.json
Currently, `zh-CN` and `zh-TW` are used as shorthands for Simplified and Traditional Chinese character sets, respectively. However, they carry with them a built-in assumption about the geographic locale which may not be appropriate in all cases.
The codes `zh-Hans` and `zh-Hant` are more correct in that they refer only to the character set and not the geographic locale. Further specificity is available via codes like `zh-Hans-CN`.
* Clone `zh-CN` to `zh-Hans` and `zh-TW` to `zh-Hant` during the build process.
* For the time being, do not check these copied files into source control. In v8.0, Video.js can switch to the new codes.
=> lang: clone zh-CN to zh-Hans and zh-TW to zh-Hant

src/js/component.js, src/js/utils/computed-style.js
Add use of the safe version of getComputedStyle in the currentDimension method of Component's class.
This will prevent a null exception when a video.js is implemented in a 'display:none' iframe on Firefox (<62).
This is a fix in continuation of the MR #3664 regarding a bug in Firefox https://bugzilla.mozilla.org/show_bug.cgi?id=548397
- use the safe version of getComputedStyle already present in video.js
- small improvement of the safe version of the getComputedStyle
=> fix: add use of the safe version of getComputedStyle

src/js/control-bar/progress-control/mouse-time-display.js, src/js/control-bar/progress-control/play-progress-bar.js, src/js/control-bar/progress-control/progress-control.js, src/js/control-bar/progress-control/time-tooltip.js, src/js/control-bar/time-controls/time-display.js, src/js/control-bar/volume-control/volume-control.js, src/js/slider/slider.js, src/js/utils/fn.js
This pull request contains various performance improvement broken up into separate commits.
=> perf: throttle more timers and use native bind

package.json
Currently running `npm run start` or `npm run watch` causes a loop since chokidar watches for all `.json` changes and during `build:lang` we copy to `.json` files. This causes chokidar to `build:lang` forever.
=> chore: fix lang watch loop caused by zh-* copy

src/js/component.js, test/unit/component.test.js
Saves about 1ms per `setTimeout`/`requestAnimationFrame`. Since we have several long running intervals that use these this is a fairly significant performance improvement.
=> perf: Do not add/remove listeners for each timer

test/unit/player.test.js
Various things are logging "errors" which are just errors that we expect from tests, silence them.
=> test: silence test logs

src/js/player.js, test/unit/player-user-actions.test.js
We got a bug report at Brightcove about hotkeys still firing when the user was focused in an element with `contenteditable`. This should fix that.
Exclude elements where `el.isContentEditable == true;`.
=> fix: do not handle hotkeys in contenteditable elements

src/js/player.js
Allow the dimension method of the Player module to accept 'auto' as an explicit value.
Check if dimension value in src/js/player.js's dimension function is 'auto' or '' when deciding to set the dimension to be automatic and return early in the function.
- [*] Feature implemented / Bug fixed
=> feat: allow player dimension method to accept 'auto'

docs/guides/components.md, src/js/clickable-component.js, test/unit/clickable-component.test.js
Allow a clickable component's click handler to be passed as a constructor option as a simple alternative to creating a custom component.
Makes for easier answers to "how do I create a button questions".
Add `clickHandler` as an option for ClickableComponent
All player controls override the `handleClick` method so are unaffected.
=> feat: Allow click handler to be specified in clickable component's options

src/js/control-bar/progress-control/load-progress-bar.js, src/js/control-bar/progress-control/progress-control.js, src/js/control-bar/progress-control/seek-bar.js, src/js/control-bar/progress-control/time-tooltip.js, src/js/control-bar/time-controls/current-time-display.js, src/js/control-bar/time-controls/duration-display.js, src/js/control-bar/time-controls/remaining-time-display.js, src/js/control-bar/time-controls/time-display.js, src/js/slider/slider.js, src/js/utils/clamp.js, test/unit/tech/tech-faker.js
Only update ui components when something has actually changed and wrap ui changes in requestAnimationFrame. This nets us most of the benefit from #6150
=> perf: only update ui on change, wrap things in requestAnimationFrame

src/js/utils/create-logger.js, test/unit/utils/log.test.js
Cap log history at 1000 items to prevent running out of memory on long videos.
=> fix: cap log history at 1000 items

docs/guides/player-workflows.md, src/js/component.js, test/unit/component.test.js
Usually, when we need to check if a component (or player) has been disposed, we check if its element exists:
```js
if (player.el()) {
// Do something...
}
```
It would be clearer if we had a method for that:
```js
if (!player.isDisposed()) {
// Do something...
}
```
* Add `isDisposed` method to the base component.
=> feat: add isDisposed method to components

package-lock.json, package.json, rollup.config.js, src/js/extend.js, src/js/tracks/text-track.js, src/js/video.js
es-abstract is huge, and there isn't really a reason for us to include it. See the changes here:
EDIT: made an actual pull request. https://github.com/brandonocasey/xhr/pull/1
└─┬ xhr@2.5.0
└─┬ parse-headers@2.0.2
└─┬ string.prototype.trim@1.2.0
└── es-abstract@1.13.0  deduped
We also are not using external helpers correctly, this pr fixes that as well.
=> perf: Save 3740 bytes gizpped by getting rid of xhr deps

package.json
I put a lot of random files into the sandbox, so, we shouldn't be linting it.
=> chore: ignore sandbox during linting

src/js/setup.js, src/js/utils/guid.js, test/unit/player.test.js
When a player is created without an `id` on the embed code, Video.js automatically assigns it one based on an auto-incrementing number (a.k.a. a GUID). For the longest time, this has happened to result in the default `id` of the first player being `vjs_video_3`.
It was never intended for users to rely on this value being consistent, but users do strange and inadvisable things.
PR #6103 had an unintended side effect in that it changed the default `id` to `vjs_video_2`, which we worry could affect some users of Video.js.
* Increment the internal starting point of the GUID from 1 to 3.
* Avoid doing anything that increments the GUID simply by including Video.js on the page.
* Add a test that simulates the initial player creation by resetting the GUID to its initial value to verify that the …
=> fix: ensure the default ID of the first player is 'vjs_video_3' as some people have relied on this

docs/guides/components.md, docs/guides/player-workflows.md
Add SubsCapsButton, SeekToLive and LiveTracker.
Fixes #5980.
=> docs: update Components list

docs/guides/components.md
Wondering if the recent update to components.md shouldn't also have the note "_(hidden, unless there are relevant tracks)_" next to the `SubsCapsButton` (like all other text track buttons)? Sure, in this case "_relevant_" is two different `kind`s of text tracks, but it still holds, doesn't it?
If I'm wrong about this, feel free to dismiss this PR! I just wanted to add it as I didn't see/review the #6253 before it was merged.
=> Minor update to components.md

src/js/tech/html5.js
Description of the problem: 
When playback is ongoing in iOS + Safari and the user disconnect headphones (wired or Bluetooth) the player will throw 'suspend' or 'stalled' after a couple of seconds and 'progress' events. 
Solution: Validation for stalled and suspended event for iOS browser when headphones are disconnected
=> fix: validation for stalled and suspended event in iOS when headphones disconnect

src/js/player.js
When suppressing the incompatible source error the error message is checked. This makes it incompatible with videojs-errors, which changes the error text.
Check the error code instead of message
=> fix: Make suppressing no source error compatible with videojs-errors

docs/guides/options.md, src/js/tech/tech.js, src/js/tracks/text-track.js
Reimplementation of https://github.com/videojs/video.js/pull/2192
on current code. Seems to work but has not been carefully tested,
especially on conditions such as slow networks or default tracks.
Would appreciate testing and any advice on ways this may go
wrong and need additional work.
For https://github.com/videojs/video.js/issues/5252
This delays loading of the VTT cue files until they are selected.
For sites like Wikipedia that tend to have large numbers of
crowdsourced subtitles and can show many files together on one
page, this saves a lot of unnecessary network transfer and API
hits.
* does not load text tracks immediately unless they are default or non-subtitles
* does load them on demand
=> Load text tracks on demand

src/js/component.js, src/js/player.js, src/js/utils/dom-data.js
If we are running on a browser that doesn't support WeakMap, use a
simple WeakMap sham as a fallback.
Also, add a tiny Set sham.
We received a request (in https://github.com/videojs/video.js/pull/6103) that we broke Android 4.x due to lack to WeakMap. This creates a WeakMap sham to use as a fallback when WeakMap isn't available.
To test locally, I change the file to always create the FakeWeakMap and use that as the default export.
=> fix: bring back Android 4.x support

src/js/component.js, test/unit/component.test.js
When an index is specified with `Component.addChild()` then the new component's element is added at the given index. This isn't necessarily correct, as not all of a component's children have DOM elements. Adding a component at the index of the control bar in the player's children will insert its el after the control bar el, because of the MediaLoader and LiveTracker.
When inserting the elelment, refer to the `el_` of the sibling component this is to be inserted before.
=> fix: ensure components added with an index are added in the correct location

.gitignore, .npmignore, package.json, rollup.config.js
The PR introduces an alternative ES module file for videojs core build.
I created this PR because I would like to use videojs core directly from the browser like this:
`<script type="module">
import videojs from 'video.js/dist/alt/video.core.es.js';
</script>`
For now, main videojs build supports umd, cjs and es module. Not sure why core build supports only cjs and umd.
=> Chore: introduces core ES module.

src/js/live-tracker.js, test/unit/live-tracker.test.js
It resets pastSeekEnd_ value to 0 when its value is higher than seeking increment value.
In rare cases, for example when we stop ingesting the live stream. The playlist duration doesn't change at all but we are constantly increasing the value of the pastSeekEnd_ variable which forces the DVR progress forward and increases the size of the gap on the progress bar.
If the pastSeekEnd_ value is higher than 1.5 x seeking increment value then set pastSeekEnd_ variable value to 0.
=> feat: resets pastSeekEnd_ variable.

src/js/utils/browser.js
New iPadOS User-agent does not contain "iPad" string in order to detect the device 
Detect  IS_SAFARI && TOUCH_ENABLED we can conclude is and iPad Device.
=> Fix: Add detection to for iPadOS in IS_IPAD const

package.json, src/js/big-play-button.js
Fixes #6270. This appears to be caused by an unreported browser bug. It also reproduces with shaka player if you call `document.querySelector('video').focus()` while playing back DRM content. For now, the only solution is simply to avoid calling `videoEl.focus()` in IE/Edge for DRM. This unfortunately may prevent hotkeys from working correctly in IE/Edge.
Modify the conditions under which we call `this.player_.tech(true).focus()` when the big play button is clicked.
=> fix: encrypted content goes black in IE/Edge when video element focused

src/js/extend.js, test/unit/extend.test.js
=> fix(extend): super_ should be available for backwards compatibility

rollup.config.js, src/js/tech/html5.js
We had to turn off strict mode (https://github.com/videojs/video.js/pull/4551) in Video.js due to a change in vtt.js. That has now been fixed in videojs/vtt.js#40 and released as part of 0.15.2 which will be available via https://github.com/videojs/video.js/pull/6333.
Fixes videojs/vtt.js#15
=> fix: turn on strict mode again

.jsdoc.json, README.md
depends on https://github.com/videojs/videojs.com/pull/112
closes https://github.com/videojs/video.js/issues/6340
video.js logo is broken in this README and on the docs site (#6340 )
Update the link to point to a valid image url (waiting for https://github.com/videojs/videojs.com/pull/112 to be merged)
=> fix broken logo link in README and docs

src/js/utils/browser.js
Safari user agent. However, the new check also returns true for iPhones.
Therefore, we should exclude iPhones from the check.
Unfortunately, this means that the iPhone user agent detection on
iPhones inside the Facebook app may break again as previously
(https://artsy.github.io/blog/2012/10/18/the-perils-of-ios-user-agent-sniffing/) we
excluded iPads from the iPhone check but that won't work anymore.
=> fix: IS_IPAD should be false on iPhone

src/js/control-bar/progress-control/seek-bar.js
A proposed fix for #6370
Progress control is not updating as expected when the video is paused and the user would like to seek a point in time by clicking the progress bar.
Improves handle for `mouseup` event inside the seekbar component. When the player is in pause mode and the `mouseup` event is triggered we want to call the update method without `throttling` to be sure that the progress bar position is up to date.
=> fix: updates seekbar position after mouse up event is triggered.

src/js/control-bar/progress-control/seek-bar.js, src/js/live-tracker.js
In #6142 I updated a lot of our code that used a hard coded 30ms `UPDATE_REFRESH_INTERVAL` so that it used a shared value in `Fn`.  Seems like I missed two in `seek-bar` and `live-tracker`
=> refactor: use Fn.UPDATE_REFRESH_INTERVAL in seekBar & liveTracker

src/js/slider/slider.js
Without these changes `area-valuenow` for the seek bar often reports `NaN`
=> fix: slider screenreader value returning as NaN

src/js/player.js
A proposed fix for #6391 
Adds support for `mouseout` event to catch the user click outside the player.
=> fix: improves control bar hiding functionality

src/js/control-bar/progress-control/seek-bar.js
The progress bar tooltip get stuck and don't update the time as the video plays. It only respond to mouse movements and reflects the time in the current time tool tip.
Add a reference for the playProgressBar component at seekBar to trigger the update action on every playing and timeupdate event
=> fix: current time tooltip does not update

test/unit/tracks/text-tracks.test.js
This PR adds a test for https://github.com/videojs/video.js/pull/6410
The test does *not* pass without the change in https://github.com/videojs/video.js/pull/6410
=> test: Add test for remote text tracks firing change events when using native text tracks

src/js/utils/browser.js
This loosens the regex used for Edge. Still detects legacy Edge but now
also detects the new Edge.
IS_CHROME still returns true for Edgium but I think that it's worth
keeping that as the behavior should be pretty close. If there is a need
to differentiate, can check IS_EDGE and also whether IS_EDGE &&
IS_CHROME is present. Combining with IS_WINDOWS could also be useful as
some capabilities of Edge are only available in Windows.
=> fix: detect chromium-based Edge

lang/en.json
Change from "subititles" to "subtitles"
"subititles settings" -> "subtitles settings"
=> Fix: solves a typo in en translation file

src/js/live-tracker.js, src/js/player.js, test/unit/live-tracker.test.js, test/unit/seek-to-live.test.js
Use the old liveui for live videos where `seekableEnd - seekableStart` is less than `30s`. This is configurable with an option.
=> fix: add a threshold of 30s for the liveui to show

src/js/poster-image.js
This is continuation of #6318. The original fix addresses the issue with DRM content going black in IE11/Edge only if playback is started by clicking directly on the big play button. The issue is still present when you initiate playback by clicking anywhere on the poster element.
Implement the same solution in PosterImage click handler as in the original fix.
=> fix: DRM content goes black in IE/Edge when playback is started by clicking on poster image

src/js/tech/html5.js, test/unit/tracks/text-tracks.test.js
It seems we have never triggered `change` events on `remoteTextTrack` when we were using native text tracks. This was a problem for VHS, which exclusively uses text tracks.
This makes it so we do trigger the event. Main issue with this change is that it creates a potential for a false positive where a change event was triggered from a non-remote text track but the remoteTextTrack list still received a change event. This issue is mitigated by best practices of looping through the list looking for the modes that you care about.
=> fix: trigger change events on remoteTextTrack when nativeTextTrack is set to true

src/js/player.js, test/unit/player-play.test.js, test/unit/player.test.js
This change allow the player to seek into a specific time before the player starts to play on all the browsers.
Add some checks to detect whenever the player is changing the source or is not ready yet to process the seek attempt and stores in cache the given value in seconds to be applied once the player is able to perform a seek
=> feat: Improve currentTime to allow be used before player is ready to play

src/js/component.js, test/unit/component.test.js
I think I find myself having to be defensive about Component children of children a lot. Specifically for control bar components. For instance, to get the `mouseTimeDisplay` we have to do something like this:
```js
const controlBar = player.getChild('ControlBar');
if (!controlBar) {
return;
}
const progressControl = controlBar.getChild('ProgressControl');
if (!progressControl) {
return;
}
const seekBar = progressControl.getChild('SeekBar');
if (!seekBar) {
return;
}
const mouseTimeDisplay = seekBar.getChild('MouseTimeDisplay');
if (!mouseTimeDisplay) {
return;
}
```
I think it would be much better if we had a built in way to be defensive about getting descendants instead of having all this code. This is the API that I propose:
```js
const mouseTimeDisplay = player.getDescendant( …
```
=> feat: Add a function for getting descendants from components

src/js/player.js, src/js/tech/html5.js
This is a rebase of #6376 with whitespace changes removed. All credit due to @citosid, whose original committer information is retained.
Expose getter/setter for the player's `crossOrigin` property, and add `crossorigin` to the list of internal properties that are copied into the HTML5 video elements. This enables resources like subtitles to include cookies in their XHR requests for sites that require authorization to fetch.
=>  feat(cors): add cors options to enable cookies on requests

src/js/player.js
Fixes a bug with the setter and aliases `crossorigin` to `crossOrigin`.
This is a followup from #6533, /cc @sodabrew @citosid
=> feat(cors): allow both crossOrigin and crossorigin method and options

docs/guides/angular.md
Updated the demo to make it run correctly in angular v8.0.0 and later.
Without the `static: true` property, an `not defined ReferenceError` will be thrown since the target is null on init.
=> docs: let the demo work correctly in angular v8+.

src/js/control-bar/progress-control/seek-bar.js
Right now `seekBar.update()` is getting called on after it is disposed by `liveedgechange` causing  and error to be thrown about `player` not existing and us trying to call `ended` on it [here](https://github.com/videojs/video.js/blob/master/src/js/control-bar/progress-control/seek-bar.js#L138)
=> fix: update being called on seekbar during dispose

src/js/tracks/text-track.js, test/unit/tech/tech-faker.js, test/unit/tracks/text-track-list-converter.test.js, test/unit/tracks/text-track.test.js
=> fix(text-tracks): set withCredentials on XHR if crossOrigin='use-credentials'

src/js/component.js, test/unit/component.test.js
The fix in #6297 doesn't work where the child to insert before is an element rather than a component, e.g. the video element.
Check if the child to insert before is an element, as well as checking if it has an `el_`
=> fix: addChild with index should allow for children that are elements

README.md
=> Update CDN version

src/css/components/_layout.scss, src/js/player.js, src/js/tech/html5.js
=> fix(fs): don't set player element css props on native fullscreen

package.json
Just a suggestion; update the description of video.js to better reflect what it is now, rather than what it was. It seems like this change should have happened when v7 was first released, but maybe it makes sense to do it now?
=> Update description of video.js in the package.json file, and add 'hls' keyword

src/js/control-bar/picture-in-picture-toggle.js, src/js/player.js, src/js/tech/tech.js, test/unit/controls.test.js, test/unit/player.test.js
The requestPictureInPicture API and button currently assume thta if the browser supports the PIP API, the tech supports it. This results in a broken button with certain techs, such as youtube or HTML5 with an audio el. Fixes #6398.
Check if disablePictureInPicture is exactly `false`. If `true` it's disabled and if `undefined` the tech does not support it.
=> fix: Disable PIP if tech doesn't support it

package.json
Following on from #6603, change the keywords to match the updated description in `package.json`.
=> Remove "flash" and add "dash" in keywords about video.js

src/js/control-bar/progress-control/progress-control.js
This was brought to our attention by a comment on #6155 https://github.com/videojs/video.js/pull/6155/files#r416763642
It seems that I used clamp wrong in that pull request. and this is the fix for it.
=> fix: Use clamp correctly in progress control

src/js/player.js
Fixes #6707. The Fullscreen API is unsupported in iOS, so `self.fsApi_.fullscreenerror` and `self.fsApi_.fullscreenchange` are undefined, which was breaking the player after entering fullscreen by [removing all bound player events](https://github.com/videojs/video.js/blob/main/src/js/utils/events.js#L369-L377).
Both `requestFullscreen()` and `exitFullscreen()` add handlers for `'fullscreenchange'` and `'fullscreenerror'` events, but remove those handlers for `self.fsApi_.fullscreenchange` and `self.fsApi_.fullscreenerror` events. There may be a reason for this inconsistency, but it seems to me that if `.one()` uses the event string, `.off()` should as well (especially considering the latter two are not always defined).
Another option might be to check for Fullscreen API support as well as …
=> fix: Fullscreen broken in iOS

docs/guides/plugins.md, src/js/plugin.js, test/unit/plugin-advanced.test.js
This adds a plugin-specific logger to all advanced plugins, by default. 
However, it will not override and `log` property from the prototype. By this, we avoid clobbering anyone's existing `log`.
=> feat: Add a default, plugin-specific logger to advanced plugins

src/js/player.js, test/unit/player.test.js
This introduces a debug mode which can be used to enable logs. Debug mode can be enabled via options, which will fire `debugon` and `debugoff` events.
=> feat: adding core debug mode

src/js/tech/tech.js
As part of #6588, we started using the crossOrigin method. However, it's
possible that a tech doesn't support this. Notably, the Flash tech. We
should instead have an abstract method on Tech that returns nothing so
we don't fail on those browsers.
=> fix(tech): add abstract crossOrigin method on Tech

src/js/player.js, src/js/tech/html5.js, test/unit/sourceset.test.js
There is a small typo in src/js/player.js, src/js/tech/html5.js, test/unit/sourceset.test.js.
Should read `initial` rather than `intial`.
=> docs: Fix simple typo, intial -> initial

src/js/utils/dom.js
From my understand, in the changes #5773, the Y position of all the
boxes is already calculated and accounted for in the offsetY value we
get. However, because the HTML coordinate system has Y=0 at the top,
when we do offsetY/boxH, we get a position relative to the top of the
element. However, we expect that position relative to the "start" of the
slider, or the bottom of it. Therefore, we want to get the inverse
value, which is '1 - clamp(offsetY/boxH)'.
Fixes #6863
=> fix(dom): vertical getPointerPosition value

src/js/tracks/text-track-display.js
For whatever reason, when the font size for text tracks is changed in
the text track settings dialog, we set a bottom of 2px on the cue.
This was added as part of the initial vtt work for Video.js in
https://github.com/videojs/video.js/commit/4e5c28cc561487ff29394d19dce3a420675e4f9d#diff-8169d53aa7eee6cab5f85b6641ef3117R176.
However, this doesn't seem to be doing anything right now and having it
means that when font-size is changed, multiple cues end up with a button
value of 2px causing them to overlap and obscure each other.
This works fine if the cues are positioned away from each other,
however, if multiple cues are positioned by default and a large font
size is used, while they will now stay on their lines, they may
partially obscure each other. This does not fix that issue and may …
=> fix(text-track): don't overlap captions when font-size changes

src/js/clickable-component.js, src/js/component.js, src/js/player.js, src/js/tech/tech.js, test/unit/clickable-component.test.js, test/unit/component.test.js, test/unit/player.test.js, test/unit/poster.test.js, test/unit/tech/tech.test.js, test/unit/tracks/text-track-display.test.js, test/unit/tracks/text-tracks.test.js
This change will trigger `languagechange` event each time `player.language()` is used as a setter. Also, `Component` will call `handleLanguageChange` method to manage the localization behavior.
=> feat: trigger languagechange event on a language change

src/js/tech/html5.js, src/js/tech/tech.js
This is helpful for source handlers and anything else that could have
customer behavior for when we're scrubbing or not.
=> feat(tech): add a scrubbing getter.

src/js/menu/menu.js
Closes #6912
Updates the `focus()` method of the Menu component to fix a bug with a CSS `className` comparison that expected the title element to be a standard DOM element instead of a Video.js Component.
When `focus()` is called on a Menu, use `Component.hasClass()` to determine if the first child is the title.
=> fix(menu): focus correct MenuItem on keyboard open

.github/PULL_REQUEST_TEMPLATE.md, docs/guides/faq.md, docs/guides/middleware.md, docs/guides/options.md
The FAQ lists the following as the autoplay blog link: https://blog.videojs.com/autoplay-best-practices-with-video-js/
The current blog link is: https://videojs.com/blog/autoplay-best-practices-with-video-js/
I made similar updates to other files as well. 
- URL changes from previous to new blog version
- Update pull request template to say "Chrome" instead of "Chome"
=> docs(fixup): change blog links to most recent blog version, fix typo

src/js/utils/dom.js
Fixes #6870
Skipping the `tabIndex` property on created elements due to #6145 optimizations blocks them from receiving keyboard events, due to not
being focus-able; for example this breaks closing `ModalDialog` elements by pressing Escape.
Fix this by always setting `tabIndex`, as the element may return the same value even though the property has not been explicitly set.
Fixes #6870
* Always set a `tabIndex` property passed to `Dom.createEl()`.
=> fix: always set tabIndex to restore keydown a11y

src/js/control-bar/track-button.js, src/js/tracks/track-list.js, src/js/tracks/track.js, test/unit/tracks/track-baseline.js, test/unit/tracks/track-list.test.js, test/unit/tracks/track.test.js
Allows the editing of a track's label after it's creation. Track buttons will listen for the labelchange event and update their content accordingly. This aligns videojs behavior with the [HTML label spec](https://html.spec.whatwg.org/multipage/media.html#text-track-label) linked in the docs, which says that "The label of a track can change dynamically".
- Add a setter for label property of the Track & fire labelchange event when the label is changed
- When tracks are added to TrackList, add a listener for a labelchange event on the track to trigger a labelchange event on the parent TrackList
- TrackButton listens for labelchange event on the TrackList, and will call the existing update handler to update the menu when the event is triggered.
=> feat(track): make label property mutable and fire a labelchange event when the label is changed

src/css/components/_live.scss
discussed in https://github.com/videojs/themes/issues/7
thx @Gregory-Gerard to find the correct place to fix it
The Button is to high in some designs
Put the Button as center item
=> fix live button positioning

src/js/utils/browser.js
Ran into an issue where we were using a configuration that looks something like:
```
{
nativeControlsForTouch: true,
html5: {
nativeTextTracks: browser.TOUCH_ENABLED
}
}
```
and we were not seeing captions appear in the native controls in Chrome on Microsoft Surface devices. After some digging, we found that with that browser/device combination, `TOUCH_ENABLED` is a number, not a boolean. And [the `nativeTextTracks` logic specifically does strict equality checks against `true` and `false` values](https://github.com/videojs/video.js/blob/694fe0f787f6b9b4edb06e6c87b91c50a8429237/src/js/tech/tech.js#L134-L138).
`TOUCH_ENABLED` should ALWAYS be a boolean. This PR casts the expression.
=> fix: cast TOUCH_ENABLED to boolean

rollup.config.js
Makes changes tests in watch take a bit less time to finish building (~5-10s) so that test iteration can be faster.
=> chore: move unit test build right below main for faster watch

rollup.config.js
This fixes an issue with requirejs where global/window and
global/document were being marked as dependencies. Instead, this makes
sure that the module gets inlines properly and not worked as a dep for
requirejs.
Fixes #6443, fixes #6272, fixes #6212, fixes #5680.
=> fix(rollup): browser globals shouldn't be external

src/js/control-bar/progress-control/time-tooltip.js
Currently during live playback with the new liveui if the progress control is all the way to the right of the seek bar the time tooltip changes in very small increments rapidly which looks really strange. 
Before:
After:
This happened when we introduced https://github.com/videojs/video.js/pull/5773
=> fix: play progress time tooltip from jittering during live

src/js/control-bar/time-controls/time-display.js
Fixed the change requested in #6700. Thanks to @travisbader
=> fix(control-bar): dont crash after dispose

src/js/utils/map.js
Bug was produced on an Android device using Chrome 34, which `window.Map` is not available. Error message `Cannot set property 'TimeDisplay#updateTextNode_' of undefined` was logged to console.
the `set` method in `MapSham` was using `set_` property, which is not defined within MapSham class. `map_` must be used instead.
Just changed `src/js/utils/map.js` file updating set method to use `map_` instead of `set_`
=> fix: fix set method to use map property

src/js/player.js, test/unit/player.test.js
The video dimensions aren't necessarily known at `loadedmetadata` particularly with native playback on iOS. In fluid mode, the player defaults to 16:9 and does not update once the dimensions are known.
- Updates player styles on `resize` events.
- Fixes arguments passed to `addEventedCallback` so the callbacks are executed.
Fixes #6939
=> fix(player): Ensure fluid works when dimensions not initially known

src/js/live-tracker.js, test/unit/live-tracker.test.js
* Prevents the live UI from showing when we don't have a seekable range
* Prevents the live ui control bar and tooltips from looking invalid when the trackingThreshold is turned off. (everything will display 0 now).
Fixes an issue in native Safari and Android HLS playback where liveCurrentTime returns Infinity (as we don't have a seekableEnd or seekableEnd is actually Infinity). Which causes the new live ui to show up when we don't really have a live window. 
Instead of returning Infinity when liveCurrentTime is Infinity, return 0. So that everything knows that we do not have a seekable window of live playback.
=> fix: set liveWindow to 0 liveCurrentTime is Infinity

.github/workflows/ci.yml
Fixes the issue seen in the tests that causes dependency installs to fail. Such as in this pull request: https://github.com/videojs/video.js/pull/7038 
This is just taking the updates from https://github.com/videojs/.github/blob/main/workflow-templates/ci.yml that were implemented in @videojs/http-streaming
=> test: update ci workflow to prevent install failures

COLLABORATOR_GUIDE.md, CONTRIBUTING.md, README.md, build/license-header.txt, docs/guides/angular.md, docs/guides/audio-tracks.md, docs/guides/faq.md, docs/guides/languages.md, docs/guides/middleware.md, docs/guides/plugins.md, docs/guides/skins.md, docs/guides/tech.md, docs/guides/text-tracks.md, docs/guides/video-tracks.md
Noticed that a lot of our docs point to the master branch, which is out of date and unused now. Along with this pull request we will have to update https://github.com/videojs/conventional-changelog-videojs to use `main`.
=> docs: change master to main

src/js/tracks/text-track.js, test/unit/tech/tech.test.js, test/unit/tracks/html-track-element-list.test.js, test/unit/tracks/html-track-element.test.js, test/unit/tracks/text-track-list-converter.test.js, test/unit/tracks/text-tracks.test.js
Noticed an error when disposing a player with text tracks on and was able to replicate it on our standard simple demo by turning on throttling to 6x in chrome and disposing the player with the default text track on. I also noticed that we do two other things:
1. It's possible to configure the player such that we trigger two updates for a text track on every timeupdate, as we don't remove timeupdate handlers before adding them in modechange.
2. If mode is set to `showing` more then once in a text track we add another update handler, without a limit to how many we can add.
=> fix: prevent dispose error and text track duplicate listeners

src/js/player.js
Using Video.js's .bind still makes us attach prototype methods as
handlers. Then when one is removed, all handlers are removed.
Instead, use arrow methods to make these methods unique.
Fixes #7013.
=> fix(fs): make sure handlers are unique per player

src/js/control-bar/time-controls/time-display.js
IE11 only supports HTMLElement and not text nodes in the contains
method. See https://developer.mozilla.org/en-US/docs/Web/API/Node/contains
Instead, compare firstChild.
=> fix(time-display): fix IE11 appending times instead of replacing

src/js/player.js
Focus on video player and scroll will raise the error
```
Ignored attempt to cancel a touchend event with cancelable=false, for example because scrolling is in progress and cannot be interrupted.
```
To reproduce the error:
1. Put your finger on video player (do not lift up the finger)
2. Scroll up and down
Check `event.cancelable` before executing `event.preventDefault`
see: https://developer.mozilla.org/en-US/docs/Web/API/Event/preventDefault#notes
=> Fix up preventDefault error on Android

src/js/mixins/evented.js, test/unit/mixins/evented.test.js
Follow up from #6982. We previously threw an error, but we've seen it
happen unexpectedly. Instead, we should log an error.
Here, if we have a `log` object on the current object, we should use it,
otherwise, we use a default `log` object.
=> fix(evented): log an error on invalid type

src/js/utils/dom.js
On iPads, if the player is inside a floating div, when fullscreen, we'll have an incorrect offset value. Instead, we should stop counting our offsets once we get to our fullscreen element (i.e. the player) because in fullscreen it's outside the regular flow, and we don't actually want to add offset the float gives us inline.
=> fix(dom): stop findPosition at a fullscreenElement

src/js/utils/dom.js
Since we switched to using adding up offsets to calculate the pointer position relative to the current element, we've had some issues, particularly on iOS, where a translated parent would cause us to miscalculate the position. This is currently a quickfix for the issue, and I'd like to spend some time to figure out a better solution that hopefully won't require us to iterate through the DOM and add up the transform matrix.
=> fix(dom): account for translated parent in pointer position

src/js/control-bar/progress-control/seek-bar.js
The progress control is updated inside of requestAnimationFrames (rAFs). Normally, this is fine. However, when a tab is hidden, rAFs are generally not triggered. So, what happens is that we get a cached rAF from the last time the tab was active. When we come back to be active, we update again, but because we already have a named rAF, we don't clear it out and instead that one gets triggered. This isn't an issue if the video is still playing, because in a second, another rAF will be triggered which will update things. However, if the video has ended, we won't get any more updated and the progress bar will still be in the old position.
Instead, when the document becomes hidden, we should clear out *both* the `SeekBar#update` and the `Slider#update` rAFs. Doing just one, unfortunately, isn't …
=> fix: clear progress control related rAFs when tab is hidden

index.html, rollup.config.js, sandbox/debug.html.example, src/js/debug.js
Adds a debug build to video.js that does the following:
* Exposes DomData on video.js. DomData our internal event tracking object and should be empty on player dispose.
* Set log level to debug by default.
=> chore: video.js debug build

docs/guides/faq.md, docs/guides/options.md, docs/guides/plugins.md
1. can't access current link [https://github.com/videojs/generator-videojs-plugin/blob/main/docs/standards.md](https://github.com/videojs/generator-videojs-plugin/blob/main/docs/standards.md) in `plugins.md` since it has changed to [https://github.com/videojs/generator-videojs-plugin/blob/master/docs/conventions.md](https://github.com/videojs/generator-videojs-plugin/blob/master/docs/conventions.md)
2. links in `faq.md` and `options.md` have same problem as [#6905](https://github.com/videojs/video.js/issues/6905)
=> docs: fix broken blogpost urls

package-lock.json, package.json, rollup.config.js
Adds rollup-plugin-replace for the soon to occur vhs update that will cause our cjs build to fail. We could also split the cjs and es build and alias es to `@videojs/http-streaming/dist/videojs-http-streaming.es.js` and cjs to `@videojs/http-streaming/dist/videojs-http-streaming.es.js` but the build will take longer with that change.
=> chore: update rollup for upcoming vhs changes

src/js/live-tracker.js
On native playback engines, like Safari, for some streams, seekable and
currentTime won't have correct values until video data has started
loading. Previously, we only tried to turn toggle tracking on
durationchange, now we also do it on canplay.
This is a followup to #7034 which helped prevent the live tracker from
showing up in some cases.
=> fix: try enabling liveui on canplay

docs/guides/options.md
Adds documentation for two options that fell through the cracks related to the new `liveui`.
=> docs: Add liveTracker options to options guide

src/js/tracks/text-track.js, test/unit/tracks/text-track.test.js
When preloadTextTracks option is set to false, it still preloads the default text track. This leads to duplicate tracks once the mode changes to showing and the track is loaded a second time. This includes the default text track in the behavior defined by the preloadTextTracks option.
Fixes #7019
#7019
Removes default text tracks from exclusion of behavior defined by `preloadTextTracks` option
=> fix: do not preload default text track if preloadTextTracks is false

src/js/control-bar/progress-control/progress-control.js
`SeekBar.handleMouseUp()` is a side-effect of disabling progress controls via `ProgressControls.disable()`. This is an issue because `SeekBar.handleMouseUp()` [manually triggers](https://github.com/videojs/video.js/blob/main/src/js/control-bar/progress-control/seek-bar.js#L352) a `'timeupdate'` event (because it assumes a seek has just taken place). If someone attempts to disable the progress controls before playback starts, a `'timeupdate'` will fire potentially before we even have `'loadedmetadata'`, which can cause problems.
- Move the relevant mouse and touch event listener removal that is needed by the `disable()` method from `handleMouseUp()` into its own function.
- Preserve the behavior where `ProgressControls.disable()` will resume a normal playback state if it is invoked while …
=> fix: Remove extra timeupdate event when progress controls disabled

src/js/player.js, test/unit/player.test.js
This adds support for a `retryOnError` option that will have the player select a new source from the source list when the selected one fails prior to playback. If a source fails during playback, no retry will be attempted.
=> feat: Retry on error

src/css/components/_adaptive.scss
A client reported that control buttons are not positioned correctly when player is full-screened and screen is small.
Currently we are excluding our responsive controls on fullscreen and changes include removing that. This solves the issue for small screens. Also added _!important_ rule to override BC skin properties and hide controls when necessary.
=> feat: enable responsive controls on fullscreen 

src/css/components/_volume.scss, src/js/control-bar/volume-control/mouse-volume-level-display.js, src/js/control-bar/volume-control/volume-bar.js, src/js/control-bar/volume-control/volume-control.js, src/js/control-bar/volume-control/volume-level-tooltip.js
Add tooltip for volume level so the user knows what they will change too. 
Maybe in the scope of WCAG "1.1.1 Non-text Content".
Add volume level tooltip.
=> Add volume tooltip

src/js/control-bar/audio-track-controls/audio-track-menu-item.js
Only change enabled on one track, the others will automatically be turned off. This prevents us from getting two  `AudioTrackList` `change` events where the first will have no tracks enabled, and the second has a track enabled.
=> fix: always have an enabled audio track when switching

.github/workflows/ci.yml
In a recent update from the VHS repo we added something so that we don't skip main workflows. I think we want it here too.
=> chore: never skip github actions workflows in main

src/js/control-bar/playback-rate-menu/playback-rate-menu-button.js
The Playback Rate control is a MenuButton, but has been modified from the standard MenuButton operation so that clicking on the button just switches to the next playback rate without displaying the menu. Also, the label of the button visually includes the current playback rate but that visual indication is not included in the accessible name or description of the button. As a result, screen reader users cannot perceive the current setting of the control, and do not realize that they actually can change the setting (by activating the button) since activating the button does not open a menu but also does not announce the rate change.
This temporary fix associates the current rate selection display in the button with the button itself using `aria-describedby`, so that it is announced by …
=> Make Playback Rate control work with screen readers - fixes #7121

package-lock.json, package.json
Update the `global` dependency to a recent version. The change already hapenned in http-streaming ( https://github.com/videojs/http-streaming/pull/1031 ) but video.js itself had another dependecy specification. This unifies it.
* Bumped the dependency in `package.json`
* Ran `npm install`
=> chore: update 'global' package in dependencies

src/js/menu/menu-button.js, test/unit/menu.test.js
Menus with one item are hidden if they have a title, because adding the title increments the hide threshold, but the title is not counted as an item. e.g. the chapters menu if there is a single chapter - `player.addRemoteTextTrack({src: 'data:text/vtt;base64,' + btoa('WEBVTT\n\n00:00:00.000 --> 00:00:05.000\nChapter 1\n'), kind: 'chapters'}, true);`
Don't increment `hideThreshold_` for the title.
=> fix: Don't hide menus with one item and a title

src/js/control-bar/progress-control/seek-bar.js, src/js/live-tracker.js, test/unit/live-tracker.test.js
This fixes two issues.
1. The current keybinds for seekbar do not take into account that duration will be `Infinity` for live playback. Which means that they will often throw an error when using for a live video. I fixed this by using the values from live tracker.
2. API seeks should abide by the liveThreshold this prevents seeks in vhs to just before seekableEnd from causing us to appear behind live. In general the original intention for `seekedBehindLive_` was to allow the user to seek behind live and ignore liveThreshold so that it wasn't jarring to the user that they couldn't seek.
=> fix: live user seek

lang/de.json, lang/en.json, src/js/video.js
Improves the tooltip/accessibility text for the fullscreen button so it's clearer the action is to leave fullscreen mode.
Adds an English translation within src/video.js rather than make it the default text which would change the translation key.
Updates English and German translations, some existing translations already translate it more like "exit fullscreen".
=> fix: Better text for exit fullscreen

package-lock.json, package.json, src/css/components/_big-play.scss, src/css/components/_layout.scss, src/css/utilities/_linear-gradient.scss
Updates sass and replaces use of / for division to get rid of the deprecation warnings when building.
Fixes #7244.
Output CSS is identical.
=> chore: Update sass and remove deprecated / for division.

src/js/control-bar/progress-control/seek-bar.js
I believe this is a bug. In `dispose` event listeners should be detached instead of reattached.
Changed `on` to `off`.
=> Fix attaching instead of detaching an event listener

src/js/player.js, test/unit/player-fullscreen.test.js
`fullscreenchange`, `fullscreenerror` events triggered by `Html5` were not handled as expected by `player` since some arrow functions missing necessary argument.
1. calling `player.requestFullscreen()` on any iOS device
2. runing code below to exit fullscreen
```js
function exitfullscreen() {
if (player.isFullscreen()) {
player.exitFullscreen();
}
}
```
video can exit fullscreen
video cannot exit fullscreen
After entered fullscreen, `player.isFullscreen()` still remain `false`.
None.
=> fix: player.loadTech_ incorrect arrow function

src/js/setup.js
In some server side rendering environments (e.g., `execjs` since
version 2.8.0 [1]) `setTimeout` is not available. Since
`autoSetupTimeout` runs when Video.js is imported and tries to
schedule `autoSetup`, this can lead to errors of the following form in
server side rendering:
TypeError: scheduler is not a function
`autoSetup` already bailed out if run outside of a browser environment
or if globally disabled. To prevent calling `setTimeout`, we already
perform the `Dom.isReal` check in `autoSetupTimeout`. Checking
`options.autoSetup` has to remain in `autoSetup` to preserve backwards
compatiblity with apps that set the option after Video.js has loaded
but before the next tick.
[1] https://github.com/rails/execjs/pull/43
=> Feature detect setTimeout in auto setup for SSR

package-lock.json, package.json
Because VHS is inlined into Video.js, we should depend on what VHS
depends on.
Fixes #7091, fixes #7209, fixes #7144, fixes #7109
=> feat(package): add VHS deps as Video.js deps

docs/guides/layout.md, docs/guides/options.md, src/css/components/_layout.scss
Fluid mode's automatic detection is nice but there can be a layout jump once the video dimensions are known. We have the `vjs-16-9` and `vjs-9-16` classes already, but square and portrait are also common now. 
Adds `vjs-9-16` and `vjs-1-1` classes for those aspect ratios.
=> feat: Add helper classes for 9:16 and 1:1

docs/guides/options.md, src/js/player.js, test/unit/autoplay.test.js, test/unit/player.test.js
This PR adds a new option to treat `autoplay: true` the same as `autoplay: 'play'`. In general we want video.js to handle as much of the autoplay logic itself as possible, since the browser's treatment of the video element's `autoplay` attribute is less predictable. For now the default option value is `false`, but it may be made the default behavior in a future major version.
=> feat: Add normalizeAutoplay option to treat autoplay: true as autoplay: "play"

src/js/utils/events.js
Fixes https://github.com/videojs/video.js/issues/7259 
update event polyfill detection logic to be compatible with react-native-web.
=> fix: event polyfill detection compatibility with react-native-web

src/js/player.js, test/unit/autoplay.test.js
When autoplay is set to `any` or `muted` and muted() returns `false`, video.js attempts the following workflow:
1. Call play(). If resolved, trigger `autoplay-success`
2. On rejection, save original muted() value and set it to `true`
3. Call play() again. If resolved, trigger `autoplay-success`
4. On a second rejection, we reset muted() back to the saved value
5. Ideally, the following .then method in the promise chain would be skipped and the `autoplay-failure` event would be triggered in the final .catch.
Since we .catch at multiple points along the promise chain, it's possible for step 4 to occur while still resolving to the following .then method, incorrectly triggering an `autoplay-success` event, instead of the expected `autoplay-failure`.
1. Rethrow an error after the muted() value …
=> fix: throw error on muted resolution rejection during autoplay

src/js/tech/middleware.js
Pretty straightforward. As far as I can tell, this is the only change needed to add support for ended() getter middleware. One use case for this is for client-side postroll ads, when the ended state of the tech is `true` but the player is still displaying ad content.
=> feat: Add ended middleware

src/js/player.js
If we've ended, there's no point in having the loading spinner. In
addition, there are cases where we get a waiting event immediately
before ended, and this works around that.
Fixes videojs/http-streaming#1156
=> fix: remove loading spinner on ended

src/js/utils/dom.js
https://github.com/videojs/video.js/issues/5706
Fail fast
=> fix: check element for null in case of a disposed player

src/js/player.js
Use `click`  instead of `mouseup` to handle tech click events. Closes https://github.com/videojs/video.js/issues/7291
Replaced `mouseup` event by `click`.
=> Use click event for tech click event

src/css/components/_control-bar.scss
1. On mobile tap a menu (such as the captions menu)
2. Wait for the menu to timeout and hide, but remember where the menu's position was on the player
3. Attempt to select one of the menu options, even though they are not visible
4. Notice that the menu item will be selected.
Prevent `pointer-events` from being triggered on the control bar while it is hidden or going into a hidden state.
=> fix: prevent control bar clicks/taps with while hidden

src/js/utils/time-ranges.js, test/unit/utils/time-ranges.test.js
This allows us to call `Array.from()` on TimeRange objects created by Video.js. For example:
```js
var input = [[0, 10], [20, 30]];
var timeRangeObj = videojs.createTimeRanges(input);
var output = Array.from(timeRangeObj);
assert.deepEqual(input, output, "they're the same!");
```
=> feat(time-ranges): make iteratable if Symbol.iterator exists

docs/guides/hooks.md, src/js/player.js, src/js/utils/hooks.js, src/js/video.js, test/unit/player.test.js, test/unit/videojs-hooks.test.js
Adding `beforeerror` and `error` hooks that make it easier to know when errors occurred on all players and allows intercepting and modifying errors.
=> feat(hooks): Error hooks

src/js/component.js, src/js/mixins/evented.js, test/unit/mixins/evented.test.js
Since `evented` is a mixin, it should cleanup after itself. I migrated the DomData cleanup from Component to the mixin dispose event listener.
=> fix: evented should cleanup dom data

docs/guides/react.md
=> docs(react): Fix typo

src/js/player.js
Fixes https://github.com/videojs/video.js/issues/7313
If multiple `mouseenter` events fire on the controlBar before a `mouseleave` event occurs, the cached inactivityTimeout value will get overwitten with a 0. This prevents the control bar from being hidden when the inactivity timeout is reached because the hide call is skipped when inactivityTimeout <= 0.
The circumstances around multiple `mouseenter` events firing before a `mouseleave` event are when a menubutton on the toolbar has its `update()` method called: the menu popup is disposed but a `mouseleave` event isn't fired for it. Once any mouse activity is detected the control bar's `mouseenter` fires again, wiping out the cached value.
An example of this occurring on a plugin …
=> fix: prevent cached inactivityTimeout from being overwritten

.github/workflows/release.yml
The release job will do an npm publish and a github-release.
It's based on videojs/.github/github-release.yml.
The new version is published as `next` and requires to be promoted to
latest manually.
The deploy job, should do an aws s3 sync to upload the files to S3 for
us. It uses a Github Environment secrets. This is so that we can require
a user to approve the CDN upload.
=> chore: add a release and deploy Github Action

docs/guides/react.md
https://github.com/videojs/video.js/issues/7361
=> docs(react): update react functional component tutorial

docs/guides/plugins.md
Fixed a typo in the plugins guide "Plugin Setup Events" section.
=> docs: fix typo in the plugins guide

src/js/component.js
Since Video.js 6, we've removed the deprecated functionality, we no longer need to have a deprecation warning.
=> fix: remove deprecation of getComponent feature

src/css/components/_adaptive.scss
Previously we introduced _!important_ rule to override BC skin properties and fix the layout for small screens. I've done several tests in Chrome, Firefox and this is not longer needed, so we can safely remove it.
=> fix: remove rule on small layout

src/js/tracks/text-track-display.js, test/unit/tracks/text-tracks.test.js
=> Set the 'lang' attribute on text track display elements, if the language of the track is known

docs/guides/options.md, src/js/live-tracker.js, test/unit/seek-to-live.test.js
Some live streams with a 30s live window can actually fluctuate between below and above the 30s threshold we have. Instead, we should have a slightly lower default to have those streams get the liveui.
=> fix: enable liveui on more livestreams

src/js/player.js, src/js/tracks/text-track-display.js
This is another follow-up to #6699.
Potentially, it means we could get rid of #6977
=> fix: don't let the player be translated except captions

src/css/components/_adaptive.scss
When responsive mode is used and the player layout is small or smaller, an empty space appears to the right of the mute button on hover.
Fixes #7465 
Add class vjs-hover to .vjs-volume-panel.vjs-volume-panel-horizontal.
=> fix: volume button empty space

test/unit/player-user-actions.test.js
f3913cd0ea9f17f2e55e6b98d237a263f925de41 is the test for #7495.
Once that one is in, I'll rebase this PR and merge it in, these tests are copied and updated from the doubleClick userAction tests.
=> test: add tests for the click user action 

src/js/live-tracker.js, test/unit/live-tracker.test.js
We try and enable the liveui on `canplay`, however, we only do it the first time after the `LiveTracker` is enabled. This means that if you change sources, we may not catch that the liveui should be enabled. This is particularly important for browsers where native playback is used, like Safari, as the metadata may not be available until `canplay`.
This is a follow-up from https://github.com/videojs/video.js/pull/7114 which enabled listening to `canplay` but apparently forgot to account for switching videos in the same player.
=> fix: improve enabling liveui when switching sources

src/js/control-bar/audio-track-controls/audio-track-menu-item.js
Audio Tracks are supposed to allow multiple tracks at the same time.
Safari 15 has added, at least partial support for this.
In #7163, we stopped turning other tracks of manually since we already
were doing so in the AudioTrackList. However, this only worked for
non-native AudioTracks. Before Safari 15, Safari automatically turned
off the other tracks for us so things continued to work.
With this change, when native audio tracks are used, we will turn off
the other tracks, partially reverting #7163.
We currently do not have any tests or are set up for writing tests for
these proxy tracks. Adding such tests will take too long for not a lot
of benefit, unfortunately.
Fixes #7494.
=> fix: turn off other tracks with native audio track

src/js/tech/html5.js
On latest iOS, we are seeing times when the volume feature detection is
showing that we are able to change the volume, though, that is not the
case. Instead, on iOS, when we detect that we can control the volume, we
set a short timer to retest and reset the featuresVolumeControl property.
Fixes #7040
=> fix: try again on volume feature detection on iOS

src/js/control-bar/progress-control/seek-bar.js, src/js/slider/slider.js, test/unit/controls.test.js
We were always setting `scrubbing(true)` on mouse down. This means, that
we'd use `fastSeek` even when seeking while clicking, rather than only
when scrubbing.
The main fix involves knowing in `handleMouseMove` whether we were
called directly as a `mousemove` handler or whether it was called from
`handleMouseDown`. This means that when `handleMouseMove` is called via
`handleMouseDown` we can skip setting `scrubbing(true)` and only do it
when we are scrubbing directly.
Fixes #6988, fixes #7360
=> fix: don't always use fastSeek when available.

COLLABORATOR_GUIDE.md
Fix a small typo in the COLLABORATOR_GUIDE
=> docs: fix typo in COLLABORATOR_GUIDE

src/js/tech/html5.js
This is a follow-up to #7514. But turns out, that we still had a timing
issue around when we were doing the check and when the volume control
was created.
Instead, we should make `featuresVolumeControl` not be a lazy property,
so, that we do that check as early as possible. Also, we should
default this property to `false` in this case, so, that we assume we
can't until we confirm we can.
Additionally, added a null check for Html5, to be extra defensive since
the timeout isn't to a player.
=> fix: volume control showing up on iOS

src/js/control-bar/audio-track-controls/audio-track-menu-item.js
In #7337, a lot of code was updated to no longer user innerHTML, but we
accidentally caused an issue with Audio Description (AD) tracks where
the track title was included twice. Once before and once after the AD
icon.
This is because we were calling `super.createEl()` but MenuItem created
a specific element and didn't just pass things the arguments along.
Instead, we should use `Dom.createEl()` directly.
Fixes #7556
=> fix: regression with AD audio track menu items

docs/guides/options.md, src/js/control-bar/time-controls/remaining-time-display.js, test/unit/controls.test.js
Make the negative sign on the remaining time display optional. Closes #7565 
Adds `displayNegative` to `RemainingTimeDisplay` which defaults to true for current behaviour. Can be set to `false` to remove the - sign.
=> feat: make negative sign on remaining time optional

src/js/player.js, src/js/tech/html5.js, src/js/tech/tech.js, test/unit/player.test.js, test/unit/tech/tech.test.js
This changes the default behavior of `player.addRemoteTextTrack()` so text tracks will now automatically be removed on source changes without needing to pass a `manualCleanup: false` option. This also removes a deprecation warning and updates documentation and tests.
=> feat: Change addRemoteTextTrack's manualCleanup option default value to false

docs/guides/faq.md, docs/guides/troubleshooting.md
Minor doc additions for things commonly encountered in Slack/SO etc
=> docs: Add some FAQ entries

src/js/player.js, src/js/tech/html5.js, test/unit/player-fullscreen.test.js
Sometimes iOS Safari enabled native controls on the video el when existing fullscreen, resulting in both the native controls and Video.js controls being visible. Fixes #3762  
* Set `controls` to `false` on the tech el when iOS exits fullscreen, as long as `nativeControlsForTouch` is not being used.
* Not pertinent to the double controls issue, but also fixes the behaviour of the `vjs-ios-native-fs`, which is currently toggling when entering fullscreen and remaining as is on exiting fullscreen. (Although this class may be able to be removed altogether if it wasn't being applied as intended anyway).
=> fix: Guard against Safari adding native controls after fullscreen

docs/translations-needed.md, lang/fr.json
A trailing comma was not noticed before merging in a JSON file, which caused automation to fail. This fixes it.
=> fix(lang): remove trailing comma from fr.json

docs/guides/options.md, src/css/components/_poster.scss, src/js/player.js, test/unit/player.test.js
Adds audioPosterMode option that is false by default. Turning the audioPosterMode on will enable the Poster Viewer experience by hiding the video element and persistently displaying the poster image. If no poster is defined, the video player will be black.
=> feat: Add audioPosterMode option

src/js/tech/html5.js, src/js/tech/tech.js, src/js/tracks/text-track.js, test/unit/tracks/text-track.test.js, test/unit/tracks/text-tracks.test.js
Text tracks currently update on `timeupdate`, which can can be too slow and/or unpredictable for some (edge) cases. This PR switches to using [`requestVideoFrameCallback()`](https://web.dev/requestvideoframecallback-rvfc/) instead, with a fallback to `requestAnimationFrame()`. There was some previous work along these lines with rAF in #2985.
Closes #2985, closes #7026.
* Implements `Tech.requestVideoFrameCallback()` as a fallback to `requestAnimationFrame()` whilst playing.
* Implements `Html5.requestVideoFrameCallback()` if the HTML5 element supports it.
* Switches text track to use this method instead of the `timeupdate` event.
- x ] Feature implemented / Bug fixed
=> feat: Greater text track precision

src/js/utils/mimetypes.js
Since [http-streaming](https://github.com/videojs/http-streaming) plays DASH, adding this feature will allow a DASH source to be provided without necessarily indicating the media type. 
```JavaScript 
player.src('https://domain.com/video.mpd') //👌
```
=> feat: Assume DASH MIME type when an MPD source URL is given

src/js/control-bar/picture-in-picture-toggle.js, src/js/player.js, test/unit/controls.test.js, test/unit/player.test.js
Modify the `audioPosterMode` method to  return a promise and unify `audioOnlyMode` and `audioPosterMode` by turning off one mode when the other mode is turned on.
This change also disables/hides PIP for an audio source and when either of the two audio modes are true
=> refactor: Unify audioOnly mode and audioPoster mode

docs/guides/components.md, src/css/components/_control.scss, src/js/clickable-component.js, src/js/component.js, test/unit/clickable-component.test.js, test/unit/component.test.js
Makes it a little easier to add ad hoc components, particularly buttons. Most significant change is a class to allow buttons that display their control text without having to add styles to unset the default styles. Also allows class(es) and control text to be included as component options for simplicity.
* Adds a `.vjs-visible-text` class for controls. This omits the styles to hide control text, unsets button width and adds some padding.
* Adds `controlText` as an option to `ClickableComponent`, so text can be passed as a setup option.
* Adds `className` as an option to `Component`, so additional classes can be passed as a setup option.
=> feat: Add text button, and component options

test/unit/tracks/text-track-controls.test.js
An incompatibility was introduced between a test written for #7604 and the changes introduced in #7633 - this addresses it to unblock release of 7.19.
Since text tracks no longer rely on the `timeupdate` event (though they still have a `timeupdateHandler` method), triggering the chapter menu item update on `timeupdate` simply did not work. Calling `timeupdateHandler()` manually does.
=> test(text-track-controls): fix failing test caused by incompatibility between PRs

src/css/components/_layout.scss, src/js/player.js, src/js/video.js
Disable all fluid and fill mode CSS when in audio only mode, except for that which adjusts the player's width responsively. This fixes a styling conflict that broke the player UI when both fluid and audio only mode were simultaneously enabled.
=> fix: Audio only mode styling conflicts with fluid mode

src/js/menu/menu-button.js, test/unit/menu.test.js
Fix for issue : https://github.com/videojs/video.js/issues/7688 by @dave105010
Remove role="menu" in html on hidden player options if they are not used (no chapters added or no CC added etc.).
Add/remove role="menu"
=> fix(accessibility): fix broken aria menu

src/js/player.js, test/unit/player.test.js
We have tight coupling in player.js Class Player method resetControlBarUI_(), when using reset() method.
ControlBar component may be not exists or exists on another nesting level.
Fixes #7689
Added condition
=> fix: tight controlbar coupling (#7689)

src/js/video.js
- Export all of the Video.js helpers (from utils) on the Video.js object.
=> feat: export more helpers in videojs object

src/js/mixins/evented.js, test/unit/mixins/evented.test.js
Reverts https://github.com/videojs/video.js/pull/7067 which replaced throwing an error with logging an error. If we get an invalid event type we really should throw because it indicates something has gone wrong.
=> revert: Revert #7067 so we throw an error for invalid event types

src/js/player.js, src/js/tech/tech.js, test/unit/utils/promise.test.js
Remove `Promise` option and any workarounds for platforms without native promise support.
**Note:** Merge with `BREAKING CHANGE` header
=> refactor: Remove workarounds for platforms without native promise support

src/js/big-play-button.js, src/js/live-tracker.js, src/js/player.js, src/js/poster-image.js, test/unit/tracks/text-tracks.test.js, test/unit/utils/log.test.js
Remove any IE-specific code, which is no longer needed once https://github.com/videojs/video.js/pull/7482 is merged to drop build support for IE.
=> chore: Remove IE-specific code

src/js/component.js, src/js/player.js, src/js/video.js, test/unit/component.test.js, test/unit/player.test.js, test/unit/video.test.js
Adds an option to replace player with a clone of the original element on dispose, which has been asked for several times.
* Component accepts an options object. If provided, the component element will be replaced by the element provided at `options.restoreEl`.
* Player passes a `restoreEl` to `super.dispose()` if provided as a player option
* The `videojs()` constructor accepts a `restoreEl` option, which can be any element, or `true` in which case the element the player is initialised on is used.
Docs will need to be added at videojs.com/guides
- [*] Feature implemented / Bug fixed
- [*] Change has been verified in an actual browser (Chrome, Firefox, IE)
- [*] Unit Tests updated or fixed
=> feat: Player can be replaced with original el after dispose()

lang/en.json, src/js/resize-manager.js
According to some HTML validators, the resize manager frame doesn't pass validation because the title attribute is not present.
Please check the below validators for details
1. https://rocketvalidator.com/accessibility-validation/frame-title-unique
2. https://equalizedigital.com/accessibility-checker/iframe-missing-title/
Add 'title' attribute.
=> fix(accessibility): frame must have a title attribute

test/unit/video.test.js
We realized that tests were failing in IE11 and Safari 9 because some new tests introduced in #7722 seem to use unsupported `DocumentFragment` features.
Rather than try to fix that, we will simply not run these tests in IE or Safari. In 8.0, we will not support IE at all or older Safaris.
=> test: stop running placeholder el test in IE and Safari to prevent errors

.github/workflows/lock.yml
Locks issues that have been closed for 60 days.
People occasionally comment on old, closed issues that they are also having the "same issue". This is rarely useful:
* the comment is less likely to be seen or responded to
* it's probably not the _same_ issue, even if a symptom is similar (like a generic error message)
* the assertion that it's "still happening" is usually not presented with any actionable information, such as steps to reproduce
If someone believes they are having the "same" issue, they should create a new issue with their steps to reproduce and include a link to the closed issue.
* Uses [Lock Threads](https://github.com/marketplace/actions/lock-threads) action.
* Locks closed issues after 60 days.
* Does not lock PRs.
* Runs once an hour, as the action processes max 50 …
=> chore: Lock old closed issues

src/js/player.js
The "not supported message" should not be localized in the player class because an "Error Display" class localizes all error messages before showing them to the user.
https://github.com/videojs/video.js/blob/main/src/js/error-display.js#L50
=> fix: error message should not be localized in the player class

src/js/tech/html5.js, test/unit/tech/html5.test.js
The check for `requestAnimationFrameCallback` assumes a video element, which breaks track updates if an audio el is used.
Additional check in htmlt tech constructor.
Fixes #7772
=> fix: HTML5 tech with audio tag shouldn't use requestVideoFrameCallback

src/js/utils/events.js, test/unit/events.test.js
Lighthouse complains if `path` is copied from the event as `Event.path` is deprecated.
Adds `path` to the list of excluded properties.
=> fix: Don't copy deprecated Event.path

src/js/control-bar/playback-rate-menu/playback-rate-menu-button.js, test/unit/control-bar/playback-rate-menu/playback-rate-menu-button.test.js
This comes out of discussion in #7121 and its associated PR, #7193.
Currently, in Video.js 7, the `PlaybackRateMenuButton` will change to the next playback rate when it is clicked, cycling through the list of items. However, this approach has accessibility issues (which were addressed in #7193 as far as I can see) necessitating a workaround.
In Video.js 8, the `PlaybackRateMenuButton` will behave like other buttons when it is clicked: it will open its associated menu persistently. This is considered a **breaking change** because it changes the behavior of a control bar menu button.
I'd love to get feedback from @gkatsev and/or @OwenEdwards on whether or not further accessibility updates are warranted here - or if we could potentially remove the workaround introduced in #7193.
- Remove the …
=> feat: playback rate button now opens the menu rather than changing the playback rate

src/js/tech/html5.js, test/unit/tech/html5.test.js
Fixes #7807
the tech needs to know whether or not the underlying element supports requestVideoFrameCallback before calling setSource
Move checking this.el.tagName === 'VIDEO' ahead of this.setSource()
=> fix: need to determine featuresVideoFrameCallback before setting source

src/css/_utilities.scss, src/css/components/_adaptive.scss, src/css/components/_control-bar.scss, src/css/components/_control.scss, src/css/components/_live.scss, src/css/components/_progress.scss, src/css/components/_time.scss, src/css/components/_volume.scss, src/css/components/menu/_menu-inline.scss, src/js/player.js
_This is [a duplicate PR](https://github.com/videojs/video.js/pull/7811) with changes based off of the `next` branch, instead of `main`, to avoid pulling updates from `7.20.1`._
Remove logic that checks for browser flexbox feature support and any style rules that specifically target the .vjs-no-flex class. We are assuming standard flex support for Video.js 8 and onward.
- Remove flexNotSupported_() and associated call.
- Remove specific style rules that target the .vjs-no-flex class added by the flexNotSupported_()method. Consolidate css rule groups where .vjs-no-flex targeting was removed.
=> refactor: Remove logic and style that accommodates non-flex fallbacks

src/css/components/_control-bar.scss
1. On mobile initialize an audio player
2. Start the playback
3. Wait for the `vjs-user-inactive`
4. Attempt to use the slider to seek through the media
5. Notice that it is no longer possible to use the slider unless you tap the control bar before.
This issue was introduced by #7329 in video.js v7.15.0
The idea is to reset the `pointer-events` to `auto` for the audio player so that the slider can be used on touch devices.
=> fix(control-bar): audio player no longer responds to touch events

.github/workflows/lock.yml
The github action introduced by #7777 in charge of locking old issues runs every hour and is followed by an e-mail. 
The [Lock Threads](https://github.com/dessant/lock-threads) does not seem to allow restricting its execution to a named repo. The proposal would be to execute the action only once a day to avoid spamming those who have a fork of the project.
=> chore(lock-threads): run only daily at 1:00 am, and skip in forks

index.html, sandbox/index.html.example, sandbox/load-media.html.example, src/css/components/_big-play.scss, src/css/components/_title-bar.scss, src/css/video-js.scss, src/js/player.js, src/js/title-bar.js, test/unit/title-bar.test.js
This PR mostly adopts [the Brightcove videojs-dock plugin](https://github.com/brightcove/videojs-dock) as a first-class feature of Video.js.
One key difference is the lack of a "shelf" element as an empty `<div>` without a clear purpose felt a bit unnecessary in the context of Video.js itself (and may not survive in the Brightcove Player either).
This removes the `vjs-big-play-centered` class and moves the Big Play Button to the center of the player by default to make room for the title bar. This is a more common UI convention in 2022.
- Add `TitleBar` component, which is a new default child of the player.
- The component is empty (and, therefore, hidden) by default.
- Providing the `Player` with video metadata via `loadMedia` will automatically populate the `TitleBar` with a `title` and …
=> feat: add a new title bar component

sandbox/noUITitleAttributes.html.example, src/css/components/_layout.scss, src/js/player.js, src/js/tech/setup-sourceset.js, src/js/tech/tech.js, src/js/utils/url.js, test/unit/player.test.js, test/unit/sourceset.test.js
Remove references to Flash and SWF support throughout the project. In cases where logic facilitated support for either deprecated feature, it is either removed or amended.
- Update comments to remove mention of Flash/SWF features.
- Remove relevant features from existing demos.
- Update player and sourceset unit tests to use `youtube` instead of `flash` for sample tech.
- Change .video-js css display rule to `inline-block` (it's not clear from the comment if this was related to Flash or "content flashing" but it seems to no longer be relevant either way when moving into fullscreen mode).
- Remove `stageclick` event listener and associated handler. This is related to SWF features.
- Logic that is either actively used during the basic player lifecycle or has broad utility outside Flash …
=> feat: Remove references and logic related to Flash and SWF

lang/fr.json
When implementing video.js's option `language` for `fr`, we noticed that "Picture-in-Picture" wasn't being translated properly. We noticed [#7589](https://github.com/videojs/video.js/pull/7589) introduced this issue within the `fr.json` file.
Please refer to issue #7847
=> fix(lang): fixes key spacing within fr.json file

src/js/tech/html5.js, test/unit/tech/html5.test.js
Safari's `requestVideoFrameCallback` is (intentionally?) broken when DRM is playing, so in that case use the fallback with `requestAnimationFrame` instead.
* Check for the presence of `<video>.webkitKeys`, and use fallback if so.
* This will case false positives in the case that a DRM source is loaded and then a non-DRM source is loaded, becuse `webkitKeys` remains. 
* The test isn't prefect - rather than set up a test with an actual DRM source, `webkitKeys` is set to an object, however since Safai doesn't allow the property to be written, the test runs on every other browser.
=> fix: No requestVideoFrameCallback on Safari with DRM

src/js/slider/slider.js, src/js/utils/dom.js, test/unit/utils/dom.test.js
Amend the `createEl` method on the Dom class to remove logic that allows `role`,` type`, and `aria-*` attributes to be set as part of the properties object on an element.
**Changes include:**
- Remove conditional statement from `createEl` method that checks for nonstandard attributes in the properties object and sets them as element attributes.
- Remove duplicate `tabIndex` attribute assignment in `Slider.creatEl` method.
=> feature: Remove support for setting nonstandard attributes as props

sandbox/noUITitleAttributes.html.example
Updates example to use https URLs, as the build previews are delivered with https. Resolves netlify warning.
=> chore(docs): use https URLs in noUITitleAtttributes example

src/js/player.js
Removes the fallback for `Element.closest()` which was only needed for IE.
=> feat: Remove fallback for Element.closest()

src/js/player.js, test/unit/player.test.js, test/unit/sourceset.test.js
This means that a retryOnError is removed and is no longer needed for
this behavior, which means that during source selection, if a source
fails, it'll try the next source that's available, to match the video
element.
BREAKING CHANGE: remove retryOnError option, turn it on by default
=> feat: make retryOnError be the default

src/js/tracks/text-track.js, test/unit/tracks/text-track.test.js
A couple more edge cases have come up where usng rvfc or raf for more accurate cue changes isn't working., with audio in video els (there's already handling for audio in audio) and background tabs.
Use the `timeupdate` event as well as the rvfc and raf callbacks to check cues. This is a bit overkill for "usual" playback but avoids edge cases. If the more preceise callback trigger first the cue will update but the timeupdate event should catch any that were missed, notwithstanding that `timeupdate` was always somewhat unpredictable.
Should fix #7910 (audio in video els and Samsung being weird) and #7902 (no updates off screen). 
Will need to be added to `next`.
=> fix: Use timeupdate as well as rvfc/raf for cuechanges

src/js/tech/tech.js, test/unit/tech/tech.test.js
Don't call tech.paused() in the requestVideoFrameCallback fallback if the tech is not ready. I've seen this is an issue in the Flash tech, as its methods are set up after the swf loads. Yes, Flash, it's 2022, but in theory another tech could be impacted if it's also async.
=> fix: allow for techs that init slowly in rvfc

src/js/extend.js
Related to #7943, see that for details.
- Deprecates the `extend` function
=> feat(deprecation): deprecate the extend function

src/js/event-target.js
EventTarget.queueTrigger() method contains a timeout code that should clear map when map.size === 0. However, It looks like 
this statement will never trigger right now because the map has always size value bigger than 0.
The last timeout should delete the type from the map.
=> fix: last timeout in queueTrigger() never clears  map

src/js/component.js, src/js/control-bar/progress-control/mouse-time-display.js, src/js/control-bar/progress-control/play-progress-bar.js, src/js/control-bar/progress-control/progress-control.js, src/js/control-bar/progress-control/seek-bar.js, src/js/control-bar/progress-control/time-tooltip.js, src/js/control-bar/text-track-controls/descriptions-button.js, src/js/control-bar/track-button.js, src/js/control-bar/volume-control/mouse-volume-level-display.js, src/js/control-bar/volume-control/volume-control.js, src/js/control-bar/volume-control/volume-level-tooltip.js, src/js/mixins/evented.js, src/js/player.js, src/js/tech/tech.js, src/js/tracks/text-track-display.js, src/js/tracks/text-track.js, src/js/utils/fn.js, src/js/video.js, test/unit/utils/fn.test.js, test/unit/videojs-integration.test.js
The `utils/fn.bind` function will be exposed in Video.js 8 because `fn` is exposed as `videojs.fn`. We don't want people using it, but it cannot be removed without breaking the Video.js event system.
This PR adds a `_` at the end of its name to indicate that it is private.
No external updates should be needed as it was not _directly_ exposed. The previously-supported `videojs.bind` has been deprecated.
- Rename `utils/fn.bind` to `utils/fn.bind_`
- Update usages
=> refactor: rename fn.bind to fn.bind_ to strongly indicate it should not be used externally

src/js/big-play-button.js, src/js/clickable-component.js, src/js/control-bar/audio-track-controls/audio-track-button.js, src/js/control-bar/fullscreen-toggle.js, src/js/control-bar/mute-toggle.js, src/js/control-bar/picture-in-picture-toggle.js, src/js/control-bar/play-toggle.js, src/js/control-bar/playback-rate-menu/playback-rate-menu-button.js, src/js/control-bar/seek-to-live.js, src/js/control-bar/text-track-controls/captions-button.js, src/js/control-bar/text-track-controls/chapters-button.js, src/js/control-bar/text-track-controls/descriptions-button.js, src/js/control-bar/text-track-controls/subs-caps-button.js, src/js/control-bar/text-track-controls/subtitles-button.js, src/js/control-bar/time-controls/current-time-display.js, src/js/control-bar/time-controls/duration-display.js, src/js/control-bar/time-controls/remaining-time-display.js, src/js/control-bar/time-controls/time-display.js
The controlText_ property should have a protected access modifier.
The PR is related to https://github.com/videojs/video.js/issues/7971
=> fix(jsdoc): controlText_ should have a protected access modifier.

src/css/components/_progress.scss, src/css/components/_volume.scss
[Please describe the change as necessary.
The bar is not centered in video control section
[issues7989](https://github.com/videojs/video.js/issues/7989)
=> fix(control-bar): align center

package-lock.json, package.json
With 8.0.0 installed, you'll see the following when running `npm ls --depth=0`:
```
npm ERR! peer dep missing: video.js@^6 || ^7, required by videojs-contrib-quality-levels@2.2.0
```
This is because videojs-contrib-quality-levels 2.2.0 is not listed as being compatible with Video.js 8.0.0 - videojs-contrib-quality-levels 2.2.1 fixes this issue.
Upgrade to videojs-contrib-quality-levels 2.2.1
=> chore(package): update videojs-contrib-quality-levels to 2.2.1

src/css/components/_poster.scss
Adds styling for the `img` el in the poster's `picture` so it scales correctly.
=> fix: Add poster size styles

.github/workflows/lock.yml
- [Updates the lockthreads action](https://github.com/dessant/lock-threads/compare/e460dfe..c1b35ae) to resolve deprecation warnings like https://github.com/videojs/video.js/actions/runs/3666803961
- Also sets to run only twice a week to reduce noise in the acitons list. N.B. This does nothing for the occasional rate limiting errors. They're limits hit while the task runs, not because of how often it runs.
=> chore: Update lock threads dependency

package-lock.json, package.json
Pulls in this change https://github.com/videojs/videojs-contrib-quality-levels/pull/142, which fixes an incompatibility between video.js v8 and contrib-quality-levels.
=> fix(package): Upgrade to videojs-contrib-quality-levels 3.0.0

src/js/tech/html5.js, test/unit/tech/html5.test.js
#7979 removed a check for an old OS X version but incorrectly, causing iPhones not to use their native fullscreen.
Returns trues for any video el with `webkitEnterFullScreen()`
=> fix: Ensures iOS can use native fullscreen

lang/en.json
Removes duplicate `Exit Fullscreen`
=> fix(lang): Remove duplicate entry in en.json

src/js/player.js, test/unit/player-fullscreen.test.js
Updates video.js to exit PiP when requesting fullscreen per [this issue](https://github.com/videojs/video.js/issues/7921).
- A check at the top of `requestFullscreen` for `isInPictureInPicture`, calling `exitPictureInPicture` if so.
Should more be done here?
=> fix: Exit PIP if entering fullscreen

src/js/tracks/text-track-display.js, test/unit/tracks/text-track-display.test.js
The window "orientationchange" event is deprecated and
it should be only used when Screen Orientation API is not supported.
The Text track display should use Screen Orientation "change" event and fallback to window "orientationchange" event if the Screen9 Orientation API is not supported.
- introduces Screen Orientation API for detecting orientation change in TextTrackDisplay class.
=> fix:  use Screen Orientation API where supported

src/js/tracks/text-track.js, test/unit/tracks/text-track.test.js
We had some special handling of cues which have equal start and end times, so they would be considered active 0.5 after they start/end. Cues with equal start and end times are not valid; the end time must be greater. However some painton style VTT in the wild contain many such cues, resulting in all such with a 0.5 seconds being displayed.
We thought this handling might still be needed for ID3 cues as ID3 only has a start time, but it's not: on adding to the track [the `endTime` is set](https://github.com/videojs/http-streaming/blob/9db9e99f1568049502058ce8312aff2dae77beab/src/util/text-tracks.js#L213) to the next cue's `startTime` or the video duration.
Removes the handling of these cues. A cue with equal start and end times is not strictly ignored, but it will only render if active cues …
=> fix: remove unnecessary handling of invalid cues

docs/translations-needed.md, lang/ar.json, lang/de.json, lang/en.json, lang/es.json, lang/fr.json, lang/it.json, lang/ja.json, lang/ko.json, lang/zh-CN.json, lang/zh-TW.json, src/css/components/_captions-settings.scss, src/js/tracks/text-track-settings.js, test/unit/tracks/text-track-settings.test.js
Based off of an audit that a Brightcove client received, we are updating the text tracks settings menu with improved labels. This change is regarding Web Content Accessibility Guidelines (WCAG). 
- Labels added/improved to fields in the settings menu
- CSS so labels are displayed next to inputs
- Translations for labels
- Updates docs regarding missing translations.
=> feat: improved text tracks settings labels

package-lock.json, package.json, sandbox/icons.html.example, src/css/components/_audio.scss, src/css/components/_subs-caps.scss
videojs-font v4.0.0 introduces new icons, and changed the unicode strings used to target the icon webfont using css. 
This change upgrades the version of videojs-font to 4.0.0 and updates any css that references unicode strings from the previous version of videojs-font. 
- upgrade videojs-font to 4.0.0
- update css that references unicode strings from previous videojs-font version
- update `icons.html.example` to include all the icons from videojs-font 4.0.0
=> chore: upgrade videojs-font to 4.0.0

src/js/poster-image.js, test/unit/poster.test.js
If there is no poster source, an img el can't be present as it would be invalid.
Use a div (again) as the top level element of the PosterImage, to keep position in the DOM. Insert/remove the picture/img els when a poster source is set/unset. 
Fixes #8122
=> fix: Remove img el when there's no poster source

build/translations.js, docs/translations-needed.md, lang/en-GB.json
The default text in our translation system are English strings, so having a full JSON file for a variant of English that would only modifiy one or two strigns would be wasteful.
This changes the script that updates translations-needed.md to not highlight the number of "missing" translations in a en-* file and just state it needs to be manually checked instead.
Fixes #8105
=> chore: Update translations script to special case en-GB

CHANGELOG.md
I didn't have the 8.0.4 tag locally when I ran the versioning step for 8.1.0, so the changelog included changes from 8.0.4.
=> docs: Remove redundant 8.0.4 changes from 8.1.0 changelog

COLLABORATOR_GUIDE.md
Update release flow in collaborator guide md
=> chore(documentation): Update release flow in collaborator guide md

src/js/control-bar/play-toggle.js, src/js/player.js, test/unit/player-play.test.js
During native playback in Safari (desktop or iOS) if the user reaches the end of content in fullscreen, the replay button will no longer function with a single click. Meaning, the button will work and change state to `playing` however the video does not restart. It seems to be an issue with the content not ending correctly as the `ended` event is firing, however `video.ended` is returning `false`. Since it's native, we don't have the option of calling `endOfStream` on the mediaSource.
If we detect native playback from the `tech` and the play toggle is still in the replay state, we can manually do a seek to 0 and call play.
=> fix: replay button broken for native playback

src/js/player.js, test/unit/player-play.test.js
Cherry-pick for 7.x branch. See: https://github.com/videojs/video.js/pull/8142
Detect native playback (Safari and iOS) and reset the progress bar on a play call if we have ended the content.
=> fix: replay button broken for native playback (#8142)

.github/ISSUE_TEMPLATE/bug_report.yaml
* Removes `bug` as a default label. `needs triage` remains.
* Makes reduced test case a required field.
* Minor tweaks to descriptions.
=> chore: update issue template

src/js/control-bar/skip-buttons/skip-backward.js, src/js/control-bar/skip-buttons/skip-forward.js, src/js/control-bar/text-track-controls/caption-settings-menu-item.js, src/js/control-bar/text-track-controls/off-text-track-menu-item.js, src/js/loading-spinner.js, src/js/tracks/text-track-settings.js, test/unit/control-bar/skip-buttons/skip-backward-button.test.js, test/unit/control-bar/skip-buttons/skip-forward-button.test.js, test/unit/control-bar/text-track-controls/text-track-menu-item.test.js, test/unit/loading-spinner.test.js, test/unit/tracks/text-track-settings.test.js
Components should update their text on `languagechange`, but some weren't where they had behaviour other than that inherited from `ClickableComponent`
Added `handleLanguagechange()` behaviour for `LoadingSpinner`, `SkipForward`, `SkipBackward`, `CaptionSettingsMenuItem`, `OffTextTrackMenuItem` and `TextTrackSettings`
=> fix: Ensure additional components update on languagechange

src/js/tracks/text-track-display.js, test/unit/tracks/text-track-display.test.js
Text track display does not always overlay a video which may generate a different text track size and position across different browsers and devices.
The text track display always overlays a video.
=> feat: text track display overlays a video

src/js/video.js, test/unit/player.test.js
This PR fixes the missing return in the `videojs.registerComponent` function to be in line with the documentation, see
https://github.com/videojs/video.js/blob/1491d71b26a407111104dde7dbbbc0ee49b4c0c8/src/js/video.js#L304-L320
```javascript
class CustomComponent extends videojs.getComponent('Component'){}
export default videojs.registerComponent(CustomComponent.name, CustomComponent);
```
- add the missing return statement
- add test case
=> fix(videojs): missing return in registerComponent

src/js/player.js, test/unit/player.test.js
This PR fixes the deletion of the `crossOrigin` value when `loadMedia` is called.
Fixes: https://github.com/videojs/video.js/issues/8086
- stores the value of `crossOrigin` before `reset` deletes it
- restores the value of `crossOrigin` after `reset` has been called
- unit test to verify that the value of crossOrigin is restored :
- when the `crossOrigin` method is called before `loadMedia`
- when the `crossOrigin` value is passed via the options then `loadMedia` is called
- when the video tag contains the `crossOrigin` property then `loadMedia` is called
=> fix: loss of crossOrigin value when loadMedia is called

src/css/components/_audio.scss, src/js/control-bar/audio-track-controls/audio-track-menu-item.js
On Firefox/Chrome browser the HLS stream that contains an audio track with a description show AD icon in the menu list.
However, The same stream on Safari doesn't have the AD icon.
Safari without VHS (in native mode) creates an audio track with a `kind` attribute value equal to "description". 
Unfortunately, video.js handles track kind attribute value equal to "main-desc" only. 
Add support for `kind: "description"`
=> fix: audio description track doesn't have icon on Safari browser

src/js/player.js, test/unit/sourceset.test.js
This PR fixes #8255 the call to `techGet_`.
- rename `techGet` to `techGet_`
- add test case
=> fix(player): techGet is undefined

src/js/control-bar/progress-control/seek-bar.js, test/unit/controls.test.js, test/unit/reset-ui.test.js
This PR fixes the error thrown when using the `seekBar` after the player has been reset.
[seek-bar.webm](https://user-images.githubusercontent.com/34163393/235620093-c1e86155-c67b-478d-8d40-1b445047f0d2.webm)
- short-circuit the `handleMouseMove` function if the `duration` is `NaN`
- update a `reset-ui` test case to reflect the player UI and ensure that the rest of the `handleMouseMove` function is not executed if `duration` is `NaN`
- update a `controls` test case to meet the expected behavior
=> fix(seek-bar): error when scrubbing after player reset

src/js/control-bar/skip-buttons/skip-forward.js, test/unit/control-bar/skip-buttons/skip-forward-button.test.js
This PR fixes the error thrown when clicking the `skip-forward` button after the player has been reset.
[skip-forward.webm](https://user-images.githubusercontent.com/34163393/235620462-c2fc7814-2dc7-45dd-bc0f-5cc05e75e824.webm)
- short-circuit the `handleClick` function if the `duration` is `NaN`
- add a test case
=> fix(skip-forward): error when clicking after player reset

src/js/player.js, test/unit/player.test.js
This PR provides a workaround for the `load` method that fails to reset the media element to its initial state when the VHS is used.
This issue affects all devices using VHS tech to play Dash and HLS. It does not affect the playback of media that does not require VHS, such as mp4 or HLS on Apple devices.
This fix does not cover the case when the load method is called directly from the mediaElement.
[Screencast from 13. 05. 23 21:00:59.webm](https://github.com/videojs/video.js/assets/34163393/7d6d5e6c-6f92-4f03-b4fa-1e7a7327b88b)
```javascript
player.src('https://d2zihajmogu5jn.cloudfront.net/bipbop-advanced/bipbop_16x9_variant.m3u8');
player.cache_.src;
// "https://d2zihajmogu5jn.cloudfront.net/bipbop-advanced/bipbop_16x9_variant.m3u8"
player.cache_.source;
// { src: …
```
=> fix(player): load method fails to reset the media element

src/js/component.js, src/js/mixins/evented.js, src/js/player.js, src/js/utils/dom.js, test/unit/events.test.js, test/unit/player.test.js, test/unit/tech/tech-faker.js, tsconfig.json
Corrects some jsodc in Player, especially
- getter/setters not specifying that they won't return when setting
- getter/setters that stated they could return the player, very old behaviour
=> fix(jsdoc): Corrections to jsdoc

src/js/player.js, test/unit/player.test.js
This PR fixes the delay in the update of `cache_.currentTime`. Updating `cache_.currentTime` as soon as the `currentTime` is set avoids having to wait for the `timeupdate` event, which results in:
- making `cache_.currentTime` more reliable
- updating the `progress bar` on mouse up after dragging when the media is paused.
See also: #6232, #6234, #6370, #6372, partially covers #8283
- Refactor `currentTime` method to decrease the indentation level
- Updates `cache_.currentTime` when `currentTime` is used as a setter and the `seconds` parameter has a value that can be converted to a `Number`
=> fix(player): cache_.currentTime is not updated when the current time is set

lang/fa.json
update fa translation
- No content
- Color
- Opacity
- Text Background
- Caption Area Background
- Playing in Picture-in-Picture
fa.json add an option called enableSmoothSeeking
- [ *] Feature implemented / Bug fixed
=> fix(lang): Update fa translation

src/js/player.js
It looks like after #8274 was merged, tests began failing consistently in Safari. Upon investigation, it seems that code in the test harness was hitting `load()` before a fake tech had been created, causing it to throw and then the test to time out.
Oddly enough, the tests didn't fail in the PR... only after it was merged! 🤷 
- Do a `null` check for the `tech_` before inspecting it.
=> test: fix Safari test failures

tsconfig.json
Removes `resolveJsonModule` from tsconfig.json, added in #8277.
Although adding that resolves one tsc complaint (relating to importing the version from 
package.json), for some reason with it present tsc will include `src/js` in the paths within 
`dist/types` 
- [xx] Feature implemented / Bug fixed
=> fix(types): revert resolveJsonModule in tsconfig

package-lock.json, package.json
Fixed a warning when using quality-levels 3.x which used mergeOptions. It prepare for 9.0.0
update videojs-contrib-quality-levels to ^4.0.0 in package.json
=> fix(package): update videojs-contrib-quality-levels to 4.0.0 to eliminate deprecation warning

src/css/components/_loading.scss
This PR fixes the responsiveness of the `loading spinner` when the default font size of `.video-js` is modified.
[loading-spinner.webm](https://github.com/videojs/video.js/assets/34163393/99b4947a-f6d2-495b-b132-30752ba0a706)
- Use `em` instead of `px` to make the component responsive
=> fix: fix loading spinner responsiveness when default font size is modified

src/css/components/_captions-settings.scss
This PR fixes the responsiveness of the `text track settings` when the default font size of `.video-js` is modified and only the label size was updated.
[text-track-settings.webm](https://github.com/videojs/video.js/assets/34163393/62696880-919d-4be7-bd52-0ab449e16d28)
- Remove css that was no longer useful since labels are no longer hidden, refer to #8101
- Use `em` instead of `px` to make sizes responsive
=> fix: fix text track settings responsiveness when default font size is modified

lang/pt-PT.json
Adds Portuguese translation for skip buttons.
=> fix(lang): add skip button text for Portuguese

src/css/components/_progress.scss
This PR fixes when the mouse hovers over the `play-progress` svg icon, the `mouse-time-display` bar appears above it.
[Screencast from 02. 07. 23 20:16:42.webm](https://github.com/videojs/video.js/assets/34163393/12440cbf-03b5-402c-a676-5ad55563d857)
- adds `z-index` to avoid overlap
=> fix(progress): mouse-time-display overlaps the play-progress svg icon

src/js/control-bar/play-toggle.js
This PR fixes #8336, where the svg `play` icon is missing when player is initialized with class `vjs-has-started`.
- add `setIcon` to the `play-toggle` component constructor
=> fix(play-toggle): missing svg play icon

src/js/player.js, test/unit/player.test.js
As noted in https://groups.google.com/a/chromium.org/g/blink-dev/c/JTPl7fM64Lc, we should use "pagehide" not "unload" JS event to monitor when PiP window gets closed.
=> fix: Use pagehide instead of unload for PiP

src/css/components/_layout.scss
Works around and issue with older Safari versions (=<15.6) with sizing the player fullscreen with `inline-block`.
Fixes #8339
Sets `display: block` in fullscreen.
=> fix: Fullscreen styles for older Safari

src/js/player.js, src/js/utils/dom.js, test/unit/player.test.js, test/unit/utils/dom.test.js
Document Picture-in-Picture API owners are [removing `copyStyleSheets` option](https://github.com/WICG/document-picture-in-picture/pull/79) as it can be done in JavaScript. This PR removes this option and copy all style sheets internally to the PiP window.
@mister-ben Please review.
=> fix: Don't use copyStyleSheets with documentPIP

src/js/player.js, src/js/tracks/text-track-display.js, src/js/video.js, test/unit/player.test.js, test/unit/tracks/text-track-display.test.js, test/unit/utils/custom-element.test.js, test/unit/video.test.js
Some features incompatible with Chrome 53 have recently been added.
Replaces or skips code using newer features.
=> fix: Chrome 53 compatibility

test/unit/utils/dom.test.js
Safari versions less than 14 have a broken `document.styleSheets` - not all style elements are included, which breaks a recent test. We're currently running tests on Brpwserstack on Safari 12 on main.
Since we use the `copyStyleSheets` function only in browsers that support documentPictureInPicture, this simply skips the test on Safari < 14. Should Safari implement documentPictureInPicture in a future update this isn't a concern as `document.styleSheets` behaves properly on 14+.
=> fix(tests): Skip a test on old Safari

package-lock.json, package.json, src/js/tracks/text-track.js, test/unit/tracks/text-track.test.js
This was causing a bug when it came to VTT Cue positioning. This check was never true becasue the `window` instances of the VTTCue being checked, and the `window` instance here are never the same.
A different way to check if the property being used is indeed a VTTCue.
=> fix: Check for VTTCue

src/js/utils/dom.js, test/unit/utils/dom.test.js
Followup to #8356. The issue with older Safari with `document.styleSheets` is a little different than thought. The problem is that Safari doesn't necessarily return rules verbatim, so a text comparison wasn't working. A rule with a shorthand property like `background: white;` is returned as `background-color: white;`. 
Changes the test to use a rule that won't be changed.
Revert skipping the test on Safari from #8356 as we can make that test work after all.
Change copyStyleSheets to use `styleSheet.media.mediaText` when setting media. On old Safari this has to be a string, other browsers allow the MediaList object to be set.
Test ran on browserstack passed here:
https://github.com/mister-ben/video.js/actions/runs/5600546784/jobs/10243092934
=> fix(tests): Fixes for old Safari

src/css/components/_captions-settings.scss, src/css/components/_loading.scss, src/css/components/_text-track.scss, src/css/components/_title-bar.scss
When an error occurs, only the error screen should be displayed to maintain visual consistency.
- Hides the Title Bar
- Hides the Loading Spinner
- Hides the Captions Settings
- Hides the Text Track Display
=> fix(error-display): avoids displaying visual components when an error occurs

src/js/utils/create-logger.js, test/unit/utils/log.test.js
- Added the `createNewLogger` method, to create a logger without a naming chain.
- Added optional custom `delimiter` and custom `styles`.
- Several improvements in jsDoc for proper types(d.ts) generation.
=> Enhanced logger

src/js/tracks/text-track.js
Fixes issue with sizing captions in #8425.
Changes test to check for presence of `getCueAsHTML` instead of the constructor name, as the constructor name is changed when minified.
Open to suggested for a test for this, since the issue only manifested when minified.
=> fix: Resolves captions sizing issue when minified

src/js/player.js, test/unit/player.test.js
Fixes #8409, when both the media URL and the poster return a response other than 200. The media error is overwritten by an empty error, leaving the player in an inconsistent state.
[Screencast from 20. 08. 23 18:35:52.webm](https://github.com/videojs/video.js/assets/34163393/f69976f6-0509-4c3a-854a-185c37386f23)
- add a condition to `handleTechError_` to ensure that the `error` is truthy
- add a test case
=> fix(error): chromium reset mediaError when the poster is invalid

src/css/components/_control-bar.scss
The control bar is not displayed correctly when the display is locked because `.vjs-lock-showing` uses `display` `block` instead of `flex`.
- use `display` `flex` instead of `display` `block` when the control bar has `.vjs-lock-showing` class
- ensure that the control bar is not displayed if the `player` has classes:
- `.vjs-controls-disabled`
- `.vjs-using-native-controls`
- `.vjs-error`
=> fix(control-bar): incorrect display when control bar display is locked

src/js/component.js, src/js/event-target.js, src/js/plugin.js, src/js/tech/tech.js, src/js/tracks/audio-track-list.js, src/js/tracks/html-track-element.js, src/js/tracks/text-track.js, src/js/tracks/track-list.js, src/js/video.js
Fixes #8301
Fix exported types.
=> fix(types): Fix issues in exported types

src/js/component.js, src/js/player.js, src/js/video.js
These accept and return the component/plugin class rather than an instance of the class. Currently, typescript will throw  `TS2345: Argument of type 'typeof MyComponent' is not assignable to parameter of type 'Component'.` when registering a component.
jsdoc updates
=> fix(types): use typeof for registerComponent and registerPlugin

package-lock.json, package.json
update VHS and mux.js versions
=> chore: update VHS and mux.js versions

CONTRIBUTING.md
I found an incomplete sentence while trying to learn how to make my first open source commit. I figured I'd fix it and help guide newcomers to include as much information as possible.
Fixed an incomplete sentence within the contributing readme.
=> chore: Fixed an incomplete sentence in contributing guide

src/js/utils/browser.js
On some Android phones, 'window. navigator. userAgentData' may be '{}', resulting in IS_ANDROID=UAD. platform==='Android' being false
=> fix: adds workaround for non-spec-compliant userAgentData

src/js/error-display.js, test/unit/error-display.test.js
When consecutive errors occur, the `ErrorDisplay` component is not updated with the new error message. This results in an inconsistent state between the `player.error` and `player.errorDisplay.contentEl().textContent`.
|                         | player.error() | player.errorDisplay.content() | player.errorDisplay.contentEl().textContent |
| ----------------------- | -------------- | ----------------------------- | ------------------------------------------- |
| player.error('Error 1') | Error 1 ✔️      | Error 1 ✔️                     | Error 1 ✔️                                   |
| player.error('Error 2') | Error 2 ✔️      | Error 2 ✔️                     | Error 1 ❌                                  |
An example of a use case where updating the error message is useful is :
- user …
=> fix(error-display): update display on consecutive errors

src/css/components/_big-play.scss
This issue happen when the `player` has the class `vjs-show-big-play-button-on-pause` and a `seek` occurs, resulting in the `loadingSpinner` being hidden behind the `bigPlayButton`.
[Screencast from 04. 11. 23 18:56:50.webm](https://github.com/videojs/video.js/assets/34163393/fabc6f3d-a3f5-4409-81dd-8ec12b230ff0)
- Avoids displaying `bigPlayButton` while `seeking`
=> fix(big-play-button): component remains displayed when seeking

src/js/player.js, test/unit/player.test.js, test/unit/reset-ui.test.js
When `player.reset` is called, the `errorDisplay` component is not reset, and neither is `player.error`.
[Screencast from 04. 11. 23 17:08:14.webm](https://github.com/videojs/video.js/assets/34163393/1b6f22d8-d3f3-4167-aa72-790265e24d96)
- Sets `player.error` to `null`, so that the `player.errorDisplay` and `player.error` are correctly reset.
- Adds an `error` function to the `testPlayer` stub to prevent tests from failing.
=> fix(error-display): component remains displayed after player reset

src/css/components/_big-play.scss
This issue occurs when the `player` has the class `vjs-show-big-play-button-on-pause` and playback has started and then been set to `pause` and an `error` occurs.
[Screencast from 04. 11. 23 18:16:08.webm](https://github.com/videojs/video.js/assets/34163393/6b432f59-4fe6-45aa-a0ef-fc62947be087)
- Avoids displaying `big-play-button` on error
=> fix(big-play-button): component remains displayed after an error

src/js/player.js, test/unit/reset-ui.test.js
When `player.reset` is called the `titleBar` component is not reset.
[Screencast from 04. 11. 23 17:03:48.webm](https://github.com/videojs/video.js/assets/34163393/e78d6088-ef4f-41f1-8ec9-36ed7ffa9725)
- Sets the properties `title` and `description` to `undefined` when `player.titleBar.update` is called so that the component is properly reset.
=> fix(title-bar): component remains displayed after player reset

src/js/component.js
Hello! We're using videojs but since the upgrade to v8, we've ran into some typing issues that we had to patch with @ts-ignore and such.
This PR fixes the issues we had with the .off() function always requiring a second param for function and the issues we have with the videojs.getComponent('Component') not returning the right type.
I'm not sure how to build from the jsdoc into the .d.ts files to check that the generated types are correct but I think these changes might work.
I'd also like to help fixing the missing ".remoteTextTracks()" function on the Player type and the missing export for video player options but I don't know how. If you give me some pointers, I'd be glad to help with this
- remove the fn argument as required on the off function
- change the returned type of the …
=> fix(types): Minor fix for types

src/js/player.js, test/unit/player.test.js
Allows CSS classes to be reset when `player.reset` is called, so that the player is close to its initial state.
- remove `vjs-playing`
- add `vjs-paused`
=> fix(player): reset CSS classes at player.reset

src/css/components/_loading.scss
Allows to change the border size of the `loading-spinner` component without having to reflect the border size in pseudo-element's margin.
[Screencast from 19. 07. 23 18:08:10.webm](https://github.com/videojs/video.js/assets/34163393/c8432886-ff23-4988-b887-23f3ca1b2c6c)
- uses display `flex` to facilitate centering of pseudo-elements
- deletes the pseudo-elements `margin`
=> fix(loading-spinner): border size customization

src/js/player.js
`seekable`, `seeking`, `ended`, `networkState`, `readyState` are not visible for typescript.
Move getters declarations directly to the player class.
=> chore: update player public interface for types visibility

package-lock.json, package.json
Update videojs/http-streaming to v3.9.0 https://github.com/videojs/http-streaming/releases/tag/v3.9.0
This includes a feature in VHS that enhances correlation between `usable` keys returned from the CDM and keyIds in the manifest.
Update package.json
=> feat: update VHS to v3.9.0

src/js/control-bar/skip-buttons/skip-forward.js
Got a complaint from a customer about the Wave tool being mad at some empty button.
Somehow the skip-backward button does have a default controlText. only the forward one was missing it.
Add a default controlText for the button component
| Before | After |
|--------|--------|
| <img width="1138" alt="image" src="https://github.com/videojs/video.js/assets/346835/7fefa721-74f2-407f-a4e5-6182e8a8cbf4"> | <img width="379" alt="image" src="https://github.com/videojs/video.js/assets/346835/2e2833c9-d732-49ea-9c22-73c893548083"> |
=> Fix skip-forward button accessibility issue

src/js/control-bar/progress-control/seek-bar.js, src/js/control-bar/time-controls/time-display.js, src/js/player.js, test/unit/player.test.js
This PR adds a player option called `enableSmoothSeeking`, which is `false` by default, to provide a smoother seeking experience on mobile and desktop devices.
[player-smooth-seek-browserstack.webm](https://github.com/videojs/video.js/assets/34163393/0f1fc92b-58bf-4303-9b00-c5c92585adb7)
This PR includes the fix #8285 and should fix #8283.
```javascript
// Enables the smooth seeking
const player = videojs('player', {enableSmoothSeeking: true});
// Disable the smooth seeking
player.options({enableSmoothSeeking: false});
```
- **player.js** add an `option` called `enableSmoothSeeking`
- **time-display.js** add a listener to the `seeking` event if `enableSmoothSeeking` is `true` allowing to update the `CurrentTimeDisplay` and `RemainingTimeDisplay` in real time
- **seek-bar.js** `update` the …
=> feat: Seek bar smooth seeking

src/css/components/_error.scss
Modify _error:
-Remove the ‘x’ element from the error modal.
Remove not required  pseudo-class on error modal.
Remove pseudo-class :before on vjs-error-display.
=> feat(error): remove confusing decorative X from error display modal

src/js/tracks/text-track-settings.js, test/unit/tracks/text-track-settings.test.js
Removes two messages in Chrome's issues tab relating to the text track settings
- _A form field element should have an id or name attribute_
- _No label associated with a form field_
Adds an `id` to each `<select>`, and sets the `id` as the `for` on associated `<label>`s.
=> fix: Fixes form markup in text track settings

src/js/utils/browser.js
SmartTV user agent strings were being detected by `videojs.browser` as Safari.
Checking the user agent string for `Tizen` and `WebOS` then checking for those flags when deducing whether the browser is actually Safari.
=> fix: browser util flagging smart TV as Safari

src/js/error-display.js, src/js/modal-dialog.js, test/unit/error-display.test.js
This recent change closes the error modal and opens it again inorder to  ensure that the error display component is updated with the new error message when consecutive errors occur.
But when this is used with the videojs-errors plugin, no error is displayed after the second error occurs. This is because [when the error display is closed ](https://github.com/videojs/video.js/blob/main/src/js/error-display.js#L27)after the second error, error is cleared and set to null [here](https://github.com/videojs/videojs-errors/blob/main/src/plugin.js#L302).
The suggested change is to just update the modal's content with the latest error message instead of closing and opening the error display.
=> fix: error-display

src/js/player.js
Update `enterpictureinpicture` event to send window metadata on trigger.
=> chore: update pip enter event with window metadata

src/js/consts/errors.js
Add additional errors to the video.js error interface regarding ads.
=> chore: additional vjs ad errors

src/js/consts/errors.js
Fix a nit typo in the errors const.
=> fix: typo in error const

src/js/consts/errors.js
Add error constants for contrib-eme specific errors.
Add constants that are representative of the separate keysystems for error reporting out of videojs-contrib-eme, also add errors specific to each step in the EME specific process.
Two notable omissions:
No errors for `remove` or `load` on the mediakeysession as they're not implemented in contrib-eme.
=> chore: add contrib-eme errors

package-lock.json, package.json
Update http-streaming to version 3.12.0
This includes changes regarding the `customPixelRatio` vhs property, as well as some mux.js fixes regarding 608 captions.
=> chore: update VHS to v3.12.0

src/js/consts/errors.js
Add and remove some error constants specific to `videojs-contrib-eme` errors.
Remove the keysystem specific errors as the keysystem is now passed as error metadata and add errors for `remove` and `load` calls on the `MediaKeySession`
=> fix: add additional and remove unused error const

src/js/control-bar/progress-control/time-tooltip.js
[spaceRightOfPoint](https://github.com/videojs/video.js/blob/main/src/js/control-bar/progress-control/time-tooltip.js#L75) is always `NaN` for [mouse time display](https://github.com/videojs/video.js/blob/main/src/js/control-bar/progress-control/progress-control.js#L84) (unlike playProgressBar's time display) because the [seekbarRect](https://github.com/videojs/video.js/blob/main/src/js/control-bar/progress-control/progress-control.js#L75) ([dom.findPosition(seekbar)](https://github.com/videojs/video.js/blob/main/src/js/utils/dom.js#L503)) does not have a `right` property. 
And since spaceRightOfPosition is always `NaN`, when the mouse tool tip is moved close to edge of the right side player, it's position is not adjusted as it is on the left and so it get's cut off.
The proposed change …
=> fix: time tooltip truncated

src/js/player.js, src/js/utils/browser.js, test/unit/player.test.js
This adds a convenience property, `IS_SMART_TV`, to the `browser` object to detect a device that is either Tizen or WebOS.
Also, added class names to the player for CSS targeting on various devices based on user agent data.
- Add `browser.IS_SMART_TV` boolean
- Add class name `vjs-device-webos` and `vjs-device-smart-tv` on WebOS Smart TVs
- Add class name `vjs-device-tizen` and `vjs-device-smart-tv` on Tizen Smart TVs
- Add class name `vjs-device-android` on Android devices
- Add class name `vjs-device-ipad` on iPads
- Add class name `vjs-device-iphone` on iPhones
=> feat: add browser.IS_SMART_TV and class names for CSS targeting devices

docs/translations-needed.md, lang/ar.json, src/js/control-bar/skip-buttons/skip-backward.js, src/js/control-bar/skip-buttons/skip-forward.js
Added two Arabic new seek button translations.
Arabic translations for `Skip backward {1} seconds` and `Skip forward {1} seconds`.
=> feat(lang): added arabic seek button translations

.github/workflows/ci.yml, src/js/player.js
Updates actions to address GitHub's Node 16 deprecation.
Updating codecov to v4 hopefully improves the reliability uploading. This change means contributors wanting codecov in their forks need to add a `CODECOV_TOKEN` secret to their repository with their codecov token.
Removes the xvfb action as avfb is available by default on ubuntu in GitHub Actions.
=> chore: update GitHub Actions version and remove xvfb

src/css/components/_text-track.scss
https://github.com/videojs/http-streaming/pull/1408 updated 608 captions to default to be left aligned. This may be unwanted by some folks and we should provide an easier way to force them to be centered. This PR adds a player level class that will override the text alignment to be `center`. It also overrides the `width` to `80%` because otherwise the cue box isn't set up correctly to be 10% from the right of the display area (a side effect of hardcoding a width value and using inset in the generation of the cues).
=> feat(emulated-tracks): add class to force cues to be center aligned

package-lock.json, package.json
Update VHS to v3.12.1 for some bug fixes
update the package.json with `http-streaming` v3.12.1, and `npm install` to add the lock changes.
=> chore: update VHS to v3.12.1

src/js/component.js, src/js/spatial-navigation.js, test/unit/spatial-navigation.test.js
Minor update related to the 'spatial navigation' feature to make 'searchForTrackSelect_' private & use 'el' as parameter in function 'getIsFocusable', since in some cases there can be an issue only using 'this.el_' when the function is called.w
=> feat(player): Make 'searchForTrackSelect_' private & use 'el' as parameter in function 'getIsFocusable'

src/js/consts/errors.js
Removes error consts that are outside of the video.js repo. These error consts are being added directly to the contrib-ads and contrib-eme repos.
- Remove error consts that are used in video.js plugins.
=> chore: remove plugin errors from error const

src/js/utils/dom.js, test/unit/utils/dom.test.js
If a MacOS trackpad is using "tap to click", the tap/click was being ignored by the seek bar sometimes, so there would be no seek. This is because the `mousedown` MouseEvent has `{button: 0, buttons: 0}` or `{button: 0, buttons: 1}` inconsistently.
- Adds a case in utils/dom to consider `(event.type === 'mousedown' && event.button === 0 && event.buttons === 0)` a click.
- Removes a conflicting test. That is covered by the test above it for the `mousemove` event.
Fixes #8691, #7736
=> fix: Support MacOS trackpad with tap-to-click

src/js/control-bar/progress-control/seek-bar.js, test/unit/controls.test.js
At the end of the video progress bar not in the end. 
This is random behavior and it is best visible on short videos.
The player shouldn't throttle 'ended' event.
=> fix: progress bar sometimes is not filled on 100%

src/js/utils/url.js, test/unit/utils/url.test.js
Replaces some now unnecessary fallbacks with the standard `URL` API.
`parseUrl` new returns an actual `URL` instead of a `URL`-like object.
Updates tests slightly: `getAbsoluteURL()` to match `URL`'s behaviour with trailing slashes, and use a `URL` object in the cross origin tests. 
Adds a test for `getAbsoluteURL()` with a relative URL
=> refactor: use URL API

src/js/video.js
Addresses an issue where activating the `restoreEl` option for an element at the root of a shadow DOM threw a "TypeError: el.parentNode.hasAttribute is not a function". The bug was due to the `parentNode` being a shadow root, which does not have the `hasAttribute` method.
The fix implemented checks for the existence of the `hasAttribute` method on `parentNode`.
=> fix: prevent error for root shadow elements when restorEl is enabled

src/js/player.js, test/unit/player.test.js
Adapts the `player.height` to the `controlBar.currentHeight` when the `audioOnlyMode` is `enabled`. This ensures that the player height and control bar height are always in sync when the player is resized.
This issue occurs when the `responsive`, and `audioOnlyMode` options are set to `true`, and the base font size adapts based on the player’s size to create a more responsive user interface.
[Screencast from 27. 01. 24 13:28:25.webm](https://github.com/videojs/video.js/assets/34163393/2d365573-d0b8-426b-8b71-9114f98d82bc)
- open [codepen](https://codepen.io/amtins/pen/LYvBOKj)
- resize the page until a breakpoint is reached
```html
<style>
.video-js {
font-size: 20px;
width: 100%;
}
.vjs-layout-small,
.vjs-layout-medium,
.vjs-layout-large {
font-size:10px;
}
</style>
<video id="player" …
```
=> fix(player): adapt player height to control bar height in audioOnly mode

src/js/consts/errors.js
Refactor error constants to a generic streaming set.
Remove unused error constants and replace with generic streaming errors.
=> feat: refactor error consts

src/js/tracks/text-track-settings.js, test/unit/tracks/text-track-select.test.js
Fixes new text track settings, so that `aria-labelledby` attributes contain only valid attributes. Currently there is one invalid id, and two els with duplicate ids.
Fixes #8708 
Updates text-track-settings.js to set the `id` property to an empty string where there is no `label`, only a `legend` element.
Adds tests to validate aria-labelled by values.
=> fix: Ensure aria-labelledby values in track settings are valid

package-lock.json, package.json
update VHS to v.3.13.0
change VHS to 3.13.0 and `npm install`
=> chore: update VHS to v3.13.0

.jsdoc.js, build/jsdoc-workarounds.js
This typedef uses typescript syntax which jsdoc itself doesn't understand. That causes `npm docs:api` to exist with an error code, so docs.videojs.com doesn't update on Netlify.
https://github.com/videojs/video.js/blob/f05769d116e0beac7b9fcde1695db4da74ade124/src/js/media-error.js#L81
This adds a hack as a jsdoc plugin to replace the typedef with valid albeit less accurate jsdoc.
=> fix(docs): Add workaround for ErrorMetadata typedef

package-lock.json, package.json
Added support for newer @videojs/http-streaming versions.
Expected outcome is release of video.js v7.21.6.
=> feat: Update VHS to 2.16.3

src/js/utils/events.js
Adds `mozPressure` and `mozInputSource` to the list of event properties not to cover, as reading them triggers deprecation warnings.
=> fix: Remove Firefox warnings about deprecated event props

src/js/player.js, src/js/utils/browser.js, test/unit/player.test.js
Some people may want to use Video.js as part of their Chromecast receiver application - particularly for UI customization. This PR builds on #8676 by adding feature detection for a Chromecast receiver context.
I did not test this on a cast device as I do not own one!
- Add `browser.IS_CHROMECAST_RECEIVER` boolean
- Add `vjs-device-chromecast-receiver` class name for players running on a Chromecast receiver device
=> feat: add browser.IS_CHROMECAST_RECEIVER and class name for CSS targeting on a Chromecast receiver where Video.js is used

package-lock.json
Updating our Karma dependency accidentally overwrote the VHS version in the lock. See: https://github.com/videojs/video.js/pull/8743
`npm install` and sync the lockfile to the package.json
=> fix: lockfile for vhs v3.13.0

src/js/tracks/text-track-settings-font.js, test/unit/tracks/text-track-settings.test.js
Prevents a duplicate id in text track settings.
Fixes #8754
The text edge settings were erroneously duplicating the id generated for the background colour. Changes to a unique name.
Adds a general test for duplicate ids.
=> fix: removes duplicate id in text track settings

src/js/tracks/text-track-select.js
The fix for the previous issue with the new text track settings introduced that ids would be re-used across players as there was no prefix for the settings that don't have a `<label>` for their `<select>`.
This change uses a generated guid for items without that label.
Fixes #8761
=> fix: use guid to ensure uniqueness of track setting options

package-lock.json, package.json, src/js/utils/create-logger.js
Typescript =< 5.2 generated better types for `log` than >= 5.3. We're on 5.5 as that has the better import syntax.
Changing createLogger to use `function log()` rather than `const log = function()` outputs as before.
Also updates typescript to 5.5.1 (rc) from 5.5.0 (beta).
5.2, or 5.5 with this change
```
export default log;
declare const log: {
(...args: any[]): void;
createLogger(subName: string, subDelimiter?: string, subStyles?: string): any;
createNewLogger(newName: string, newDelimiter?: string, newStyles?: string): any;
levels: any;
level(lvl?: "info" | "error" | "all" | "debug" | "warn" | "off"): string;
history: {
(): any[];
filter(fname: string): any[];
clear(): void;
disable(): void;
enable(): void;
};
error(...args: any[]): any;
warn(...args: any[]): any;
debug(...args: …
```
=> fix: improve ts output for create logger

package-lock.json, package.json
Update VHS to v3.13.1 for a bug fix, specifically for encrypted fmp4.
https://github.com/videojs/http-streaming/releases/tag/v3.13.1
Update VHS from v3.13.0 to v3.13.1 for the fix.
=> fix: update to VHS v3.13.1

package-lock.json, package.json
Update to release of Typescript 5.5 (5.5.2) from rc (5.5.1). Diff shows no changes in types output.
=> chore: Update typescript to 5.5.2

src/js/menu/menu-item.js
This fix addresses an issue that was introduced in this [refactor](https://github.com/videojs/video.js/commit/35de64ceb04b4b7dd6be067e275128d02c6d6e91#diff-9fd94576fe3b609171a426feb961b0954d70c8c14e598024d49ae9c8836a71ca). At the moment, all key down events that are supposed to interact with the `menu-item` component are now being ignored, meaning you are unable to interact with most of the menu items in the control bar (e.g. captions settings). This PR fixes that by only ignoring key down events that are normally ignored by the `menu-item`.
=> fix: enable keyboard controls on menu items

src/css/components/_audio.scss, src/js/control-bar/audio-track-controls/audio-track-menu-item.js
Fix #8769 for mismatched track kind should be plural descriptions according to definition of `AudioTrackKind`
https://github.com/videojs/video.js/issues/8769
Pluralisation
=> fix: apply correct styles to audio descriptions track menu items 

src/js/component.js, src/js/player.js, src/js/video.js
- Removes erroneous `@return {Component}` from `ReadyCallback` in Component
- Remove `@this {Component}` from `ReadyCallback` in Component, because this is not accurate for classes that extend Component
- Adds `@returns {void}` to `ReadyCallback` in Component
- Produces a more accurate typedef
- Isn't strictly accurate in jsdoc/javascript but does this matter since it's well understood. Absence of `@return` is interpreted by tsc as returning `{any}`, `@returns {undefined}` would require an explicit `return undefined` in ts.
- Adds a `{PlayerReadyCallback}` in Player with `@this {Player}` used in the `new Player()` and `videos()` constructors.
- Are we ok adding this new typedef
- Is inconsistent with `player.ready()` which uses `ReadyCallback` without `@this` - but this can't be changed …
=> fix(types): fix and improve component ready callback definition

src/js/transient-button.js
Transient button sets an event listener on the player directly instead of on itself, which doesn't get cleaned up when disposed.
Fixes #8795
Call `on` on the component with player as the first arg, instead of calling `on` on the player directly.
=> fix: ensure transient button event listeners are removed on dispose

package-lock.json, package.json
=> chore: update vhs version 3.13.2

package-lock.json, package.json, src/js/mixins/evented.js
Chrome 53 doesn't like the minified output. Specifically, it throws `Uncaught SyntaxError: Unexpected token (` on the ternary in the minified version of `normalizeListenArgs()`
https://github.com/videojs/video.js/blob/e78bcc7b2d829fce01451cf105b918d8feec4548/src/js/mixins/evented.js#L165-L195
Line breaks added for clarify
```js
Tt = (e, t, s) => {
var i = t.length < 3 || t[0] === e || t[0] === e.eventBusEl_;
let r, n, a;
return i ? (r = e.eventBusEl_, 3 <= t.length && t.shift(), [n, a] = t) : [r, n, a] = t, ft(r, e, s), yt(n, e, s), bt(a, e, s), a = _(e, a), {
isTargetingSelf: I,
target: r,
type: n,
listener: a
}
},
```
Chrome would be happy with this if `[r, n, a] = t` were `([r, n, a] = t)`.
Refactor `normalizeListenArgs()` slightly to use multiple statements to coerce uglify-js to …
=> fix: Refactor evented to make mincompatable with Chrome 53

src/js/tracks/text-track-settings.js
The refactored text track controls aren't listening for tap events.
Add tap handler to done and reset buttons.
Fixes #8808
=> fix: Listen to taps on track controls

src/js/spatial-navigation.js, test/unit/spatial-navigation.test.js
The bug:
Focus is lost when playback error is displayed.
This small PR will update the spatial-navigation logic so when the error modal is shown the spatial-navigation will try to focus the components present in the error modal, in most cases this will be the vjs close button.
Keep navigation working when player shows the error modal by focusing a component in that modal.
=> fix(spatial-navigation): keep navigation going when player has an error

src/js/modal-dialog.js, src/js/spatial-navigation.js, test/unit/spatial-navigation.test.js
The spatial-navigation is unable to focus certain elements of the error modal when this appears, this PR will fix that
Allow the spatial-navigation to focus certain non-component elements in the error modal
=> fix(spatial-navigation): focus lost in error modal

src/js/spatial-navigation.js
This PR will make the refocus available not only to the buttons of the error modal but also to the close button of the error modal on the event of 'aftermodalfill'.
Allow the spatial-navigation to refocus the error modal when error modal appears.
=> fix(spatial-navigation): refocus available also to the close button of the error modal

src/css/components/_close-button.scss, src/css/components/_layout.scss, src/css/components/_volume.scss
Some of the existing rules would be interpreted differently in a future version of SASS. In the current version, they trigger a deprecation warning. See https://sass-lang.com/documentation/breaking-changes/mixed-decls/
Re-orders rules to maintain current output and remove warnings. The output of video-js.css and video-js.min.css remains the same.
=> refactor: Reorder SASS styles to address deprecation

package.json, src/js/player.js, test/unit/setup.test.js, test/unit/tracks/text-track-settings.test.js
Removes an old unmaintained dependency that isn't needed any more.
Replace safe-json-parse with `JSON.parse`
=> chore: Remove safe-json-parse

package-lock.json, package.json
Update http-streaming to v3.13.3
- Update package.json and package-lock.json with new version of VHS.
=> chore: update http-streaming to v3.13.3

src/js/component.js, test/unit/component.test.js
The current implementation of `requestNamedAnimationFrame` prevents multiple updates on a frame but by disregarding all but the first request per frame. This throttling behaviour is apparent when playing a very short video - if a `timeupdate` occurs just before the `ended` event, the progress bar position on the `timeupdate` is set at say 98% and 100% from the  `ended` is discarded. Although #8633 removed the throttle from the `ended` handler itself, the throttle and non-throttled update can still both execute between frames.
Changes the implementation to apply only the last callback instead. If any exist they will be cancelled. There will still be only one update, but now it's the last.
Updates tests to reflect the changed behaviour. 
Fixes #8782
=> fix: Change requestNamedAnimationFrame to apply last change per frame instead of first

src/js/component.js, src/js/utils/dom.js
Generated types are mangled for `Component.toggleClass()`, because tsc doesn't understand `~` namespaces. The second arg is then not marked as optional. 
Refactor JSDoc
=> fix(types): ensure toggleClass's second arg is optional

src/css/components/_text-track.scss, src/js/tracks/text-track-display.js, test/unit/tracks/text-track-display.test.js
In the specific case of using an old chrome version this minor changes will allow the captions to be shown.
Small fix when using videojs in an old browser that does not support the css 'inset' property.
=> fix: allow captions in devices that use old chrome to be shown

src/css/components/_text-track.scss
Small fix to use backup styles only when inset is not supported.
Use backup styles only when inset is not supported.
=> fix: use backup styles when inset is not supported

build/readme-version.js, package.json
Updates the version number where it appears in URLs in the README, when `nom version` is ran. It's looking specifically for patterns like `/8.17.3/` and `/video.js@8.17.3/`; if we change the README we need to consider this script.
New script at build/readme-version.js
=> chore: update version number in readme on release

src/js/player.js, test/unit/player-user-actions.test.js
Double clicking the document pip window requests fullscreen but this fails. The gesture on the pip window can't initiate fullscreen.
Fixes #8877
Change the default double click action to just exit pip. This is the same behaviour as before without the error, as requestFullScreen() calls exitPictureInPicture();
=> fix: Don't request fullscreen from document PIP window

src/js/player.js, src/js/tech/html5.js, test/unit/player.test.js, test/unit/tech/html5.test.js, test/unit/tech/tech-faker.js
It is useful to have methods for appending and removing `<source>` elements to the `<video>` element, as they are sometimes required to enable certain playback features, for example, using [Airplay with MSE](https://webkit.org/blog/15036/how-to-use-media-source-extensions-with-airplay).
Add new methods-- `addSourceElement()` and `removeSourceElement()` to the player and tech. The former will take a source object and create and append a new `<source>` element to the `<video>` element, and the latter will take a source url and remove any `<source>` element with a matching `src`.
=> feat: Add methods to add and remove <source> elements

package-lock.json, package.json
=> chore: update mpd-parser to v1.3.1

package-lock.json, package.json
Bump the VHS dependency version to v3.15.0
=> chore(package): update http-streaming to v3.15.0

src/js/tracks/text-track-fieldset.js, src/js/tracks/text-track-select.js, test/unit/tracks/text-track-settings.test.js
Localization is not applied correctly in fieldset labels and select options. As a result, the text track setting modal dialog is only half translated.
- add `localize` at `label` level in `TextTrackFieldset`
- add `localize` at `option` level in `TextTrackSelect`
- add test cases
=> fix(text-track-settings): localization not correctly applied

src/js/menu/menu-button.js, test/unit/menu.test.js
Fixes that Escape being pressed isn't closing menus due to incorrect `event.key` name.
Fixes #8915
Replaces `Esc` with `Escape`.
=> fix: Fix Escape handling in menus 

docs/examples/elephantsdream/index.html, docs/examples/simple-embed/index.html
Two examples use http and not https.
`href=http` changed to `href=https` in two places in two files.
=> fix: change http to https in examples

package-lock.json, package.json
=> chore(package): Update @videojs/http-streaming to 3.16.0

src/css/components/_progress.scss, src/js/control-bar/progress-control/progress-control.js, src/js/control-bar/progress-control/seek-bar.js, src/js/player.js, test/unit/controls.test.js, test/unit/player.test.js
On desktop, a user can hover over the progress bar while content plays, which makes it possible to seek to a relatively precise location without disrupting playback. On mobile there is no hovering, so in order to seek during inline playback the user can only tap a location on the progress bar (very hard to do precisely on a small screen) or scrub to try to hone in on a specific location (can be very clunky because seeks are constantly being executed). This PR adds a feature to treat scrubbing on mobile more like hovering on desktop-- while scrubbing, seeks are disabled and playback continues, only when the user finishes scrubbing is a single seek executed to the desired location.
One key use-case for this feature is thumbnail seeking integrations on mobile, where the user can scrub …
=> feat: Add option to disable seeking while scrubbing on mobile

lang/oc.json
=> chore: update Occitan locale file

src/css/components/_progress.scss
Problem: the vjs-user-inactive class triggering the hiding of the tooltip is added much later on touch devices, therefore the mouse tooltip stays visible on its last seek target position whenever the user taps the screen to access the controls.
This change ensures that the mouse tooltip is only visible when the user is actually scrubbing.
=> fix: hide mouse tooltip on touch devices when not scrubbing

src/css/components/_volume.scss, src/js/tracks/text-track-list-converter.js, src/js/tracks/text-track-list.js, src/js/tracks/text-track.js, test/unit/tracks/text-track-list-converter.test.js, test/unit/tracks/text-track-list.test.js, test/unit/tracks/text-track.test.js
Adds `toJSON` method to both the `TextTrack` and `TextTrackList` classes. The `toJSON` method creates a serializable JSON object from the track or track list.
There was an issue when attempting to serialize (JSON.stringify()) `player.textTracks()` due to circular references in `textTracks.tech_`. These methods create serializable copies of textTracks so a user has a way to serialize this data.
Since JSON.stringify calls `toJSON` natively, it will use this new overidden `toJSON` method instead of the native method. `JSON.stringify(player.textTracks())` will now be a valid serialized string. Previously, it threw an error.
- Add `toJSON` methods to `TextTrack` and `TextTrackList` classes
- Tests for the above methods
=> feat: toJSON methods for text track serialization

src/js/utils/url.js, test/unit/utils/url.test.js
More robust edge case handling for getFileExtension().
**Case** : Type is not provided explicitly in {src,type} object.
In this case getFileExtension() is called to fetch the extension so as to get the type.
For certain cases, fn does not returns the correct extension.
For Eg: 
1. https://demo.unified-streaming.com/k8s/features/stable/video/tears-of-steel/tears-of-steel.ism/.m3u8
In this case fn returns "". 
I have simplified getFileExtension() so that fn will return m3u8 in this case as well.
Simplified getFileExtension() for better readability and to handle more edge cases.
=> fix: Improve getFileExtension() readability and handle leading dot extensions.

src/js/tracks/text-track.js
Resolves captions sizing issue when minified #8442
This bug discussed and confirmed. A fix has been released shortly for videojs8 but verison 7 still haven't fixed. #8370 
Same fix applied at #8442
=> fix: Resolves captions sizing issue when minified (v7)

src/js/tracks/text-track-settings-controls.js
Fixes text track modal controlText.
Only apply reset text to the `Reset` button and done text to the `Done` button.
=> fix: controlText for text track modal

src/js/big-play-button.js
References #9006. Minor extension of #4497.
Don't set focus after tapping on the big play button
=> fix: only change focus from BPB if not tap or mouse click

CHANGELOG.md
This pull request fixes a broken link found in the CHANGELOG.md for version 8.19.0. 
The link has been updated to ensure it directs users to the correct resource. This change enhances the documentation accuracy and improves user experience.
- Updated the link in the CHANGELOG.md file to point to the correct issue.
=> Fix broken link in changelog for version 8.19.0

src/js/tracks/text-track-display.js
This is an attempt to fix https://github.com/videojs/video.js/issues/6207
Added event handlers for 'useractive' and 'userinactive' events to update text tracks display position so that they reposition when the control bar is shown or hidden
=> fix: update text-track-cue styles on useractive

.github/workflows/release.yml
Our automated release workflow has been failing for a while. A search of the error message turned up https://github.com/softprops/action-gh-release/issues/236, which suggests that the "contents" permissions for the workflow need to be set to "write".
⚠️ This change may break the intent of #8911, but it's not clear to me from that PR whether a permission of `read` is necessary for the provenance protection.
=> fix: release workfow permissions

.github/workflows/release.yml
#9027 only fixed one issue with the release workflow. [The last release run](https://github.com/videojs/video.js/actions/runs/14489334201/job/40641922135#step:10:26) failed with:
```
👩‍🏭 Creating new GitHub release for tag v8.23.2...
⚠️ GitHub release failed with status: 404
undefined
retrying... (2 retries remaining)
👩‍🏭 Creating new GitHub release for tag v8.23.2...
⚠️ GitHub release failed with status: 422
[{"resource":"Release","code":"already_exists","field":"tag_name"}]
```
The initial 404 appears to have be caused by a lack of [permission for discussions](https://github.com/softprops/action-gh-release?tab=readme-ov-file#permissions), and then subsequent tries fail because the tag already exists.
Add `write` permission for `discussions`
=> fix: update release workflow `discussion` permission

src/js/component.js
removeChild() in component.js was missing the string as an acceptable parameter due to which ts complaints.
Example : player.removeChild('controlBar');
Error : **Argument of type 'string' is not assignable to parameter of type 'Component'**
1. Added `string` in the jsdoc for removeChild() in component.ts.
2. Updated comment for removeChild().
=> fix(component.js): Updated JS Doc for removeChild()

.jsdoc.js, LICENSE, README.md, package.json
Update the LICENSE file and project documentation to more accurately reflect the history and current governance of Video.js.
Brightcove has never required contributors to sign a Contributor License Agreement (CLA) or transfer copyright. As a result, the existing “Copyright Brightcove, Inc.” line was misleading, since Brightcove doesn’t own all contributions.
This change:
Keeps the Apache 2.0 license text exactly as-is.
Updates the attribution to accurately reflect the distributed ownership of the codebase. Aligns with common open source practice for projects without a CLA or copyright assignment. Acknowledges that Brightcove has registered the Video.js trademark.
This is a documentation-only change — it does not affect licensing terms, the license type (Apache 2.0), or project usage.
=> docs: Clarify copyright, CLA, and project stewardship
